### ISSUE TITLE
Logout doesn't work

### ISSUE THREAD

**Issue by vladaman** [salesagility/SuiteCRM#10019]
After an upgrade to 8.2.2 the Logout from Web interface doesn't log out the user. I get notification message "Logout successful", user is redirected to #home but the session is still valid.

**Comment by pgorod** [comment]
Please fill in the details of OS, PHP version, etc, they are relevant.

**Comment by pgorod** [comment]
There are some potentially useful browser console messages here:

https://community.suitecrm.com/t/8-2-4-logout-impossible/88761/20?u=pgr

**Comment by jugvialet** [comment]
Do You have any any updates on it?

**Comment by pgorod** [comment]
I'm closing this issue since it is incomplete, can't be replicated, and is probably stale at this point. If the original poster or anyone else still feels the need for the issue, please open a new one with the newer 8.2.4 version and fill in the complete Issue template.

The Community Forums are also a good place to ask.

https://community.suitecrm.com/
