### ISSUE TITLE
Logic hooks and email relationships

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#104]
Some beans (at least Accounts, probably Contacts) that inherit emails will fire the "after_save" event before the bean has persisted the email address relationships to the database. This can cause odd issues if, for example you have a workflow which calls an external service which then queries for the bean. The returned data will not have any email addresses associated because the email addresses haven't made it to the database yet.

This will be tricky to work around since the SugarBean->save is being called by a child class which then does it's own saving work. It would be nice if we could investigate if it's reasonable to "fix" this (changing it could affect other parts of SuiteCRM) and ways of doing that.

**Comment by ESRuth** [comment]
Perhaps this could be solved with another option from the workflow module. A trigger that fires after the full save is done? It's still an enhancement, but it could be easier than having to make sure that the change is completely backward compatible.

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Logic hooks and email relationships](https://trello.com/c/4BVDlOzs/164-logic-hooks-and-email-relationships)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by chris001** [comment]
🤦‍♂️  This is clearly a bug in the SugarBean and database classes.  Workflow logic is getting false negatives on email relationships, because the data layer is allowing Workflow to get at incomplete updated data, which ought be locked during the update.  Workflow logic shouldn't be permitted to run on partial data during mid write.  Should be using pessimistic locking and transaction begin and end instead of autocommit and optimistic.  Google phantom read, dirty read, transaction, pessimistic locking, atomic.
