### ISSUE TITLE
In 7.5.2 select create Account and cancelling from Home screen goes to error page

### ISSUE THREAD

**Issue by mikesolo** [salesagility/SuiteCRM#1057]
In the home screen if you use the + button to Create an Account/Contact etc then when you get the EditView press cancel instead of taking you to the modules List View it now tries to go to DetailView and fails

"Error retrieving record. This record may be deleted or you may not be authorized to view it."
I have tested it in 7.5.1 and it works properly

**Comment by paulgodley** [comment]
Hi @mikesolo, I have just checked out from the 7.5.2. hotfix branch and installed this with the test data.  In both Chrome and Firefox, when I follow the steps you outlined, I am taken to the appropriate List View (accounts, contacts, etc.).  Can you please try a quick repair and rebuild and let me know if the problem is still happening?  Also, can you tell me which browser that you are using and I will try to emulate the issue?  Many thanks.

**Comment by gymad** [comment]
May help: It seems related to issue #893 . The first subversion where the error occurred at the dd08e8 commit when the cancel button changed.

**Comment by paulgodley** [comment]
Thanks @gymad, I will check that out.

**Comment by paulgodley** [comment]
Hi @mikesolo, I can now replicate your issue.  I will update with the fix as soon as possible.

**Comment by mikesolo** [comment]
@paulgodley Thanks that fixed it

**Comment by jellydonuts** [comment]
i was getting this with the tasks module as well... is this fixed all around?
