### ISSUE TITLE
iCal synchronisation fails

### ISSUE THREAD

**Issue by timo12357** [salesagility/SuiteCRM#1077]
The iCal synch fails.
It requests user name and password and accepts none.
SuiteCRM Version 7.3.2 running on a Centos 5.10 server
Calendar client is Evolution on Ubuntu 14.04

This issue has been discussed quite a lot on the forums:
https://suitecrm.com/forum/bug-tracker/3325-bug-ical-patch-not-working-after-upgrade
http://developer.sugarcrm.com/2012/05/29/new-in-sugar-6-5-ical-support-for-calendar/

**Comment by chris001** [comment]
@chandon has posted a fix.
https://github.com/sugarcrm/sugarcrm_dev/pull/220
I asked chandon to fork hotfix and do a pull request with details on how to test it so others can confirm fix....

**Comment by chandon** [comment]
I don't think my fix is related to this username/password problem. My fix was linked to iCal format and Encoding problem on sugarCrm. The iCal format problem was solved with suiteCRM, not the encoding. For encoding problem, see my PR #1163 

Perhaps this problem is more a Client problem. You don't need a password in your client configuration, the username/password is already included in the URL of the suiteCRM Ical Integration URL (ok, it's not really secure, if you want a more secure way to protect it, you can add Basic Auth with your web server and configure it in your client, but it's not related to suiteCRM)

**Comment by primozn** [comment]
**Issue:** Can't sync with iphone, gmail and Thunderbird Lightning.

I get this error If i run iCalendar Validator on site: http://severinghaus.org/projects/icv/ 
Your calendar parsed, but with errors.
Error:	Error was: Invalid property: DTSTAMP
Cause:	Sorry, I couldn't get an exact cause.

**My environment:** SuiteCRM 7.7.2, PHP 7.0.5, Apache 2.4.18

**Comment by Florian6901** [comment]
primozn i have the sam bug, no outlook and google sync with my suitecrm calendar, did you find a solution?
http://img4.hostingpics.net/pics/288795icalerror.png

**Comment by primozn** [comment]
No, can't get it to work :(

**Comment by mattlorimer** [comment]
for 7.7.x+ ical will be fixed in this pr #2098

**Comment by Florian6901** [comment]
Thank you very much, it works at last!
