### ISSUE TITLE
AOR_Reports - Condition date format compared to system date format

### ISSUE THREAD

**Issue by jellydonuts** [salesagility/SuiteCRM#1082]
If you have a report condition of a date and run it as a user with a different date format than that of the format used to create the report item, no results are shown.

This is because the underlying SQL query's date format is different (not converted to the system's date format) in which the report item was saved.

Example:

1. Created new task using user's date format (dd.mm.yyyy), task is saved to db using the system date format (yyyy-mm-dd)
2. Run report using condition of the date > value > 03.11.2016 (user's date format)
3. SQL query uses this same date format to try and select entries when it should be converting the format to the system's format which is what is being saved into the database.

Task in its table
`| 54bb6397-7de3-7d0e-1fd1-56e309dfac5e | test                   | 2016-03-11 18:09:30 | 2016-03-11 18:09:30 | 1                | 1          |             |       0 | 1                                    | Completed   |             0 |
`

Section of the SQL query to select the task
``( `tasks_cstm`.task_started_c >= '03.01.2016' AND `tasks_cstm`.task_started_c < '03.31.2016' )``

**Comment by jellydonuts** [comment]
see attached screenshot, since you're not verifying if the field is a date value before the conversion, it converts all empty fields to "NaN-NaN-NaN" (not a number).

![broken-nan](https://cloud.githubusercontent.com/assets/1541720/14472357/b1b966d0-00a7-11e6-8781-68c2370030d1.jpg)

**Comment by nelem** [comment]
There's still a problem with #1802 which converts the UI date to a db date because it depends on the user's date format which can be mm/dd/yy or dd/mm/yy and is a problem when both dates are  valid. E.g. 2 Nov 2017 looks valid both ways round.

fieldInput = $.datepicker.formatDate('yy-mm-dd', new Date(fieldInput)); <== Need to know user's date format in Javascript.

Is there any way to get the user's date format in the UI Javascript?

**Comment by nelem** [comment]
See PR #4506
