### ISSUE TITLE
Reminder Meetings/Alerts performance issues

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#1128]
Speed/performance issues regarding reminder meetings and alerts is an issue that has been raised by many users. Logic should be reviewed and optimised where possible.

See forum post/topic for full details: https://suitecrm.com/forum/feedback/8320-performance-issues-regarding-suitecrm-reminders-alerts-logic

**Comment by vladbar** [comment]
I tried to replicate this issue (created 500 reminders with different invitees) and could not see any problems. 
The 2 lines which were mentioned in the forum:

$popupReminders = BeanFactory::getBean('Reminders')->get_full_list('', "reminders.popup = 1");
and 
$invitees = BeanFactory::getBean('Reminders_Invitees')->get_full_list('', "reminders_invitees.reminder_id = '{$popupReminder->id}' AND reminders_invitees.related_invitee_module_id = '{$current_user->id}'");

belong to a function called addNotifications. This function is called only occasionally (in order to create the necessary data) and the mentioned lines are needed there (see below):

#####################################################
--- ### addNotifications is called only once: ### ---
#####################################################
1. /var/www/html/585/SuiteCRM/include/javascript/jsAlerts.php - 47 inside constructor; calls Reminder
Reminder::addNotifications($this);

2. /var/www/html/585/SuiteCRM/modules/Reminders/Reminder.php - 262 goes through every reminder
public static function addNotifications(jsAlerts $alert, $checkDecline = true) { 
	...
	$popupReminders = BeanFactory::getBean('Reminders')->get_full_list('', "reminders.popup = 1");
	...

3. /var/www/html/585/SuiteCRM/include/MVC/View/SugarView.php - 150 calls new jsAlerts(); and $jsAlerts->getScript();
        // We have to update jsAlerts as soon as possible
        if (
            !isset($_SESSION['isMobile'])
            &&
            (
                $this instanceof ViewList
                || $this instanceof ViewDetail
                || $this instanceof ViewEdit
            )
        ) {
            $jsAlerts = new jsAlerts();
            echo $jsAlerts->getScript();
        }

4. /var/www/html/585/SuiteCRM/jssource/src_files/include/javascript/sugar_3.js - 256 checkAlerts() is called from getScript()
function checkAlerts() {
	...
	alertsTimeoutId = setTimeout("checkAlerts()", 1000); - calls itself every second 
	... 

Conclusion: addNotifications is called only once;
checkAlerts() is called every second and uses the data which was created by addNotifications()

another suggestion was is to fix this line by adding a where clause with filtering by dates:
$popupReminders = BeanFactory::getBean('Reminders')->get_full_list('', "reminders.popup = 1");
but this function really needs to get all the reminders in order to check relatedEvent first.
		if($popupReminders) {
			foreach($popupReminders as $popupReminder) {
				$relatedEvent = BeanFactory::getBean($popupReminder->related_event_module, $popupReminder->related_event_module_id);
