### ISSUE TITLE
Studio - Required address fields issues

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#1181]
If the Billing Address Street or Shipping Address Street is added to the edit view, the address block is added which has the street, city, state, postal code and country fields within it. If an address field is required, for example the 'Shipping Postal Code', but the field has not been individually added to the edit/detail view the user receives a popup stating that the required field is not on the view. It actually is on the view, as it is part of the address block, but the CRM does not identify this. If the user then adds the field to the view individually, and this field is required, the user cannot save the record. There is no error generated so it is unclear to the user what is wrong.

**Comment by daniel-samson** [comment]
One solution would be to change the street field so that it doesn't add the other fields in place. 

It looks like the design of studio assumes that you had only one instance of a field. 

Perhaps we should add a new place holder in studio for address fields and then have it so that when you drag that into the view ... it will automatically generate the the rows and fields for the address lines.

**Comment by Mac-Rae** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
