### ISSUE TITLE
role permissions for removing Contacts from target lists

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#1238]
I'm running SuiteCRM 7.4.1. I just noticed that I can't remove Contacts from target lists as long as the role action "delete" is set to "owner" for the Contacts module. I don't think this should be happening as it's pretty confusing.

Deleting a contact and removing a contact relationship with a target list should not be part of the same role action, imho. No idea if this was different in previous versions or not.

**Comment by EZS-JD** [comment]
I believe this is actually a bug:
A non-admin user without "delete"  role action permissions on target list module:

_cannot_ unlink contact from target list from within contact detail view (via subpanel target list)
_can_ unlink contact from target list from the target list detail view (via subpanel Contacts)

i.e. the same action can be be taken by one route, but not the other. This is inconsistent and cannot be meant to be?

**Comment by samus-aran** [comment]
This looks like it is standard roles for all modules. i.e. you can not remove a relationship between a Contact and Account via Account if you are not the Contact owner.  Removing a relationship is deleting said relationship.  This filtering has been since the initial commit.

However I am unable to view the Target list subpanel on the Contact's detail view

Feel free to reopen this more of a bug or again a suggestion.
