### ISSUE TITLE
Regression: new SugarBean.php in 7.5.2 breaks relationship fields

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#1241]
I had working customization using a new custom field in a contact-to-contact relationship. The field is a multienum. 

Notice that the field is in the relationship, not in any of the contacts. It was done following these instructions: http://sugarmods.co.uk/how-to-add-custom-fields-to-a-relationship-table-and-display-them-in-a-subpanel-sugarcrm-suitecrm

The field was showing correctly in a subpanel. After the upgrade from 7.5.1 to 7.5.2 it stops showing. No error, just a blank space instead of showing the value. 

I think none of the information from the relationship is being loaded into the bean, but I am not sure, it might be just this field.

After 5 hours debugging, and checking each file, I found that if I copy back data/SugarBean.php from 7.5.1 the issue is fixed...

**Comment by pgorod** [comment]
Upon further investigation, replacing only bits of the file, this is the change that's breaking my system:

https://github.com/salesagility/SuiteCRM/commit/b3246d371f1e5ca6619d342b9d770d6babe09b70

**Comment by pgorod** [comment]
If I understand things correctly, this is the crucial moment as seen in debugging. The code shown here is the one that works. I edited the "if" so that instead of one "if" with two conditions (joined by &&), I turned it into two separate "ifs" to make the break-point more practical.
![debugging-issue-1241](https://cloud.githubusercontent.com/assets/15945027/14560142/a08ae252-0305-11e6-9c11-362652b859e7.png)
In this case, the final "if" will be entered, and the field will be selected to be added. In the broken code of version 7.5.2, there is an additional condition:
`&&     (!isset($value['link_type']) || $value['link_type'] != 'relationship_info')`
... which will cause the field not to be added.

I think this is a bug anyway, but maybe my metadata isn't properly configured. I confess I don't understand exactly what I did, I just tried different things until it worked. Here are the relevant files:

`<?php

// created: 2015-02-17 04:53:59

$dictionary["contacts_contacts_1"] = array (
  'true_relationship_type' => 'many-to-many',
  'from_studio' => true,
  'relationships' =>
  array (
    'contacts_contacts_1' =>
    array (
      'lhs_module' => 'Contacts',
      'lhs_table' => 'contacts',
      'lhs_key' => 'id',
      'rhs_module' => 'Contacts',
      'rhs_table' => 'contacts',
      'rhs_key' => 'id',
      'relationship_type' => 'many-to-many',
      'join_table' => 'contacts_contacts_1_c',
      'join_key_lhs' => 'contacts_contacts_1contacts_ida',
      'join_key_rhs' => 'contacts_contacts_1contacts_idb',
    ),
  ),
  'table' => 'contacts_contacts_1_c',
  'fields' =>
  array (
    0 =>
    array (
      'name' => 'id',
      'type' => 'varchar',
      'len' => 36,
    ),
    1 =>
    array (
      'name' => 'date_modified',
      'type' => 'datetime',
    ),
    2 =>
    array (
      'name' => 'deleted',
      'type' => 'bool',
      'len' => '1',
      'default' => '0',
      'required' => true,
    ),
    3 =>
    array (
      'name' => 'contacts_contacts_1contacts_ida',
      'type' => 'varchar',
      'len' => 36,
    ),
    4 =>
    array (
      'name' => 'contacts_contacts_1contacts_idb',
      'type' => 'varchar',
      'len' => 36,
    ),
    5 =>
    array (
      'name' => 'reltype',
      'type' => 'varchar',
      'len' => 36,
    ),
  ),
  'indices' =>
  array (
    0 =>
    array (
      'name' => 'contacts_contacts_1spk',
      'type' => 'primary',
      'fields' =>
      array (
        0 => 'id',
      ),
    ),
    1 =>
    array (
      'name' => 'contacts_contacts_1_alt',
      'type' => 'alternate_key',
      'fields' =>
      array (
        0 => 'contacts_contacts_1contacts_ida',
        1 => 'contacts_contacts_1contacts_idb',
      ),
    ),
  ),
);
`
and the relevant Vardefs:

`$dictionary["Contact"]["fields"]["e_reltype"] =
 array (
 'name' => 'e_reltype',
 'rname' => 'id',
 'relationship_fields'=>array('id' => 'rel_id', 'reltype' => 'reltype'),
 'vname' => 'LBL_RELTYPE1',
 'type' => 'relate',
 'link' => 'contacts_contacts_1',
 'link_type' => 'relationship_info',
 'join_link_name' => 'contacts_contacts_1',
 'source' => 'non-db',
 'importable' => 'false',
 'duplicate_merge'=> 'disabled',
 'studio' => false,
 );

$dictionary["Contact"]["fields"]["reltype"] =
 array(
 'massupdate' => false,
 'name' => 'reltype',
 'type' => 'multienum',
 'isMultiSelect' => true,		
 'studio' => 'false',
 'source' => 'non-db',
 'vname' => 'LBL_LIST_RELTYPE2',
 'importable' => 'false',
 'options' => 'reltype_options_list',
 );

$dictionary["Contact"]["fields"]["rel_id"] =
 array(
 'name' => 'rel_id',
 'type' => 'varchar',
 'source' => 'non-db',
 'vname' => 'LBL_LIST_RELTYPE3',
 'studio' => array('listview' => false),
 );
`

and finally the relevant subpanel definitions:

`~<?php
// created: 2015-11-27 14:25:35

$subpanel_layout['list_fields'] = array (
  'contacts_contacts_1contacts_idb' =>
  array (
    'usage' => 'query_only',
  ),
  'reltype' =>
  array (
    'name' => 'reltype',
    'vname' => 'LBL_RELTYPE1',
    'width' => '10%',
    'default' => true,
  ),

...etc`

**Comment by gunnicom** [comment]
Thats the commit that changed that line:
https://github.com/salesagility/SuiteCRM/commit/b3246d371f1e5ca6619d342b9d770d6babe09b70#diff-5bb494d1dca998198a61c907931633ba

**Comment by pgorod** [comment]
Yep, that's it. I think we need @mattlorimer 's help here because I don't know exactly what he was fixing, and what he meant that extra condition to do.

Also, I don't have a local GitHub repository, and I'm not very familiar with GitHub, so if somebody else could do the fix for me, I would appreciate it.

Meanwhile, I'm using SuiteCRM with that line corrected manually, I hope nothing bad comes of it...

**Comment by mattlorimer** [comment]
> #743 Accept status is not showing on the meetings subpanels

You likely need extra configuration  to use relationship fields in this way, take a look at how it is configured in events, contacts, opportunities for an example.

**Comment by pgorod** [comment]
@mattlorimer I'm quite surprised at your reply, but maybe I'm missing something. This is not something I was trying just now, I had it working reliably with several other configurations, I have custom Edit screens to edit the relationship fields, I have logic hooks handling the data, etc.

I spent a long time getting it to work because there is no proper documentation. I did quite a lot of Googling at the time (a few months ago) and looked into existing code. But there's only so much one can learn from example. When you need something different from the example, you're often left without any clues. I have already looked at the existing modules, I can look again, but frankly my hopes for clarification aren't that big.

So we really don't know if this is something so easy to dismiss. How many people out there are using this like me, following the same guides I found? How much is it costing them to get their systems broken? And this is a hard bug to pin down. What are the benefits of this change for them? Is it really needed? Can't it be improved?

You could defend your code change; or you could point to the error in my code; but without doing either, and without knowing how many people are affected, it seems risky to just close the issue like this...

My sincere thanks, and apologies if I'm in error.

**Comment by mattlorimer** [comment]
I would suggest that your subpanel defs are wrong where you have
`  'contacts_contacts_1contacts_idb' =>
  array (
    'usage' => 'query_only',
  ),
  'reltype' =>
  array (
    'name' => 'reltype',
    'vname' => 'LBL_RELTYPE1',
    'width' => '10%',
    'default' => true,
  ),`
should be
`		'e_reltype' =>
			array (
				'usage' => 'query_only',
			),
		'rel_id' =>
			array (
				'usage' => 'query_only',
			),
		'reltype' =>
			array (
				'name' => 'reltype',
				'vname' => 'LBL_RELTYPE1',
				'width' => '10%',
				'default' => true,
			),`

**Comment by pgorod** [comment]
I confirm that your suggestion works, even with the changed code in SugarBean from 7.5.2.

Still, I am baffled to see how my code was working so well, and I'm really sorry there is no proper documentation for this kind of customization (so often necessary). Examples are not enough if we don't know _what_ references _what_. Andy's post on this is the best out there, but it would benefit from being updated and expanded...

Anyway, you were absolutely right and I can only reiterate my thanks and apologies.

**Comment by JanSiero** [comment]
Commit b3246d3 fixes the empty accept status fields in the subpanels, but defeats the purpose of PR #61, which introduced the ability of the SugarBean class to look up the required relationship info field by itself.

As the vardefs well-define how each field should be queried, PR #61 was introduced to add the ability to the SugarBean class to query relationship fields, without the need to supply their belonging relationship_info field.

It is true for subpanels, that the corresponding relationship_info field can be added as "require_only" field and there is no need for this ability. However for other usages of relationship fields, for example added them to listviews and filters by Studio, the need to add their relationship_info field as "query_only" by code is not a desired solution.

The following issue underlines this and presents a possible fix. 

#### Issue

 - When using Studio to add the field "opportunity Role" to the listview of Contacts, the values of this field are not displayed
 - Sorting on this field "opportunity Role", by clicking the column header "Role" results in the list not showing entries at all
 - When Adding this field to a Filter, a search does not yield results

#### Expected Behavior

When using studio to add this standard field to Listviews or filters, this should result in displaying its 
contents and using it to for searches.

#### Actual Behavior

Instead, the contents remain empty and it cannot be searched

#### Possible Fix

The original code in PR #61 broke the display of the accept status (issue #743) of meetings, calls and events in subpanels. It is caused by the fact that accept status have multiple relationship_info fields, each for Meetings, Calls and Events, and the lookup did not discern these.

With commit b3246d3 this was fixed, however this broke the ability of SugarBean to query relationship_info fields by itself (issue #1241), effectively undoing PR #61.

PR #8551 reverts b3246d3 and adds a check to make sure only the relationship_info field matching the parent module is used.

#### Steps to Reproduce
1. Create a Contact
2. Create an Opportunity
3. Add the Contact to the Opportunity and change its role to "Decision maker"
4. Open Studio, module Contacts
6. Edit the Listview
7. Add the Field "Role"
8. Save and Deploy the changes
9. Open the module Contacts (ListView), use Column Chooser to add "Role" to the visible fields

=> Expected behaviour:
The Contact is shown with its role "Decision maker"

=> Actual behaviour:
The field value for role for this contact is empty

#### Context

Relationship fields are not common in SuiteCRM, but may be used in different custom modules and scenarios, for example a contact-contact relation. The display of this field in Listviews may be a common requirement. Especially searching for contacts that are decision makers by using role as a filter is very useful and should be supported by SuiteCRM.

#### Your Environment
* SuiteCRM Version used: 7.11.10
* Chrome Version: 51.0.2704.63 (64-bit)):
* Environment: MySQL, PHP 7
* Operating System and version: Ubuntu 16.04

**Comment by JanSiero** [comment]
Withdrawing pull request #8551 because it doesn't resolve lookups for relationship fields other than in Subpanels. 

Due to the ambiguity of which relationship info field should be queried, this should not be resolved by SugarBean::create_new_list_query(), but should be defined beforehand by supplying the required field, as described in this comment: https://github.com/salesagility/SuiteCRM/issues/1241#issuecomment-210798022

I suggest to therefore fix this by having Studio adding the required relationship_info field when a relationship field is inserted into a listview / subpanel, for which I will create a PR at a later moment.
