### ISSUE TITLE
Unable to send email campaign SuiteCRM7.6RC & SuiteCRM7.6.1

### ISSUE THREAD

**Issue by chandan999** [salesagility/SuiteCRM#1289]
Hi All,
       I am not able to send email campaign in Suitcrm 7.6 RC.Even test campaign emails are not going.Its getting stuck in queue.But same thing is working fine suiteCRM 7.5.3.

**Comment by samus-aran** [comment]
Hi @chandan999 - does the logs say anything with regards to the queue?

**Comment by chandan999** [comment]
After recent changes in code in suiteCRM 7.6.1

if (!$test && $lock_count!= 1) { 
			$GLOBALS['log']->fatal("Error acquiring lock for the emailman entry, skipping email delivery. lock status=$lock_count " . print_r($row,true));
			continue;  //do not process this row we will examine it after 24 hrs. the email address based dupe check is in place too.
		}

But still i am facing issue of sending emails manually from email queue.It is getting stuck "in process" state.Log says "Error acquiring lock for the emailman entry, skipping email delivery"

**Comment by chandan999** [comment]
appendErrorMessage($error_message).This function is not working in suitecrm 7.6.1

**Comment by samus-aran** [comment]
Thanks for the response @chandan999 We have assigned this accordingly.

**Comment by dodexahedron** [comment]
Processing of the emailman table always fails when using mysqli, if the storage engine for the emailman table is innodb and autocommit is on (which it is, by default).

This is because the mysqli_affected_rows function returns only the number of rows affected by the LAST query, even if that query was implicit. If the table is innodb and autocommit is on, the last query was COMMIT, which affects 0 rows, leading to ALL outbound email processing failing.

Potential fixes:
Force storage engine of emailman table to something other than InnoDB (I hate this idea).
Make MysqliManager.php turn autocommit off on its connections and get the count before committing (seems reasonable).

**Comment by dodexahedron** [comment]
Why is this "lock" checking code there, in the first place?  I think that's the more important question to be asking, here.

My proposed solution at least "fixes" it and the solution proposed by @gymad also looks like it would work around it, too, but both are hacks and the original "lock" code looks like a hack to get around something specific that may have been happening in the past, anyway.

If it's there to make sure that a SQL command actually did happen, then WOW we really aren't trusting MySQL, are we?
If it's there because MyISAM was not ACID, then...well...using InnoDB is the solution, there.
Either way, I honestly think the code just needs to go away.  Then, none of these hacky workarounds will be necessary in the first place.

Really, though. Can someone explain why this code is even there in the first place?

**Comment by dodexahedron** [comment]
Just to comment here...
Someone else has independently tested the solution I posted and it worked for them, as well:
https://suitecrm.com/forum/installation-upgrade-help/9185-email-campaigns-no-longer-send-after-upgrade-from-7-5-3-to-7-6-1#31721

But I'd still like to know why the original code was there, in the first place, so we can either improve it or remove it.

**Comment by chandan999** [comment]
Issues solved.

public function checkConnection()
	{
		$this->last_error = '';
		if (!isset($this->database))
		{
			$this->connect();
		}
		/*
		else{
            try {
                $this->database->ping();
            }catch(Exception $ex){
                unset($this->database);
                $this->connect();
            }
        }
		*/
	}

This function is present in /include/database/DBManager.php.If we comment the above lines of code in this function.Then everything is working fine.
