### ISSUE TITLE
Using "E-Mail" from the action menu does not include variables from the templates

### ISSUE THREAD

**Issue by cjmny** [salesagility/SuiteCRM#1366]
After implementing the fix from pull request #1168, the emails themselves will send, but the don't pull the variables mentioned in the email templates  (e.g. Instead of "John", the email is addressed to "prospect_first_name").

**Comment by sathishsengodan** [comment]
Hi @cjmny 

I am unable to replicate this issue.I have created a test template with account variables and sent out email from the accounts module using that template. I have received the all the values for the variables in the template to my email.

Please can you explain this in bit more detail so I can look into this further. 

Thanks

**Comment by cjmny** [comment]
Thanks for the update @sathishsengodan .  I experienced this issue with an email template built for the Prospects module.  I am basically just trying to address the emails by name, but when I do the email gets delivered with "Hello $prospect_first_name,".  When the same email is sent through a Workflow, it has the variable data.

**Comment by cjmny** [comment]
Update to this.  If you generate the email and specify the related module record, it does work.  This does present an issue though.  You can multi select in the list view to email multiple accounts/prospects, and while SuiteCRM will warn you that unintended results could occur, if you are pulling required fields from the record in the email they should populate.

**Comment by Tectract** [comment]
Still not interpolating email variables for me. What is the fix?

**Comment by samus-aran** [comment]
The fix proposed will need to be tested thoroughly as a replacement for the the current parse_template function.  Something we will need to schedule in and perhaps encourage the community to test.

**Comment by EZS-JD** [comment]
I'm willing to help test.

**Comment by benjaromero** [comment]
Any update in this issue?

I am experiencing a similar problem. I have built two custom modules, one basic  and the other one contacts.

I add variables from both to the email template but the email sent just shows right variables of the contact module. The variables from the basic module doesn't show the variable values. Any idea why?

I really appreciate any help.

Ben

**Comment by boombata** [comment]
i guess same issue in 7.7.9, email sent from cases including case fields are just containing $acase_* variables but not the data. 
as side effect "new case email" set into the inbound email is not including data.
note that the "new case email" set in AOP is working fine.

**Comment by PedroErnst** [comment]
I've just fixed #4636 which is a somewhat related issue. Template variables in the related module should now replace correctly in 7.8.x (it was already fixed in 7.9.x).

So this issue now is only the bulk action email.

When selecting multiple Leads/Contacts/etc and using the bulk action Email, if you choose a template:

SuiteCRM 7.8.x LTS will warn you explicitly that this is not supposed to work. You're supposed to use Email Campaigns for such functionality. No bug.

![image](https://user-images.githubusercontent.com/34056696/34986333-21172b2c-faaf-11e7-91cb-8da612e89056.png)

In 7.9.x, with the reworked Email module this warning no longer appears.

So my question is what is the intended functionality here?

- The warning is simply missing, and the way to go for this kind of personalized email is still Email Campaigns.

Or is bulk action emails supposed to replace the contact details for each of the addressees selected in the bulk action? So instead of sending a single email with X addresses in TO the CRM would split it into individual emails. Some other functionality would be lost here (for example reply to all for anyone receiving such an email).

So I think maybe only the warning is missing here.

@mattlorimer @daniel-samson

**Comment by Mausino** [comment]
@samus-aran shoud it be in milestone 7.10.12  ? because it's Fix Proposed and Hight Priority issue. I want only that we wont forget on this ticket if has tested solotion.

**Comment by samus-aran** [comment]
I agree in this particular case that we could add the current 7.10.12 because there appears tobe fixes for this throughout the application regarding parsing.

https://github.com/salesagility/SuiteCRM/issues?q=is%3Aopen+is%3Aissue+milestone%3A7.10.12

**Comment by samus-aran** [comment]
Ideally https://github.com/salesagility/SuiteCRM/pull/6466 Should be the new fixed proposed.
