### ISSUE TITLE
Word wrap on $aop_case_updates_description in email template

### ISSUE THREAD

**Issue by kyriakoy** [salesagility/SuiteCRM#1449]
Variable $aop_case_updates_description is not being parsed correctly at email templates. Only the first word of the description is printed

Reproduce problem:
Create workflow for case updates to send email using template and use the variable $aop_case_updates_description 

Version SuiteCRM 7.x
Ubuntu 14.04/ php 5.5.9/ mysql 5.5.49

**Comment by kyriakoy** [comment]
Thank you for the update
I confirm that is working

**Comment by aproposnix** [comment]
As of 7.7.8, this is still an issue.  Do we have an ETA for this fix?

**Comment by tealsteam** [comment]
This issue is still present at 7.8.2, proposed fix does not work, when applied it, the email shows the mailmerge references i.e. $aop_case_updates_description in the email,

There are a number of people suffering this issue as you can see here,
https://suitecrm.com/forum/advanced-opensales-workflow-portal-support/15619-email-on-case-update#5530
and here
https://suitecrm.com/community/forum/suitecrm-7-0-discussion/2768-word-wrap-on-aop-case-updates-description-in-email-template

**Comment by mattds91** [comment]
The proposed fixed templateParser.php worked for me - Thank you

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
