### ISSUE TITLE
Chart dashlets not respecting dashlet/dashboard widths

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#1529]
Chart dashlets do not respect column settings for dashboards. They also do not respect normal dashlet/page width settings. If you add 2 chart dashlets side by side, they overflow and the page then requires horizontal scrolling.

**Comment by acoolov** [comment]
The report charts are huge. They don't fit the dashlet on the dashboard. When is it going to be fixed?

**Comment by gunnicom** [comment]
For me i patch my Suite after every update with the following:

--- a/modules/AOR_Charts/AOR_Chart.php
+++ b/modules/AOR_Charts/AOR_Chart.php
@@ -257,9 +257,9 @@ class AOR_Chart extends Basic {
         }
         $xName = str_replace(' ','_',$x->label) . $this->x_field;
         $yName = str_replace(' ','_',$y->label) . $this->y_field;
-
-        $defaultHeight = 500;
-        $defaultWidth = 900;
+        // GUNNIFIX
+        $defaultHeight = 400;
+        $defaultWidth = "";

         switch($this->type){
             /*

**Comment by Dillon-Brown** [comment]
@gunnicom What issue does that fix? chart dashlets width/height looks correct to me with #4874.

**Comment by gunnicom** [comment]
I dont know since when i do this patch, and if i had in in a pull request at some time.
But for me, charts were to wide ( Or still are without my patch, though i did not try the patch from #4874 )
Maybe the patch #4874 will fix the issue for me, too. But maybe it can be helpful if the other patch does not fix in any case. If the patch fixes it, it is only a documentation of another way to fix it.
