### ISSUE TITLE
Mass update - Case state/status values

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1549]
Hi,

When you mass update the cases, and you will change the state value from open to close, you will still see them (the cases) as open, because, there was not changed the status value... same issue with status value, if you change the status value via mass upadte, the state value still shows as open.

Same issue you get if you using the inline edit :) 

![case](https://cloud.githubusercontent.com/assets/5773777/15773406/0556932e-2977-11e6-8bff-56961e59ef1c.png)

**Comment by dtfuller** [comment]
Hi everyone! 

I just traced this PR to be the cause of an error when my users do a Mass update over the Leads or Accounts module. In my instance, those modules have been customized to contain nested dynamicenums, so when the update is performed, the value of the child dynamicenum is defaulted. This **should not** be the expected result.

In case anyone runs into this, as a temporal fix (and since my organization does actively use the Cases module) I've commented out this whole section and moved on to working on fixing the changed data.
