### ISSUE TITLE
Rem word as a Remove abbreviation? [Language]

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#1716]
#### Issue

String `'LBL_REMOVE' => 'rem',` causes some trouble to translators as its not a proper word or even an abbreviation. You find it here: 
modules/Calls/language/en_us.lang.php
modules/Meetings/language/en_us.lang.php
modules/Project/language/en_us.lang.php
modules/Configurator/language/en_us.lang.php
modules/Campaigns/language/en_us.lang.php
See: https://github.com/salesagility/SuiteCRM/search?utf8=%E2%9C%93&q=%27LBL_REMOVE%27+%3D%3E+%27rem%27&type=

#### Possible Fix
Why not a full word? At least it should be used an ending dot to show an abbreviation
`'LBL_REMOVE' => 'Remove',`

#### Context
"rem" is not a word and causes doubts to translators

#### Your Environment

- SuiteCRM Version used: Hotfix

**Comment by horus68** [comment]
Fixed by https://github.com/salesagility/SuiteCRM/pull/2358

**Comment by horus68** [comment]
@Dillon-Brown back on this. Is it safe to use a full word for this string?

**Comment by pgorod** [comment]
I think we would first need to find where this appears on screen, since I think it must have been abbreviated for a reason - normally this would be a matter of layout (screen space), for example to make it fit in a column header or in a button in a table row.
After we know where it appears, we could make a more informed decision about removing it.

If not, the label name could be changed to LBL_REMOVE_3LETTERS_MAX or something, to make it clearer for translators.

**Comment by pgorod** [comment]
I spent some time looking for these labels in the app, but I can't find them. There is a lot of re-definition of LBL_REMOVE labels all over the place, it's hard to know which one are actually used, which aren't.

I'm guessing these could be in the subpanels, at the end of the row, where we have "edit" and "remove" but it should be short. But I didn't find any of those menus with just "Rem", they all say "Remove".

So I don't know what to do with this. We could try removing but it involves some risk.
