### ISSUE TITLE
Scheduled Reports doesn't take User Timezone into consideration

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#1744]
#### Issue

The Scheduled Reports functionality seems like it doesn't take the User's Timezone into consideration for Displaying.
#### Expected Behavior

I would expect the Functionality to take the user's timezone into consideration in ways that the other Datetime functionality does. (I.e, Calls/Meetings/Reminders etc...)
#### Actual Behavior

Looks like it doesn't re-calculate the values to display in the User's Timezone.
#### Steps to Reproduce

1.  I set the time in the following screenshot at 15:50 UTC time. (User was on UTC timezone)
2.  I then changed my user's timezone to Hong Kong (UTC+8), Yet, it still displays as 15:50 UTC

![screenshot from 2016-07-13 15 55 26](https://cloud.githubusercontent.com/assets/13675281/16808020/a6e252e0-4912-11e6-8829-a08686edc247.png)

Another way to experience issues is: 
1.   Have a user in a Timezone that's not the Database's  (e.g, Hong Kong, which is UTC+8)
2.   Edit Scheduled report and set a time. (e.g, 15:50)
3.   Rather than store in DB as a value converted from the User's Timezone into UTC, as other Datetime fields do, it simply stores as UTC, which might cause confusion with users that aren't using UTC timezone.
#### Context

Was trying to run a scheduled report.  This doesn't cause issue with functionality, simply causes confusion if user it on a Timezone other than the DB's

This is likely fairly low priority I believe, as this doesn't affect functionality.
#### Your Environment

- SuiteCRM Version used: 7.6.4
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 47
- Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.5.9
- Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by pgorod** [comment]
I'm not sure this is really a bug, this sort of thing frequently happens when people don't configure the timezone for the PHP CLI. Then the things that are dependent on cron jobs get different timezones.

I know this is pretty old, but maybe @johnM2401 can verify whether his timezone settings for CLI (command line PHP) are correct? If you go into Admin/Schedulers, click on one of the jobs that runs very frequently, and see if its "last run time" makes sense according to your timezone.

**Comment by isleshocky77** [comment]
@pgorod Could you expand a little on your answer. 

In my experience, most people set their server (php cli and web) for UTC timezones, and then update the application to a specific timezone. 

In my use-case, we do that exactly. The server (both cli and web) are set for UTC; however, the users in the system are all America/New_York. I thought there was a global config for default timezone in config.php - but I'm now not seeing that.

I think it would be nice for SuiteCRM to have a timezone set separate of php and the underlying system as most users would expect this. Also, I would think that the Scheduled Reports might want a setting for sending the report based on the actual end user's timezone if sending to a user.

**Comment by pgorod** [comment]
I see many people on the forums who don't understand the difference between CLI and Web, and don't know about the need to configure two php.ini's. That's why I asked here.

SuiteCRM already handles the "user's" timezone, separate form PHP timezone. That is in the user's profile.

I agree that any time shown to the user inside the app, that is not in agreement with this profile setting, is a bug. I just wanted to rule out the possibility that it was influenced by a php.ini configuration error. This error can cause the scheduler to _run_ at the wrong times, not just to _display_ a wrong time to the user.

Sometimes we find places in SuiteCRM that don't bother to translate times to user time, that much is true. For this case, it should be simple to investigate.

**Comment by samus-aran** [comment]
Superseeded by #7305
