### ISSUE TITLE
A wird behavior of Advance search in Listview 

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1774]
#### Issue

You can see more here: http://screencast.com/t/RK9ZboKZpn9 
Problem with hide and unHide the Advance Search menu

#### Expected Behavior

If i hide advance search i am expceting then when i will sort any column, it will stay hidden

#### Actual Behavior

It is still unhidden when i am sorting, i must push search button on Basic Search and after it will stay hidden.

#### Steps to Reproduce

1. Any Listview
2. Search with advance search
3. Hide advance search
4. Sort any column

#### Context

Low priority

#### Your Environment

* SuiteCRM Version used:
* Browser name and version: Verzia 52.0.2743.75 beta-m (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6, PHP 5.6
* Operating System and version: Debian (hosting)

**Comment by Mausino** [comment]
+ in SuiteCRM 7.7 RC2 it shows in one column

![rc2](https://cloud.githubusercontent.com/assets/5773777/17173899/e074515c-53fd-11e6-9c6b-3be824969e79.png)

**Comment by willrennie** [comment]
This is a usability issue rather than a bug. If you are clicking 'Basic Search' without performing or clearing your advanced search, when you order your 'Advanced Search' results it is going to show the Advanced Search pane open, so that you can view/edit the search criteria you entered. This works in the same manner in older versions of SuiteCRM so isn't a theme bug. In regards to all of those fields being listed in one column, that has also been addressed in the production release.

**Comment by ijdavie** [comment]
The issue with all the fields appearing in the one list has been addressed in the latest release. @will is correct this appears to be usability rather than a bug. No search has been run at this stage which is why it will revert to the previous search.

**Comment by Mausino** [comment]
@ijdavie  thank you for answer. I will respect your decision.
