### ISSUE TITLE
7.7RC2 Case Updates not displayed

### ISSUE THREAD

**Issue by 2xaronl** [salesagility/SuiteCRM#1826]
In 7.7RC2 I'm getting 
`Notice: Undefined property: aCase::$internal in /var/www/suitecrm/modules/AOP_Case_Updates/Case_Updates.php on line 302` and when trying to view the details page of a case with updates previously posted the update text is not displayed with the rest of the record.  The update text is inserted as a record in the aop_case_updates table.

#### Issue
This issue was also present in 7.7RC which was my initial install.

#### Expected Behavior
Update text should display when available.

#### Actual Behavior
Update text is not displayed.  Error is produced.

#### Possible Fix
It seems that the case object that's being passed to the display_updates function doesn't have an 'internal' parameter...

#### Steps to Reproduce
1. Create a case
2. Edit the case by adding Update Text
3. Save the edits
4. Update text is not displayed

#### Context
This bug makes cases much less usable.  Fixing this should be a high priority.

#### Your Environment
* SuiteCRM Version used: 7.7RC, 7.7RC2
* Browser name and version: Firefox 47.0.1, Chrome 51.0.2704.103 m
* Environment name and version: MySQL 5.6, PHP 5.5.9
* Operating System and version: Ubuntu 14.04.4 LTS

**Comment by 2xaronl** [comment]
Will this fix be applied to the SuiteR theme as well?  I forgot to mention that I was using the SuiteR theme when this occurred.

**Comment by emcrobert** [comment]
7.7RC and 7.7RC2 were beta versions of 7.7, both to give people a chance to see what functionality was coming up in the next release and for testing purposes. They weren't intended for production use and don't serve any purpose now 7.7 is actually out. 

So when I saw your issue I tested it in 7.7 and found there was an issue with the SuiteR theme and cases, which this fix should resolve. Personally I didn't have issues with cases using the other themes & my fix is in a template that is unique to Suite R and wouldn't be relevant for the other themes.

Now I look back at your message I notice the error you have is a PHP notice. I wouldn't recommend editing your php.ini file so it doesn't report warnings or notices. I'd also recommend that if it's a production instance (and not just for testing) you should use 7.7 rather than one of the release candidates.

If you still have issues after taking this advice please let me know and I'll try to look into it.

**Comment by bojkic** [comment]
does this fix this also https://github.com/salesagility/SuiteCRM/issues/444#issuecomment-237827117
