### ISSUE TITLE
Knowledge base - "No suggestions"

### ISSUE THREAD

**Issue by bojkic** [salesagility/SuiteCRM#1876]
#### Issue
Suite 7.7 fresh installation. When entering Case subject, even though there is Knowledge base article with identical name, no suggestions are given

#### Your Environment

* SuiteCRM Version used: 7.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Crhome, Win10
* Environment name and version (e.g. MySQL, PHP 7): Ubuntu php7 mysql
* Operating System and version (e.g Ubuntu 16.04): 16.04

**Comment by bojkic** [comment]
Here is log excerpt:

"Thu Aug  4 18:24:14 2016 [3590][1][FATAL]  Query Failed: SELECT id, name, description, status, sum(relevance)
                  FROM (
                        SELECT id, name, description, status, 10 AS relevance
                        FROM aok_knowledgebase
                        WHERE name = 'proba'
                        AND deleted = '0'
                        UNION SELECT id, name, description, status, 5 AS relevance
                        FROM aok_knowledgebase
                        WHERE name LIKE '%proba%'
                        AND deleted = '0'
                        UNION SELECT id, name, description, status, 2 AS relevance
                        FROM aok_knowledgebase
                        WHERE description LIKE '%proba%'
                        AND deleted = '0'
                        )results
                    GROUP BY id
                    ORDER BY sum( relevance ) DESC
         LIMIT 0,30: MySQL error 1055: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'results.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by "

**Comment by shogunpol** [comment]
The issue has been checked on SuiteCRM 7.7.1, and PHP 5.5.9, and do not appear. 
The issue has been checked on SuiteCRM 7.7.1, and PHP 7, **and it appear**. 
1st - The version of PHP (suggest use more stabil, older version);
2nd - Also if "Knowledge base" is not created "suggestion" does not apear (because is nothing to suggest).

**Comment by bojkic** [comment]
Yes, I am using php7.

**Comment by mminnie** [comment]
I don't know if this qualifies as a "bug".  It is introduced because as of MySQL 5.7.5, the ONLY_FULL_GROUP_BY was added as a default value to the sql_mode MySQL system variable.

[See here]
(http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html)

Disabling this setting in MySQL either through the configuration or through code resolves the issue.

This being said, moving forward the code causing the issue should be fixed as it will probably remain to be a default setting in MySQL.

**Comment by ijdavie** [comment]
@mminnie, I would agree, however disabling this in MySQL I dont see is a permanent work around. In the long term the software will need to handle this.
