### ISSUE TITLE
Title case shouldn't be used - SuiteP

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#1911]
#### Issue

Using template SuiteP there are places where title case is active changing all the translated words to capital on each ord first letter.
This makes translation look bad on language that do not allow title case or to capitalize certain words (prepositions and such)

#### Expected Behavior

Title case and sentence case should not happen automatically. There could be a setting to turn on (for those who want) but it needs to be able to have a turn off so capitalization follow the work of the translator.

#### Steps to Reproduce

See Reports / Action menu
the title case is active changing the translated words. 
This is the language source:
![10](https://cloud.githubusercontent.com/assets/3055443/17553219/94f2301e-5efc-11e6-9026-b10fdf17edbd.png)

#### Context

This makes translation look non professional for some languages that do not allow Title Case, Just Sentence case.

**Comment by horus68** [comment]
its possible to fix on css (suiteP theme)
\themes\SuiteP\css\style.css
near line 3467
`li#tab-actions > ul.dropdown-menu .open > .dropdown-toggle.btn-primary {
    background-color: #F08377;
    text-transform: capitalize !important;`

remove or change the line for text transform to
`    text-transform: none !important;`

**Comment by daniel-samson** [comment]
If you access the main navigation, create button, or the create/edit drop downs in the subpanels. They are all capitalized in the Suite7, SuiteR, SuiteP themes.

@horus68 What is your opinion on the other drop down elements that are capitalized? Should we change just the action menu or all the elements that are capitalized?

I think what we need is to make a change so that you can apply a CSS file for each translation after the style.css file has been applied. Since en_us is the default language I could add a en_us.css file for the default.

@horus68 What language is your translation in?

**Comment by horus68** [comment]
Not all menu are capitalized: The ALL menu is not.

My language is pt_PT (and has several restrictions on the usage of a capital letter besides the initial letter of a sentence and people names or places).

Capitalization should be a thing for language. Yes there can be a setting for those who prefer capitalize words. 
Title case (initial capitalized) is very common on some modern UI because they are created with english in mind. It can look cool but its an error on several languages.
When translating capitalized words sometimes are not so friendly as in English too.
Examples of bad looking on any language are articles and prepositions as in:
"Criar Um Contacto" ... some will be ok with "Criar um Contacto" but it should be "Criar um contacto"

I see a PR from you now so I will close this issue.
https://github.com/salesagility/SuiteCRM/pull/1920
