### ISSUE TITLE
Drop Down Editor is not functioning

### ISSUE THREAD

**Issue by ioriyong** [salesagility/SuiteCRM#1945]
Hi,

SuiteCRM 7.7 is not having issue by creating a dropdown using DropDown Editor. However, after the upgrade, the DropDown editor is having an issue creating a drop down parameter.

Regards,
Joh

**Comment by shogunpol** [comment]
The issue is tested and really exist, It was tested in themes: Suite R, Suite 7 and Suite P.
The issue exist only in: Suite P theme, when you create new drop down in 'DropDown Editor', when you start adding the items of drop down, you typed item name and display label and click 'add' button to create next element of the drop down list it doesn't work.
Issue been tested in version 7.7.1.
