### ISSUE TITLE
Workflow any change fails on audited fields

### ISSUE THREAD

**Issue by mattlorimer** [salesagility/SuiteCRM#195]
if you run an a workflow with 'Any Change', if will not fire if the field is audited

**Comment by adriangibanelbtactic** [comment]
Hopefully this helps someone else to solve the problem.

I have been tracking the problem and it seems that the main $bean for the workflow it's not getting the old value in its fetched_row array but new one.

Why? Because the audit code it's probably saving the new value in the database just before handing the program to the logic hooks (where AOW_Workflow is run).

I ask myself if a new feature about being able to run the workflow before and / or after the saving of the bean (which I think I have seen in some suitecrm betas) could workaround it.

**Comment by adriangibanelbtactic** [comment]
Check: https://github.com/salesagility/SuiteCRM/blob/9cec55772ec039833ca2b1e4135b0b8e2debe719/data/SugarBean.php#L1480-L1483

These are the lines that make this workflow not to work.

As you can see above them the before_save logic hooks are called thanks to:
https://github.com/salesagility/SuiteCRM/blob/9cec55772ec039833ca2b1e4135b0b8e2debe719/data/SugarBean.php#L1426

And after them the after_save logic hooks are called thanks to:
https://github.com/salesagility/SuiteCRM/blob/9cec55772ec039833ca2b1e4135b0b8e2debe719/data/SugarBean.php#L1496

So if matches my former comment guessing.

Next I'm going to study how this auditing was handled in the past just to see if it makes sense to revert some of newest changes or not. Anyway I suspect the best way of solving this problem is improving the workflow module itself.

**Comment by jcrist1027** [comment]
I pointed this issue out months ago on the forums.  The fix as mentioned is to disable audting on the field which is a quick fix.  However I cannot figure out how to disable auditing on the Cases:Assigned To field as it isn't listed in the Case field list in Studio.  Seems like someone would have posted a have for the workflow PHP code to fix this by now?  If not, I will see if I can device a patch but I'm realtively new to Sugar.

**Comment by adriangibanelbtactic** [comment]
@jcrist1027 My current workaound is to comment these lines:

https://github.com/salesagility/SuiteCRM/blob/9cec55772ec039833ca2b1e4135b0b8e2debe719/data/SugarBean.php#L1480-L1483

It would need nice if someone who understood better the source code would confirm that there are no secondary effects to this change.

Feedback on the workaround working for you (or having undesired effects) is welcome.

**Comment by websolprov** [comment]
Did any of you find a fix for this? It would appear that if you comment out those lines then it prevents the fields that are being audited from working properly?

**Comment by mattlorimer** [comment]
this issue has yet to be resolved

**Comment by adriangibanelbtactic** [comment]
@mattlorimer I wouldn't mind taking a deeper look on the issue. But I would need some tips on where to look on the source code for unexpected secondary effects of my workaround.

Thank you.

**Comment by mattlorimer** [comment]
I think the solution is to add a way that we can detect changes in fields not using $fetched_row, the same in before save and after save logic hooks,

**Comment by adriangibanelbtactic** [comment]
@mattlorimer Something like a deep copy of the original $bean object which could be named as: old_bean and that could be accesed like this:

```
$bean->old_bean
```

I sometimes do print_r of $bean objects and I know they do circular references sometimes so that might be a problem for a deep copy. And well, php does not support deep copy of objects very well although this project: https://github.com/myclabs/DeepCopy seems interesting.

Yes, definitively there's a need of accessing the old_bean which makes sense and it's easy to implement. Maybe a custom clone function for bean objects which only deep copies what makes sense in terms of comparing the old and new bean.

**Comment by shogunpol** [comment]
The bug doesn't appear any more, after changes in bug#1648. Please close the case.
