### ISSUE TITLE
Workflow create record dates doesn't handle setting field from blank date

### ISSUE THREAD

**Issue by mattlorimer** [salesagility/SuiteCRM#196]
If you try to set a date from anther date, e.g date_created + 2 hours and the date is null, the date will be set a random date

**Comment by ricktimmis** [comment]
I believe there is a relationship between this issue, and the following Bug reported in the SuiteCRM Forum.

https://suitecrm.com/forum/bug-tracker/3706-workflow-create-record-with-date-offset-ignores-selected-date-field#15510

The fix proposed to modules/modules/AOW_Actions/actions/actionCreateRecord.php - Line 178
Does resolve the problem described there.

I suspect just a little bit more work might be required to trap a returning null date in the Bean to fix this issue fully, but this seemed like a sensible place to put this information, rather than raise a whole new issue.

**Comment by TheSmallFry** [comment]
I have just installed 7.2.3 and the bug is still there.  Fixed in the same way although this time on line 196.

**Comment by TheSmallFry** [comment]
Sorry I do not have the talent to work out how to fix this.  Can anyone help?

Thank you.

**Comment by Jason-Dang** [comment]
Can no long Replicate. If the date/datetime field to be used is blank then the date/datetime is automatically set to today/now which, in the case of date created would be correct. Otherwise the issue would be that the date/datetime field to be used has not been populated and in this case the logical thing to do would also be to use today/now. 

@ricktimmis The bug you referenced is unrelated to this issue as it doesn't relate to setting fields based on blank fields. However it is still a bug and is related to the following two issues which are duplicates. The issue in both these cases and your referenced bug is that the date/datetime field to be used is being ignored on newly created records and instead today/now is being used to set the created records date field. 

Issue #1990
https://github.com/salesagility/SuiteCRM/issues/1990

and 

Issue #533
https://github.com/salesagility/SuiteCRM/issues/533
