### ISSUE TITLE
Merge Duplicates: "Assigned-to" field not showing up in the right place

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#2047]
#### Issue

In the interface to merge two contact datasets SuiteCRM conveniently shows the differing fields first, and then all fields, with the same contencts below that. I've been noticing, that this is not done correctly for the field "assigned to". See Screenshot for an example.

![screen shot 2016-08-25 at 16 20 35](https://cloud.githubusercontent.com/assets/15463075/17972901/b8b93278-6ae0-11e6-867e-d3ab6a07f81a.jpg)
#### Expected Behavior

Fields with differing contents should be shown in the top section titled "Columns whose value in primary row differs from value in merging rows:"
#### Actual Behavior

Field "assigned to" with differing data is shown in the bottom section under the section title "Columns whose value is similar across all rows:"
#### Steps to Reproduce

1. (e.g. contacts) select two contacts from list view that belong to two different users
2. choose action "merge"
3. Look for field "Assigned to User"
   4.
#### Context

This can lead to wrong user being assigned to the merged dataset, because the active user assumes they are the same in both datasets. -> bad for data integrity
#### Your Environment

- SuiteCRM Version used: 7.4.1
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
- Environment name and version (e.g. MySQL, PHP 7):
- Operating System and version (e.g Ubuntu 16.04):

**Comment by shogunpol** [comment]
The issue was tested in current version of SuiteCRM(7.7.2) and it is appear.
It is labelled as a bug.
@EZS-JD  , thanks for raise this issue, we work on the solution.

**Comment by Mac-Rae** [comment]
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. 
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. 
If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.
For more information about 7.8.x end of life please visit our [blog post ](https://suitecrm.com/7-8-x-end-of-life/)
