### ISSUE TITLE
Dropdown editor broken

### ISSUE THREAD

**Issue by sky54000** [salesagility/SuiteCRM#2051]
#### Issue

In the Administrator Page, in the dropdown editor functionality,
The dropdown editor don't allow us to edit the dropdown, when we want to add elements to a dropdown we can't because of the "ADD" button, we can click on it, but it has no effect. We can complete the "Item Name" and the "Display label" but when we click on "ADD" , the element is not added to the dropdow, that have no effect.

 
#### Expected Behavior

When we click on "ADD" button our element supposed to be added to our dropdown

#### Actual Behavior

When we click on "ADD" button, that have literally no effect.

#### Possible Fix

Don't know how to fix this.

#### Steps to Reproduce

1.Go to the administrator interface
2.Go to the dropdown editor
3.select a dropdown
4.Complete "Item Name" and "Display Label"
5.Click on "ADD" button

#### Context

I just want to edit my list(dropdown) and it's impossible since the last upgrade

#### Your Environment

* SuiteCRM Version used: 7.7.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome last version
* Environment name and version (e.g. MySQL, PHP 7): MAMP PHP-5.6, MySQL
* Operating System and version (e.g Ubuntu 16.04): MAC OSX last version

**Comment by morrissey123** [comment]
Same problem here after upgrate. As far as i see the main sugar_grp1.js output force the error.
my console shows "SyntaxError: missing ; before statement" line 489 and stop script with "error adding script"

**Comment by samus-aran** [comment]
Hi Guys, what upgrades are these from?  There was previously an issue with adding dropdowns which had a previous fix.  Are you using a custom theme and possibly repair and rebuild and refresh your browser cache.  Let us know how you get on.

**Comment by morrissey123** [comment]
Hi there,
i use the Standard Suite P theme on the Version 7.7.2. No theme customization - Sugar Version 6.5.24 (Build 509). U r right. This problem was fixed, as far as i know, already in a previoulsy version, but now it seems to be back again. Seems to be an undefined field or variable so that the main sugar_grp1.js stop the script in Line 489. So far i didnt detect any PHP Erros. Also the Log files (Apache) looks pretty OK. No suspicios in it. U can see my screenshot in the suite CRM board: https://www.suitecrm.com/forum/installation-upgrade-help/10895-after-upgrade-to-7-7-2-studio-not-working-correctly
Repair, rebulid and refreshing caches did i already

**Comment by morrissey123** [comment]
works perfectly !! thX gymad
