### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by bcowman** [salesagility/SuiteCRM#2082]
I have SuiteCRM version 7.7.3 but cannot get Notifications to work.  Also the Desktop Notification Count never changes.

I have read all the community posts on this subject and tried all suggestions:
          I have tried IE11 and the latest versions of Chrome and Firefox.
          I have enabled Desktop Notifications for each browser.
         Cron jobs as running.
         The time zone in php.ini is correct.

My environment is IIS8, mySQL 5.626, PHP 5.6

The fact that the Desktop Notification Count never changes leads me to think this is a bug.

**Comment by samus-aran** [comment]
Hi @bcowman Are you meaning perhaps the Alerts/Reminders (for when meetings and calls are coming up)? Probably just our terminology, but I believe you mean the alert counter up at the top right of the instance?

**Comment by bcowman** [comment]
Yes, Alerts/Reminders for calls and meetings and the Alert Counter at the top right.

**Comment by KhyberPass** [comment]
Hi @bcowman, alerts are working for me with 7.7.4 - but are not very reliable as there are a few things that can break them. You need to ensure the following
- Notifications are enabled under your Profile -> Advanced. When you click on the Enable button you should get a notification
- The meeting or call has the popup checked, a time set and a person invited - like this
![image](https://cloud.githubusercontent.com/assets/5484293/18434884/42bbf752-7933-11e6-8ed4-66fcf9c8c4b5.png)

- The browser tab is active and not inactive ie. you have Suite open on the browser 

Also, you can use the following to see the alert time counting down. Paste into a Chrome console window.
console.log("Alerts:", alertList.length, "-", alertList[0].time, "Time:", secondsSinceLoad);
This assumes that you only have 1 alert pending. If the length shown is more than 1 then you may need to adjust the [0] to [1] or more.
The alert time is fixed and the secondsSinceLoad counts up in seconds. When secondsSinceLoad is greater than the alert time the notification will trigger. When a page is loaded the times are reset to new values.
Nick

**Comment by bcowman** [comment]
Hi Nick,

Thanks for taking the time to reply to my query...

I have upgraded to 7.7.4.

- Notifications are enabled
- The Call has popup checked, a time set and person invited.  If I also include the Email Invitees then I WILL receive the email.
- Browser tab is active

I have created only one alert.  If I post the code you supplied into Chrome Console I get the following error:

![image](https://cloud.githubusercontent.com/assets/6651942/18442024/14e58f90-7907-11e6-85cf-3cfbb15b766b.png)

**Comment by KhyberPass** [comment]
Hi, the error you are getting in the console is because the array alertList is empty. This means that there is no alert in the list - which is the problem.
If you do the following in the console
console.log("Alerts:", alertList.length);
it will show 0 i.e. no alerts
You can also do this a few times
console.log("Alerts:", alertList.length, "Time:", secondsSinceLoad);
This will show no alerts and the time will be counting up each second.
This shows that the timer is active but there is nothing in the list to process.

It is good news that you are receiving email reminders. This means that the reminder entry is in the table, but just not progressing to the alert system.

How are you creating the reminder? From a Meeting or a Call?
What reminder prior time are you using?
What timezone is your profile set to?
What language are you using, English?

Things that may stop the reminder progressing to an alert are
The status of the Call must be Planned.
The Call start date must be less than now and greater than 'reminder_max_time' ago. 'reminder_max_time' is 90000s defined in include/language/en_us.lang.php
The user must not have declined the call.

I will think about what else you can try.
Nick

**Comment by KhyberPass** [comment]
Hi,
Was doing some searching and found [this](https://suitecrm.com/forum/feedback/8309-suitecrm-notifications-alerts-not-working-on-out-of-the-box-installation).
I noted that they said that alerts did not work when the date format was set to dd/mm/yyyy
My date format is yyyy-mm-dd, when I changed it to dd/mm/yyyy alerts stopped working.
What is your date format set to?

I will check out the source and find what the problem is.
Nick

**Comment by bcowman** [comment]
Hi Nick,

Yes my date format is set to dd/mm/yyyy.  I changed the date format to yyyy-mm-dd and notifications worked.

**Comment by jack7anderson7** [comment]
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.
