### ISSUE TITLE
API query failure - rollback or error report

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#213]
The SuiteCRM API(s) should have a feature whereby it either errors out if a query fails, or provides a 'roll back' feature. An issue has been identified where if a query fails on a custom table, the record will still be created but without the related custom field data. If any part of the query/queries fail, the API call should either error out or provide a rollback option to delete any partially created records.

**Comment by chris001** [comment]
Agreed.  
This should be made a general part of the persistence layer, so that it would protect all Create Read Update Delete ("CRUD") queries to data.  

In database lingo this is known as "Transactions".  

First, if on MySQL, you have to convert the database tables to InnoDB tables - because the default MyISAM tables don't support Transactions.

Then at the persistence layer you need to turn off PHP auto-commit on the database connection, and commit only when all the data has been successfully written - at the "meaningful end" of the PHP business logic code that was writing out that data..  if that commit fails then you must rollback before PHP can die().

Then, obviously, either automatically retry (if it's a fast query) a few times, and/or notify the user their query failed and give them an opportunity to manually retry their save/delete/search/whatever they were trying to do...

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [API query failure - rollback or error report](https://trello.com/c/MlsbDQch/156-api-query-failure-rollback-or-error-report)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by chris001** [comment]
Guys, this issue isn't a suggestion.  It's a defect.  It causes there to be missing data in the database.

**Comment by samus-aran** [comment]
I'll revert this and set it to Medium Priority.

**Comment by Dillon-Brown** [comment]
Now moved to a RESTful API V8 that will provide singular calls and provides errors/failures.
