### ISSUE TITLE
Show/Hide Security Groups Management doesn't work in View Users

### ISSUE THREAD

**Issue by animaleyeah** [salesagility/SuiteCRM#2137]
SuiteCRM 7.7.3

Show/Hide Security Groups Management doesn't work in Viewing specific user, caused by duplicated display of security group subpanel in Access Tab.

\modules\ACLRoles\DetailUserRole.php

line 88

Better remove the subpanel->display section

**Comment by shogunpol** [comment]
The issue has been tested on recent version of SuiteCRM(7.7.4), and it appear.
We labeled it as a bug.
@animaleyeah , thanks for raise this issue.

**Comment by boombata** [comment]
We do need the panel that cannot be seen because it is the only one having the options to edit the group and select "primary group" "not inheritable" based per user. the new panel with the same name does not have the edit. 
as a note, the panel is not visible only on non admin user pages.
as a temporary work around, 
1- from admin account 
2- set the user "userA"  as an admin
3-  Security Groups Management panel becomes available for this user
4- edit  Security Groups Management for this user
5- remove admin rights to the user.

**Comment by pgorod** [comment]
@Dillon-Brown I don't quite understand how to reproduce this and test if it is fixed, but since the proposed fix was already merged and this is quite old, I would say... close.
