### ISSUE TITLE
Feature Request - "tel:" encoding for click-to-call on mobile

### ISSUE THREAD

**Issue by sieberta** [salesagility/SuiteCRM#2187]
#### Suggestion

It would be nice if you could click a number to call it.
#### Expected Behavior

Phone numbers should be formatted as "tel:" links.
#### Actual Behavior

They aren't.
#### Possible Fix

[https://suitecrm.com/forum/developer-help/6536-skypeout-callto-tel-code-location](https://suitecrm.com/forum/developer-help/6536-skypeout-callto-tel-code-location)
#### Context

It doesn't effect me at all, because I've already deployed this personally.

**Comment by pgorod** [comment]
This is not really a suggestion for improvement, but rather a bug, since `callto:` has been discarded by the [RFC 3966](https://tools.ietf.org/html/rfc3966) (from 2004) explaining that 

> URI schemes locate a resource and do not specify an action to be taken

So a change to `tel:` seems to have only positive consequences. The most significant being that your cell phone can call them when you click, something quite relevant in 2017.

Skypeout can always pick up those links also, if you tell your computer to register that application as responsible for handling `tel:` URIs.

This would be a nice time to drop the `Skypeout` name from the `Admin-->System Settings` screen. It is just one of the many programs that can handle phone calls. I suggest to change that setting into something more generic like `Allow clicks on phone numbers to start calls`.
