### ISSUE TITLE
Cannot sort Hits on Campaigns

### ISSUE THREAD

**Issue by stenfalp** [salesagility/SuiteCRM#2199]
#### Issue

Clicking on "Hits" in the detail view of a campaign collapses the box that should be sorted.

#### Steps to Reproduce

1. Go to a compaign detail view.
2. Click on "Hits" column on the "Viewed Message" box.

#### Your Environment

* SuiteCRM Version used: 7.7.4
* Browser name and version: All browsers.

**Comment by stenfalp** [comment]
Also the number of row items reported is incorrect: it is doubled.

Regards,
Stenio

**Comment by roy2098** [comment]
I believe this is also related to navigating thru the campaign status "dashlets" - there is no working navigation. I've reported this elsewhere...

**Comment by roy2098** [comment]
Thank you thank you thank you!!!!!

:-)

I tested dashboard dashlet paginations, they worked (I need to hold 
mouse over the arrows for a second or two but they respond after that)

I cannot test the campaign status until i run a new campaign in the next 
several days because I've removed old campaigns.

Thanks again for all your work!

-Roy

**Comment by stenfalp** [comment]
Thanks from me too!!!
 :-) :-)
