### ISSUE TITLE
My-activity-stream-options-generates-error

### ISSUE THREAD

**Issue by vmijalkovic** [salesagility/SuiteCRM#2225]
I cannot access the my activity streams options.
It gives a small 1 line box on the screen.

 PHP Warning: Smarty error: unable to read resource: "custom/modules/SugarFeed/Dashlets/SugarFeedDashlet/Options.tpl" in /www/html/suitecrm/include/Smarty/Smarty.class.php on line 1094

There is a small workaround that was proposed on the forum:
https://www.suitecrm.com/forum/suitecrm-7-0-discussion/8570-my-activity-stream-options-generates-error#38042

My version is 7.7.4 (but it was reported also for the previous versions) on IIS/MySql

**Comment by pgorod** [comment]
I've also had this problem for months now. I'm using Linux and Apache.

**Comment by mikebeck** [comment]
this is a fix I proposed but never got merged https://github.com/salesagility/SuiteCRM/pull/1761, and this is a better fix because even in a fresh SugarCRM install it's like that, I don't know when and way SuiteCRM changed that line of code, it doesn't make sense to call to a custom folder that doesn't exists because you don't have nothing created yet.

best regards
