### ISSUE TITLE
AOP: In Settings is "Round Robin" selected Inactive/Terminated users are selected

### ISSUE THREAD

**Issue by mattlorimer** [salesagility/SuiteCRM#227]
If one selects in settings for AOP "Round Robin" Inactive/Terminated users are assigned the case.

Expected:
If "Round Robin" is selected ONLY active users are assigned cases.

**Comment by shogunpol** [comment]
In Expected: description of bug is ambiguity: the "active users" - drop down facility are apear in two places in User module (User profile and User information). The replication of the bug was negative, means the bug do not appear. Testing was done on 6 accounts with various: Status, User Type and Employee Status. The test has been done 4 times, than after Status, User Type and Employee Status was changed in mentioned 6 accounts. Result:
In every case, user assignment happen only for users with 'status AND employee status' - both in active,
Testing has been done on: SuiteCRM version 7.6.6.

Suggestions: Close Bug case.

**Comment by ijdavie** [comment]
issue found. more information found in #2032, Closed this issue as duplicate and left 2032 open as it contains more information.
