### ISSUE TITLE
Size of the Created Spots

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#2278]
#### Issue

During spots creation, the charts are not fitting to the working area as seen below.

![2016-09-22 11_55_17-spots-creation](https://cloud.githubusercontent.com/assets/20369981/18742304/1b3653cc-80bc-11e6-8c97-84dbda341ff3.png)

The spot was created in demo system. 
#### Expected Behavior

The created chart should fit to the working area.

**Comment by Mac-Rae** [comment]
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. 
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. 
If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.
For more information about 7.8.x end of life please visit our [blog post ](https://suitecrm.com/7-8-x-end-of-life/)
