### ISSUE TITLE
 Security Groups selection not used on record creation

### ISSUE THREAD

**Issue by boombata** [salesagility/SuiteCRM#2309]
#### Issue

-in security group management have set
 "Use Creator Group Select " = yes
inherit from creator = yes
inherit from assigned user =no

-have user1 in group A and Group B
- create a new account, and make sure to select group B only  in the selection box then hit save
- account is associated to group A and group B instead of only group A

it looks like working when i select the first group (group A) , only group A is listed after creation
#### Your Environment

- SuiteCRM Version used: 7.7.4
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
  firefox 48.0 
- Environment name and version (e.g. MySQL, PHP 7):
  PHP 5.6.26 
- Operating System and version (e.g Ubuntu 16.04):
  ubuntu 14.04

**Comment by shogunpol** [comment]
@boombata , you right, something isn't right here, i marked it as a bug.

**Comment by ijdavie** [comment]
@eggsurplus, are you able to comment on this ? and is this something you are aware of ?
Thanks.

**Comment by eggsurplus** [comment]
This is by design. It skips the Inherit from Creator if the group select is being used for a given user. In practice, the expectation was that if I'm creating the record and explicitly selecting groups then I don't want my groups associated to the new record automatically. 

The exception is with the parent/assigned auto inheritance. Those still get inherited automatically to ensure that if someone is creating the record who has with lesser rights/memberships than the parent/assigned records then that wouldn't cause those groups to be dropped going downstream.

Said another way:

Parent Record 1 has Group A, B, C (so that all appropriate users have access to it).
User 1 is a member of Group D and E only, but has the capability to create a record under Parent Record 1
User 1 creates a Meeting under Parent Record 1
User 1 only sees Group D and E in the group select
User 1 selects Group E
Expectation #1 is that Group D does not get associated
Expectation #2 is that Group A, B, and C still get associated to the Meeting as well so that everyone associated with Parent Record 1 can see it

Hope this helps!
