### ISSUE TITLE
Campaign view status page "Filter Chart By"  issue

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#2339]
#### Issue
When i want to see campaign status, Filter Chart By field show me {$app_strings["LBL_CAMPAIGN_NONE"]}

#### Steps to Reproduce

1. Open campaign page
2. View status
3. On the page, there is "Filter Chart By:" field.
4. In drop down, there is a code which is "{$app_strings["LBL_CAMPAIGN_NONE"]}"

#### Context

Low

#### Your Environment

* SuiteCRM Version used: 7.7.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 49.0.1
* Environment name and version (e.g. MySQL, PHP 7): MySQL 10.0.27
* Operating System and version (e.g Ubuntu 16.04): Ubuntu Linux 16.04
* Theme: Suite 7

![issue](https://cloud.githubusercontent.com/assets/22373035/18951127/084daab8-864c-11e6-82ea-6f536ae63605.png)

**Comment by amariussi** [comment]
To fix this:
edit file: modules/Campaigns/TrackDetailView.php and go to line 167 and invert single quotes with double quotes so that the variable is evaluated.

Original code:
`$options_str .= '<option value="all">{$app_strings["LBL_CAMPAIGN_NONE"]}</option>';`

Working code:
`$options_str .= "<option value='all'>{$app_strings['LBL_CAMPAIGN_NONE']}</option>";`

Here is a prposed solution:
https://suitecrm.com/forum/suite-themes/11433-bug-in-campaigns-detail-view-v-7-7-5

**Comment by amariussi** [comment]
Sorry, I just noticed the proposed solution by shogunpol
