### ISSUE TITLE
SuiteP - 2 css issue of Projects

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2373]
#### Issue

If you edit the Project record, after push the save button, it tooks you on Giant View and not on Detailview. The cancel button work as i expected (it takes you to Detaiview)
- there are 2 css issues for SuiteP theme

A. the Save&Cancel buttons in Editview - bellow buttons different colors

![project](https://cloud.githubusercontent.com/assets/5773777/19070807/59ee4b22-8a2d-11e6-923e-c5d50d277397.png)

B: Create Project Task --> Calendar --> Date color, if you choose the date from calendar

![pt](https://cloud.githubusercontent.com/assets/5773777/19070880/b7a05896-8a2d-11e6-89b2-c7e139063620.png)
#### Your Environment

- SuiteCRM Version used: 7.7.5 Official demo
- Browser name and version: 53.x m 32bit
- Operating System and version: Win 10 Home

**Comment by shogunpol** [comment]
@Mausino  , please do not write two issues in one place, it causing sometimes difficulties, when we solve one of multiple issues raised in one post.
In Projects  after push the save button, it takes you to the Giant View it is intentional, If you want raise this issue and we can mark it as a suggestion, I would however recommend this is done in a separate issue it is kept separate to the bug within this one.

**Comment by sieberta** [comment]
@Mausino, see my forum post on how to change the behavior on project save.  I will note, however, this is not upgrade safe.  https://suitecrm.com/forum/suitecrm-7-0-discussion/10829-version-7-7-1-default-project-view-is-gantt-chart-how-to-change

@shogunpol sorry for continuing the two issues in one thread predicament.

**Comment by Mausino** [comment]
@shogunpol thank you for feedback, in next time i will post if separatly
@sieberta great suggestion for self changing

**Comment by ChangezKhan** [comment]
Both CSS issues are not available on SuiteCRM 7.8.2.

**Comment by samus-aran** [comment]
@Mausino The Save button taking you to the Gantt is intentional  rather than the detail view.  So we wouldn't state that as a bug.  So the bug is that the Cancel button takes you to the DetailView rather than the expected Gantt view. Change the priority of this bug to low as the CSS issues have been resolved.

**Comment by Mausino** [comment]
@samus-aran yes i agree with you.. for people which cooperate together it is  after save function in editview better giantt view... but i have one question + suggestion

question: why when user click on listview (or name of project record) tooks him into detailview, but isn't into giant view ? if is by default set up after editview action

suggestion: could be instead of link View Details there the button... it think it will better orientation in this view
![2017-05-17_1351](https://cloud.githubusercontent.com/assets/5773777/26152742/8722b1a0-3b08-11e7-8a5a-d7a3310b4371.png)

**Comment by Dillon-Brown** [comment]
Unable to replicate in 7.8.x. Please re-open if this is still an issue you can replicate and provide clear steps for. Thanks.
