### ISSUE TITLE
Logo upload function is not working

### ISSUE THREAD

**Issue by saleembdr** [salesagility/SuiteCRM#2464]
#### Issue

The logo upload function is not working. A message with the type of supported images is shown even though a supported image is uploaded.
#### Expected Behavior

The logo image should be uploaded.
#### Actual Behavior

A message indicating supported image types is shown.
#### Possible Fix

The variable '$upload->temp_file_location' includes a path with the extension 'tmp' in the file 'modules/Configurator/UploadFileCheck.php'
#### Steps to Reproduce
1. Login
2. Go to the administration section
3. Click on system settings
4. Attempt to upload a image with a supported extension

![image](https://cloud.githubusercontent.com/assets/10287173/19597205/d3343e4e-979b-11e6-8fea-3902ba641192.png)
#### Context

I was trying to change the logo that is shown on the login screen of SuiteCRM.
#### Your Environment

SuiteCRM 7.7.4 using Microsoft SQL Server and PHP 7 on IIS.

**Comment by shogunpol** [comment]
The issue has been tested in recent version of SuiteCRM(7.7.6), and it not appear,
@saleembdr , can you confirm is this not issue any more in recent version of SuiteCRM, if yes can you close an issue.
Thanks for your contribution.

**Comment by Ninidelaogong** [comment]
Hi,
I am using SuiteCRM V7.7.6. and the problem still occurs. I have tried  .jpeg and  .png.
The images have a max. height aof 170px and a width of 368px and even smaller and the message described shows.
![error_message](https://cloud.githubusercontent.com/assets/23031353/19646129/62813a6c-99f8-11e6-90b0-93511e5c7e92.JPG)
![version](https://cloud.githubusercontent.com/assets/23031353/19646128/627fdc8a-99f8-11e6-9f45-be6fb61df497.JPG)

**Comment by saleembdr** [comment]
I have installed the version 7.7.6 for testing. The same message is encountered while trying to upload a JPEG image for the logo. The following screen-shot provides more information.

![image](https://cloud.githubusercontent.com/assets/10287173/19674773/f2b7e55a-9a92-11e6-954c-0ec9aa0a40a2.png)

**Comment by shogunpol** [comment]
@saleembdr , just quick question, did you try with another images, and extensions? like take some pictures with different size .jpg .jpeg .png, and try out?
Thanks for your contribution.

**Comment by saleembdr** [comment]
@shogunpol. I tried downloading the logo that is currently used on the system and uploading it again. The same message was encountered. The downloaded logo from the application that is on the login page is named 'company_logo.png'.

**Comment by shogunpol** [comment]
@saleembdr , i just ask different question, use any other pictures with above described extensions.
 Thanks for your contribution.

**Comment by Ninidelaogong** [comment]
@shogunpol well you didn't ask me, but I tried several pictures with different extensions and sizes. Always the same problem.

**Comment by Ninidelaogong** [comment]
@shogunpol  as I understand you are involved in the development. Can you send me the structur of the programm, so I can take a look by myself what could be the problem ?

**Comment by shogunpol** [comment]
@Ninidelaogong , you can download recent version of SuiteCRM(7.7.6), on:
https://suitecrm.com/download/suitecrm.

**Comment by saleembdr** [comment]
@Ninidelaogong. You can temporarily fix the problem by adding 'tmp' to the array in the following statement:

$supportedExtensions = array('jpg', 'png', 'jpeg');

This statement is in the file 'modules/Configurator/UploadFileCheck.php'. You can remove the 'tmp' value after uploading the image. Keeping the value 'tmp' will cause SuiteCRM to accept any file type for uploads.

**Comment by Ninidelaogong** [comment]
@saleembdr thanks for the hint. I tried but it didn't work with my installation. I didn't get the error message anymore but there was also no upload.
I found out that the same problem is with sugarcrm.

**Comment by saleembdr** [comment]
@Ninidelaogong. Print the value in the field '$upload->temp_file_location' of the 'UploadFileCheck' file. The file extension in this path should be temporarily added to the array.

**Comment by shogunpol** [comment]
After additional information, i been able to replicate an issue in recent version of SuiteCRM(7.7.6),
the issue appear only in MSSQL.
@saleembdr , we label this issue as a "Bug"
thanks for your contribution.

**Comment by saleembdr** [comment]
@Ninidelaogong. I was mistaken about the file that can be changed for a temporary fix. The correct file to change temporarily is 'include\utils.php'. The following statement is the one that can be changed by adding the 'tmp' value mapping:

$supportedExtensions = array('jpg' => 'image/jpeg', 'jpeg' => 'image/jpeg');

**Comment by Ninidelaogong** [comment]
@saleembdr perfect thank you so much, works perfectly.

**Comment by shogunpol** [comment]
@saleembdr , may i ask you to test this issue on our official demo instance? if is work? 
http://demo.suiteondemand.com/index.php?action=Login&module=Users

**Comment by horus68** [comment]
@shogunpol confirmed in 7.8 beta: can't upload a new logo. 
I can upload a logo when installing (the install screen) but I can't change the logo later (using Admin / system settings)
The message is the same as above "its not a jpeg or png."
Note: I even tested to upload the same image used ok when installing, so its not the image.

Suggestion: there should be an option to delete the actual logo!

**Comment by saleembdr** [comment]
I was also not able to test this on the demo instance because I do not have access to the administration section.

**Comment by bmwtourer** [comment]
just to add precision, I installed a brand new test instance of 7.8.3 and the problem remains...

**Comment by cloudcon** [comment]
Problem still remains in Versão 7.9.4

**Comment by pgorod** [comment]
In duplicate issue #5530 user @kanagaraj1305 suggests it's a problem with the security verification condition here: 

https://github.com/salesagility/SuiteCRM/blob/master/include/utils.php#L5089

**Comment by spencershaw** [comment]
I have the same problem. See https://suitecrm.com/suitecrm/forum/installation-upgrade-help/18669-logo-upload-broken-system-generates-mod-strings-lbl-logo-error#64148

**Comment by spencershaw** [comment]
It's painful. I gave up.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Ricardo <notifications@github.com> Date: 11/29/18  10:28  (GMT+00:00) To: salesagility/SuiteCRM <SuiteCRM@noreply.github.com> Cc: Spencer Shaw <spencer@streetlike.com>, Comment <comment@noreply.github.com> Subject: Re: [salesagility/SuiteCRM] Logo upload function is not working
  (#2464) 
I am having this issue on a fresh install of 7.10.10

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/salesagility/SuiteCRM","title":"salesagility/SuiteCRM","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/salesagility/SuiteCRM"}},"updates":{"snippets":[{"icon":"PERSON","message":"@maverick85 in #2464: I am having this issue on a fresh install of 7.10.10"}],"action":{"name":"View Issue","url":"https://github.com/salesagility/SuiteCRM/issues/2464#issuecomment-442783787"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/salesagility/SuiteCRM/issues/2464#issuecomment-442783787",
"url": "https://github.com/salesagility/SuiteCRM/issues/2464#issuecomment-442783787",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [salesagility/SuiteCRM] Logo upload function is not working (#2464)",
"sections": [
{
"text": "",
"activityTitle": "**Ricardo**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@maverick85",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"salesagility/SuiteCRM\",\n\"issueId\": 2464,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"salesagility/SuiteCRM\",\n\"issueId\": 2464\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/salesagility/SuiteCRM/issues/2464#issuecomment-442783787"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 175411215\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by saleembdr** [comment]
> I am having this issue on a fresh install of 7.10.10
> 
> It is a brand new installation. Everything else seems to be working so far.
> I have a jpg logo that each time I try to upload it it gives me the error:
> 
> `The file format of the image must be JPEG or PNG. Upload a new file with the file extension .jpg or .png.`

Check a possible resolution in my comment on the 28 of October 2016.

**Comment by pgorod** [comment]
Maybe an easier workaround is to just go into the server using a shell and replacing the file 

`themes/default/images/company_logo.png`

and making sure it has read access by your web server...

**Comment by AmirMustafa** [comment]
I have freshly installed the latest version:
Version 7.10.11 
Sugar Version 6.5.25 (Build 344)

When I upload the image, image gets uploaded but it does not reflect the website. i.e. company logo does not change. Please guide me.

**Comment by spencershaw** [comment]
We gave up. Loads of bugs in the software.

Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Amir Mustafa <notifications@github.com> Date: 1/8/19  08:35  (GMT+00:00) To: salesagility/SuiteCRM <SuiteCRM@noreply.github.com> Cc: Spencer Shaw <spencer@streetlike.com>, Comment <comment@noreply.github.com> Subject: Re: [salesagility/SuiteCRM] Logo upload function is not working
  (#2464) 
I have freshly installed the latest version:

Version 7.10.11

Sugar Version 6.5.25 (Build 344)
When I upload the image, image gets uploaded but it does not reflect the website. i.e. company logo does not change. Please guide me.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/salesagility/SuiteCRM","title":"salesagility/SuiteCRM","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/salesagility/SuiteCRM"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AmirMustafa in #2464: I have freshly installed the latest version:\r\nVersion 7.10.11 \r\nSugar Version 6.5.25 (Build 344)\r\n\r\nWhen I upload the image, image gets uploaded but it does not reflect the website. i.e. company logo does not change. Please guide me."}],"action":{"name":"View Issue","url":"https://github.com/salesagility/SuiteCRM/issues/2464#issuecomment-452215890"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/salesagility/SuiteCRM/issues/2464#issuecomment-452215890",
"url": "https://github.com/salesagility/SuiteCRM/issues/2464#issuecomment-452215890",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AmirMustafa** [comment]
Ohhh.. thanks for the update Spencer :)

**Comment by doapydave** [comment]
7.5.11
tried all the suggestions above.  still cant upload logo during install.  would be nice to get resolution at some point.  for now, i'll just change it in the fs.

**Comment by pgorod** [comment]
I'm afraid this can't be fixed if it can't be reproduced...

If one of you can please provide
- a specific image file you used and triggered this issue
- what messages did you get in your logs during that upload
- basic version info: SuiteCRM, PHP, Database

Thanks.

**Comment by mauriciocano** [comment]
Same problem in 7.11.5, 7.11.6. There is some workaround to this issue?

**Comment by pgorod** [comment]
@mauriciocano can you provide the information I asked for in my last comment?

**Comment by MyBlissIT** [comment]
1. I tried to recreate my logo according to dimensions of SuiteCRM logo, saved as .png and .jpeg but both files did not upload, I still received the same error message.

2. I subsequently downloaded SuiteCRM logo and re-uploaded it again, it was uploaded.

Is there still no possible fix?

**Comment by MyBlissIT** [comment]
> I'm afraid this can't be fixed if it can't be reproduced...
> 
> If one of you can please provide
> 
> * a specific image file you used and triggered this issue
> * what messages did you get in your logs during that upload
> * basic version info: SuiteCRM, PHP, Database
> 
> Thanks.

On number 2 of your list this is the log:

Thu Jul 11 20:49:40 2019 [341750][1][FATAL] A user (1) attempted to use an invalid file for the logo - upload://tmp_logo_company_upload/CRM%20Logo%20Test.jpg
Thu Jul 11 20:50:11 2019 [349043][1][FATAL] A user (1) attempted to use an invalid file for the logo - upload://tmp_logo_company_upload/CRM%20Logo%20Test.png

Number 3:

Version 7.10.17
Sugar Version 6.5.25 (Build 344) on PHP Version 7.3

**Comment by pgorod** [comment]
This won't go anywhere until somebody provides what is being asked, sorry. If you have a file that doesn't work, please provide it so I can reproduce the problem here. It's simple, but for some reason weeks go by and nobody is able to give me what I asked for...

**Comment by pgorod** [comment]
If you don't want to put the file up publicly, email it to community@suitecrm.com

Thanks

**Comment by MyBlissIT** [comment]
> This won't go anywhere until somebody provides what is being asked, sorry. If you have a file that doesn't work, please provide it so I can reproduce the problem here. It's simple, but for some reason weeks go by and nobody is able to give me what I asked for...

https://drive.google.com/file/d/1CUQxasBdQRkrl7frYpUqJ7DVXFF6crYn/view?usp=sharing

**Comment by Dillon-Brown** [comment]
@MyBlissIT Thanks! I've just replicated this using your image. The problem is the space in the filename, as a temporary workaround, you should be able to remove it and upload as normal.

**Comment by pgorod** [comment]
The_irony,_that_after_years_with_this_issue,_and_16_participants_here,_and_dozens_of_comments,_in_the_end_the_issue_is_spaces_in_the_filename._I'm_dumping_spaces_altogether,_from_now_on

**Comment by MyBlissIT** [comment]
> @MyBlissIT Thanks! I've just replicated this using your image. The problem is the space in the filename, as a temporary workaround, you should be able to remove it and upload as normal.

@pgorod you telling me the fix is naming a file as "CompanyLogo.jpeg" instead of "Company Logo.jpeg"

**Comment by pgorod** [comment]
To be more precise, Dillon is telling you that, not me :-)

**Comment by MyBlissIT** [comment]
I removed the space on the filename and I believe the file is uploaded because I do not recieve the error message.

However, the SuiteCRM logo still appears on my Log In page + dashboard.

I uploaded via System Settings -> Select Logo

**Comment by pgorod** [comment]
Quick Repair and rebuild
Ctrl-F5 in the browser to refresh

**Comment by Dillon-Brown** [comment]
Interesting, I'm able to replicate that as well (Image uploads but still shows the old one), it looks like @pgorod is right and a hard browser refresh fixes it though.

**Comment by MyBlissIT** [comment]
> Quick Repair and rebuild
> Ctrl-F5 in the browser to refresh

fixed!!! thanks

**Comment by MyBlissIT** [comment]
Now, How do I remove the SuiteCRM on the top left of the dashboard?

![image](https://user-images.githubusercontent.com/34719141/61124836-52ac5f00-a4a8-11e9-815c-0291f05d085d.png)

**Comment by MyBlissIT** [comment]
> Now, How do I remove the SuiteCRM on the top left of the dashboard?
> 
> ![image](https://user-images.githubusercontent.com/34719141/61124836-52ac5f00-a4a8-11e9-815c-0291f05d085d.png)

I would possibly like to have my own Favicon as well

**Comment by pgorod** [comment]
Please search the Forums for those answers, that is not part of this bug here. Thanks for you help debugging this.

**Comment by MyBlissIT** [comment]
Thank you @Dillon-Brown , you assisted me on 2 bug issues today.

**Comment by horus68** [comment]
> The_irony,_that_after_years_with_this_issue,_and_16_participants_here,_and_dozens_of_comments,_in_the_end_the_issue_is_spaces_in_the_filename._I'm_dumping_spaces_altogether,_from_now_on

Lets hope this is solved now. Only to remember that initially the bug also affected no space files!
`I confirm the bug. Tried both JPG and PNG with several sizes, no space or no non-alpanumeric.`
https://github.com/salesagility/SuiteCRM/issues/502#issuecomment-167022664

**Comment by macktic** [comment]
nope, still not working for me.
![sebsspace](https://user-images.githubusercontent.com/13149707/62412932-d4ebf700-b600-11e9-893d-db9a8d7595a3.png)

**Comment by macktic** [comment]
same image worked when I chose it during install, but I reinstalled and left that option, now it won't update

**Comment by Dillon-Brown** [comment]
@macktic Interesting, my initial assumption would be permissions but I'll give this a try on Monday with your image and see if I can replicate.

**Comment by romannl** [comment]
In xampp with SuiteCRM 7.10.20 (I don't know if in other cases too) the error is in **utils.php**
function **verify_uploaded_image(...**
`
{
    $supportedExtensions = array('jpg' => 'image/jpeg', 'jpeg' => 'image/jpeg');
    if (!$jpeg_only) {
        $supportedExtensions['png'] = 'image/png';
    }

    if (!file_exists($path) || !is_file($path)) {
        return false;
    }

    $img_size = getimagesize($path);
    $filetype = $img_size['mime'];
    $tmpArray = explode('.', $path);
    $ext = end($tmpArray);

    if (substr_count('..', $path) > 0 || ($ext !== $path && !isset($supportedExtensions[strtolower($ext)])) ||
            !in_array($filetype, array_values($supportedExtensions))
    ) {
        return false;
    }
`
Pay attention that $supportedExtensions[] are: **jpg, jpeg** and **png**
BUT the temporary file created after upload has **tmp** extension.

That is why this function always returns false.

For quick fix you can add "tmp" extension to this function as valid, or change the upload file name to have correct extension in tmp directory.
I think it would be best to add tmp extension to $supportedExtensions, since the file type gets validated anyway in this sentence:
!in_array($filetype, array_values($supportedExtensions))

Regards,
Roman.

**Comment by Santosgusta2010** [comment]
Hi all, I'm still having the same issue. I'm ussing SuiteCRM Versión 7.11.10 Sugar Versión 6.5.25 (Preparado 344) and the logo file attached. All is running in Windows.
Any help Will be appreciatted. Thanks.
![LogoIFF](https://user-images.githubusercontent.com/19849910/69543574-ab1e5d80-0f6c-11ea-98eb-64fa1cb4f9fe.jpg)

**Comment by romannl** [comment]
> Hi all, I'm still having the same issue. I'm ussing SuiteCRM Versión 7.11.10 Sugar Versión 6.5.25 (Preparado 344) and the logo file attached. All is running in Windows.
> Any help Will be appreciatted. Thanks.
> ![LogoIFF](https://user-images.githubusercontent.com/19849910/69543574-ab1e5d80-0f6c-11ea-98eb-64fa1cb4f9fe.jpg)

@Santosgusta2010 Did you try the solution I proposed in https://github.com/salesagility/SuiteCRM/issues/2464#issuecomment-536640697 ?

**Comment by Santosgusta2010** [comment]
> Hi all, I'm still having the same issue. I'm ussing SuiteCRM Versión 7.11.10 Sugar Versión 6.5.25 (Preparado 344) and the logo file attached. All is running in Windows.
> Any help Will be appreciatted. Thanks.
> 
> 
> @Santosgusta2010 Did you try the solution I proposed in #2464 (comment) ?
> Like, this:
> Open utils.php
> Edit function verify_uploaded_image(...
> Change:
> $supportedExtensions = array('jpg' => 'image/jpeg', 'jpeg' => 'image/jpeg');
> To:
> $supportedExtensions = array('jpg' => 'image/jpeg', 'jpeg' => 'image/jpeg', 'tmp' => 'tmp');
> Save and test.
> Be careful, this change is not update-safe in SuiteCRM, but once you change the logo, you won't need this function.

Hi, I'm not sure where the utils.php files is located. I changed content on the file UploadFileCheck.php

**Comment by romannl** [comment]
> Hi, I'm not sure where the utils.php files is located. I changed content on the file UploadFileCheck.php

Sorry about that, I updated the response to include the directory:
/include/uptils.php
And what did you change in UploadFileCheck.php? Did it work?

**Comment by Santosgusta2010** [comment]
> Hi, I'm not sure where the utils.php files is located. I changed content on the file UploadFileCheck.php
> 
> Sorry about that, I updated the response to include the directory: <-- Don't worry
> /include/uptils.php
> And what did you change in UploadFileCheck.php? Did it work?

I changed modules\Configurator\UploadFileCheck.php and add 'tmp' to $supportedExtensions = array('jpg', 'png', 'jpeg','tmp'); but didn't work.
Now I've changed  include/uptils.php as you say and is working now. Thanks for helping.

**Comment by pgorod** [comment]
Can somebody make a PR with this change to the SupportedExtensions array?
