### ISSUE TITLE
History sub-panel filter

### ISSUE THREAD

**Issue by stevejenkin** [salesagility/SuiteCRM#2559]
#### Issue

The filter option in all History sub-panels does not work, filtering by Type, Name or date does not work. 

#### Expected Behavior

When filtering only the required history items should be displayed.

#### Actual Behavior

All history items are displayed, no matter what filter is used.
#### Steps to Reproduce

1. Navigate to any record that has a history sub-panel
2. Open the record and click on the 'Filter' button in the sub-panel
3. Select a filter to display only the required history items
4. Click Search

#### Context

I feel this is high priority for those that have a large number of history items within a record, filtering by type or date is very useful but the filtering is not working.

#### Your Environment

* SuiteCRM Version used: 7.7.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 54.0.2840.71 m
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6, PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): CENTOS 7.2 x86_64

**Comment by staganyi** [comment]
Can confirm this does not work on v7.7.7 either.

**Comment by vladbar** [comment]
This might be related to issue #2106 and might have the same cause.

**Comment by FibreCRM** [comment]
Hi SuiteCRM, any news on the progression of fixing this bug?

**Comment by Mausino** [comment]
@stevejenkin @vladbar @daniel-samson 

We applied fix #2559 and was worked for SuiteCRM version 7.8.x, but for version 7.9.x needs to update this code because there was big rewamp of email module.

Now "FILTER" in History subpanel work in wird way 👎  when you applied this patch

When you filter for example only task without any other parameters.. it should show you only tasks, but shows you emails and tasks... Same for meetings + calls
"FILTER" for Notes + Emails don't work

**Comment by daniel-samson** [comment]
I can confirm that this is still an issue on SuiteCRM 7.9.3.

**Comment by icetear** [comment]
This was opened many months ago. It's interesting that it's still an issue. Is anybody working on SuiteCRM?
