### ISSUE TITLE
SuiteP - Main menu navbar is over the email pop up window

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2573]
#### Issue

If you try to set up your mail, you will see that the pop up  window is under navbar

![email](https://cloud.githubusercontent.com/assets/5773777/20050868/0b056f72-a4cc-11e6-954d-18425939eafa.png)

Second issue is, that titles in headers of tables are white and in SuiteP are invisible on white background

![headers_email](https://cloud.githubusercontent.com/assets/5773777/20050916/690635d4-a4cc-11e6-832b-ae8b8400caad.png)

#### Steps to Reproduce

1. Admin
2. Inbound Emails
3. Create Email
4. Select Folder for email (if you set up the IMAP)

#### Your Environment

* SuiteCRM Version used: 7.7.6
* Browser name and version: Chrome 64 bit 54.x
* Environment name and version: PHP 5.6, MySQL 5.6
* Operating System and version: Win 10 Home

**Comment by Mac-Rae** [comment]
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. 
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. 
If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.
For more information about 7.8.x end of life please visit our [blog post ](https://suitecrm.com/7-8-x-end-of-life/)
