### ISSUE TITLE
AOP contact receives 2 emails

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#275]
If a contact emails a support address, they receive 2 emails from AOP, one where no template variables are filled in, the other with Case details filled in correctly.

**Comment by adriangibanelbtactic** [comment]
This bug is solved by removing:

```
        if($emails && $email_template){
            $GLOBALS['log']->info("AOPCaseUpdates: Calling send email");
            $res = $this->sendEmail($emails, $email_template, $signature, $this->case_id, $addDelimiter);
        }
```
(Lines 81 to 84)
from:

https://github.com/salesagility/SuiteCRM/blob/e50da7faeec000d055b8b42a81e4f2c3efc3f687/modules/AOP_Case_Updates/AOP_Case_Updates.php

Direct link to lines to be removed:
https://github.com/salesagility/SuiteCRM/blob/e50da7faeec000d055b8b42a81e4f2c3efc3f687/modules/AOP_Case_Updates/AOP_Case_Updates.php#L81-L84

It seems that the AOP2 merge did some wrong assumptions. Some other assumptions from AOP2 might lead to other bugs.

Can anyone apply the fix?

Thank you.

**Comment by shogunpol** [comment]
It was done proper testing on different accounts, emails, and options in Inbound Email.
Conclusion: The described bug do not appear in current (7.7) version of SuiteCRM.
Suggestions: Close the Bug Case.
