### ISSUE TITLE
Delete confirmation ignores "Cancel" and deletes anyway

### ISSUE THREAD

**Issue by LordVan** [salesagility/SuiteCRM#2862]
#### Issue

When pressing Delete (tested on account, contact and offer) a confirmation dialogue pops up, but no matter what is pressed the record is deleted

#### Expected Behavior

"Cancel" Button goes back and it does not delete anything.

#### Actual Behavior

Either button press leads to deletion of the data

#### Possible Fix

maybe bug in javascript ?

#### Steps to Reproduce

1. create dummy contact / account
2. delete from details or list screen
3. choose cancel
4.

#### Context

Easy accidental deletion of data!

#### Your Environment

* SuiteCRM Version used: 7.7.8 and 7.7.9 tested
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 55.... on linux and windows
* Environment name and version (e.g. MySQL, PHP 7): php 5.6.27, mariadb-10.0.22
* Operating System and version (e.g Ubuntu 16.04): Gentoo

**Comment by LordVan** [comment]
the bug only happens with SuiteP theme not suite7

**Comment by urdhvatech** [comment]
​I checked and confirm that it "deletes" record even if one press "cancel"

It happens if you are in SuiteP theme and the DetailView buttons are not grouped together. i.e Admin->System Settings->Display actions within menus = off

This shows the buttons in sequential order on detailview. Now when you click delete and press cancel the record gets deleted.

**Proposed solution** is adding "retun false;" in the onclick event of the delete button.

**Go to file** 
- include/Smarty/plugins/function.sugar_button.php

Around line no 341:  there would be a block case for generating DELETE button, on its onclick event, add return false; 
Below is the example of it.

`$output = '{if $bean->aclAccess("delete")}<input title="{$APP.LBL_DELETE_BUTTON_TITLE}" accessKey="{$APP.LBL_DELETE_BUTTON_KEY}" class="button" onclick="'.$js_form.' _form.return_module.value=\'' . $module . '\'; _form.return_action.value=\'ListView\'; _form.action.value=\'Delete\'; if(confirm(\'{$APP.NTC_DELETE_CONFIRMATION}\')) SUGAR.ajaxUI.submitForm(_form); return false;" type="submit" name="Delete" value="{$APP.LBL_DELETE_BUTTON_LABEL}" id="delete_button">{/if} ';`

This would solve the issue.

**Comment by CamoMacdonald** [comment]
Just to confirm this is only happening on detail view, if you do it through list it works as expected :)

**Comment by urdhvatech** [comment]
@CamoMacdonald Yes, it is just for detail view only, but it can delete someone's important data accidentally. I proposed quick fix on my previous comment.

**Comment by CamoMacdonald** [comment]
@urdhvatech Yeah was just confirming for testing purposes.
*Incase this does happen in the interim, if a record is deleted from the CRM by accident it can be retrieved from from the DB by changing the Deleted field from 1 to 0 unless in the schedular if the Prune Database job is active
