### ISSUE TITLE
Enable Legacy Search for all Modules Needed

### ISSUE THREAD

**Issue by cjmny** [salesagility/SuiteCRM#3152]
#### Issue
When many modules are in use, or many custom modules are in use, trying to use the config_override to disable the new filtering is difficult at best.

Would it be possible to add it as a system wide setting in the UI?  Basically allow disabling of the filter in favor of the search?

**Comment by pgorod** [comment]
What exactly are the difficulties you're experiencing with the new filters?

It would be nice to be able to move forward, instead of having SuiteCRM full of legacy modes and special configs. Of course, to do this and keep everybody happy we would have to try and improve whatever is bothering you or your users... what is it? : - )

**Comment by cjmny** [comment]
We have some users here who are, for lack of a better way to say it, not comfortable with change.  When we go in to the "Accounts" module, I have a very specific set of fields configured for people to use for search.  They go into the module, click in the field they want to search, and find the account.  Similar situations happen in prospects, leads, campaigns, contacts, and many many custom modules.  With the filter, it gives power users a good tool, but your normal "office user" has extra clicks, things are moved around, and forces you into a modal window.

**Comment by pgorod** [comment]
Yes I agree with you, perhaps the advanced search shouldn't be so hidden from direct access...

**Comment by murdal** [comment]
Our approach is to separate 'Filters' and 'Search'. Basic and Advanced Filters on each module view for list based actions then improved global searching from main navigation to find 'specific' record. This would ultimately be less clicks as you would not have to go; Select Module, Clear Current Search Criteria, Input New Search Criteria, Click Search.

Although there has been one extra click to get to the search screen there is potentially less clicks to clear a search, selected a save search or change the list view layout. That's not including scrolling clicks if you had a large Basic/Advanced search panel.

Rather than default to making it easier to do it the old way it would be good to look at reviewing the current method and improving that. For example, adding filter fields at the top of columns which could replace basic search. Then we only have one modal window for advanced.

**Comment by gunnicom** [comment]
Just for reference, i already had that issue and it was refused: https://github.com/salesagility/SuiteCRM/issues/2884

**Comment by evgu** [comment]
@shogunpol please note that enable_legacy_search does not work for all modules.  
E.g. $sugar_config['enable_legacy_search'][] = 'Targets'; does not enable legacy search for Targets.  Bug: #3179 submitted. 

@pgorod, Feedback from all our users was that legacy search was much easier to use as search criteria was directly visible on load of the listing, without having to hover around. Compnies often have complex segmentation of leads/accounts data and the new filter is premature from UX perspective when we need to use a complex search criteria.

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enable Legacy Search for all Modules Needed](https://trello.com/c/RKZZZEdq/25-enable-legacy-search-for-all-modules-needed)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
