### ISSUE TITLE
Email popup for Related

### ISSUE THREAD

**Issue by VRedguard** [salesagility/SuiteCRM#3191]
#### Issue

windows go under top bar

#### Expected Behavior

![capture d ecran 2017-02-15 a 16 31 30](https://cloud.githubusercontent.com/assets/23078474/23307227/c75bdbc2-fa74-11e6-8da9-4d96d629bc43.png)

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Mausino** [comment]
@edilex please edit your ticket issue and add there how do the users reproduce issue (i found 2 ways)

1. Any detailview of record --> Activity Subpanel --> Compose email
![email_issue](https://cloud.githubusercontent.com/assets/5773777/23310609/65af7b10-fab3-11e6-8298-e7c45c856af6.png)

2. Email --> click on any email -> View dropdown button --> Display Headers or Display Raw Email
![email_issue_2](https://cloud.githubusercontent.com/assets/5773777/23310616/6c80af36-fab3-11e6-9d16-44c75e80d836.png)

**Comment by shogunpol** [comment]
@edilex , what window, what module? please provide steps to reproduce an issue.

**Comment by Mausino** [comment]
@shogunpol i reproduced all 3 issue situation with screenshots

1. Any detailview of record --> Activity Subpanel --> Compose email
2. Email --> click on any email --> View dropdown button --> Display Headers or Display Raw Email
3. Email ---> click on any email --> Quick Create dropdown button -> Choose any you want

or i can create separate issue ticket when you want.

**Comment by Dillon-Brown** [comment]
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
