### ISSUE TITLE
Wrong advanced filter message in Suite7 and SuiteR themes

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#3234]
Wrong advanced filter message after adding to the filter a non-existent criterion.

#### Expected message
"No results found... Perhaps change your search criteria and try again?"

#### Actual message
 "No results found.
or change your search criteria"

#### Your Environment
* SuiteCRM Version used: 7.8.2

**Comment by shogunpol** [comment]
@likhobory , please provide steps to reproduce on real case.

**Comment by likhobory** [comment]
1. Select SuiteR theme in user profile
2. Select List View for some module (Accounts, for example)
3. Select Filter->Advanced filter
4. Put some non-exisnent value to the filter field (for example 'йцукен' to account name field as search criteria) and push the search button

![default](https://cloud.githubusercontent.com/assets/5983672/23705956/2d197d5a-041d-11e7-9f36-2a975f73cb4a.png)

**Comment by horus68** [comment]
@shogunpol  instead of the full message from /include/language/en_us.lang.php
'MSG_LIST_VIEW_NO_RESULTS_CHANGE_CRITERIA' => 'No results found... Perhaps change your search criteria and try again?',
https://github.com/salesagility/SuiteCRM/blob/673712cc1faf269d470767430bf734e09f126b6a/include/language/en_us.lang.php#L2082

There are 2 strings displayed:
'MSG_LIST_VIEW_NO_RESULTS_BASIC' => 'No results found.',
https://github.com/salesagility/SuiteCRM/blob/673712cc1faf269d470767430bf734e09f126b6a/include/language/en_us.lang.php#L2081

'MSG_LIST_VIEW_CHANGE_SEARCH' => 'or change your search criteria',
https://github.com/salesagility/SuiteCRM/blob/673712cc1faf269d470767430bf734e09f126b6a/include/language/en_us.lang.php#L2085

This would only be correct if some value is supposed to be displayed in between the 2 strings.

See the usage of 'MSG_LIST_VIEW_CHANGE_SEARCH'  (2 files)
https://github.com/salesagility/SuiteCRM/search?utf8=%E2%9C%93&q=%27MSG_LIST_VIEW_CHANGE_SEARCH%27+
