### ISSUE TITLE
Adding Line Itens in Quote 'desapearing'

### ISSUE THREAD

**Issue by liviozanol** [salesagility/SuiteCRM#3269]
Inicial clean deployment of SuiteCRM version 7.8.1.

We have multiple Line Items using multiple Line Items Group. Current 11 Groups with approximatally 4 items in each group for one client (each group is a Virtual Machine)

#### Issue
Line Items and Groups are deasapearing from the quotes without any message (neither in the logfile)

After adding a few groups and line items sucessufully I started to have problems. After 11 created sucessufully, opened the Editor and added about 5 new groups, each with ~ 4 itens, pressed the save button and all "went well".

But, reviewing the line items quote shows me wrong number of groups items, wrong number of items in some groups and some weird behavior sometimes, like desapearing items and items appearing without group.

![Adding a single new Item](https://cloud.githubusercontent.com/assets/10122064/23868528/86f69580-07fe-11e7-974e-e40ebf87c0da.png) (all is fine)

![After Saving](https://cloud.githubusercontent.com/assets/10122064/23868566/a479e1a2-07fe-11e7-9c1d-c74c1ced3f47.png)
- The added Item desapears;
- The total is zero!

Tried to erase and create the group again, but when I tried this suddenly the group also desapears now and can't be created.

#### Expected Behavior
The items should appear correct at the Quote Screen

#### Actual Behavior
Items randomly desapear and some items can appear, but without their groups

#### Possible Fix
Don't Know

#### Steps to Reproduce
Don't Know

#### Context
Trying to create my first quote.

#### Your Environment

* SuiteCRM Version used: 7.8.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 56.0.2924.87
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.6.30, MySQL 5.5.54, Apache 2.4.10
* Operating System and version (e.g Ubuntu 16.04): Debian 8

**Comment by horus68** [comment]
Can you replicate this in actual version 7.8.2 using the demo site?
https://suitecrm.com/demo

**Comment by liviozanol** [comment]
@horus68 , thanks for your help!

I've just tried to replicate the behavior using the demo site but I couldn't... Created ~ 24 groups with 4-5 items each and the problem didn't happened...

Nevertheless, I've made a video showing the problem in our enviroment... Could you please take a look?
https://youtu.be/KzPCQET8J8k

**Comment by pgorod** [comment]
@liviozanol this is a typical forum issue, it doesn't belong here in Github. You have to do some basic troubleshooting before you come here to report a bug.

**Comment by kdjmonaghan** [comment]
@liviozanol 

I've tried to replicate your issue with the information you've provided on an 7.8.2 instance (the latest version):

![screenshot from 2017-03-15 11-26-30](https://cloud.githubusercontent.com/assets/3587120/23946462/6682fc9c-0972-11e7-9311-1a9ad0c080bd.png)

![screenshot from 2017-03-15 11-26-03](https://cloud.githubusercontent.com/assets/3587120/23946482/7aaf7aa6-0972-11e7-8a46-16c15f1b99f6.png)

As you can see the information appears as expected here, not the result you're getting. It's possible the issue may be resolved by upgrading to 7.8.2, perhaps your issue was resolved indirectly in the newest build. 

If you're unable to replicate this bug on the demo and you're unable to replicate it on any other instance of 7.8.2, could you try upgrading to 7.8.2 and seeing if the bug exists when you try to create the invoice with the same information?

**Comment by Dillon-Brown** [comment]
Closed due to inactivity / inability to replicate as core issue.
