### ISSUE TITLE
PHP Compatibility check (feature suggestion)

### ISSUE THREAD

**Issue by matteoraggi** [salesagility/SuiteCRM#3309]
I would suggest to the suitecrm team to add a compatibility check while installing and from the admin area, to check quickly the php.ini configuration and other php modules, like vtiger and yetiforce are doing, example:
https://yetiforce.com/images/articles/administrator/install_crm_step_3_yetiforce.png

**Comment by pgorod** [comment]
Like this? What specifically do you think should be added to the pre-installation requirements?

![suite3](https://cloud.githubusercontent.com/assets/15945027/24261634/80c299a4-0fef-11e7-9036-112e380a688e.png)

**Comment by matteoraggi** [comment]
That it is wonderful! yeah! Why don't add this page in the admin area too?
So then the administrators can check more quickly from where troubles could come from..

**Comment by pgorod** [comment]
I recently did a Pull Request that solves some frequent permissions problems. Some of those changes include improvements to the information  shown to the end-user, namely about how to set up cron correctly. See #3268 

I have more fixes coming up but frankly I'm waiting for that to get merged before I spend more time on this. I'm willing to contribute fixes that get into the product, but I'm not willing to contribute fixes that get stuck on Github : - )

One of my future plans is to improve the Admin --> Diagnostics page (have you seen that page already?). I would like to add a summary on top, something that would give all versions, some paths to files, some system configurations, so that people could simply copy-paste that when they ask something on the forums. You'd be amazed how much time I have wasted in my life just getting some noobie to tell me which user it's web server is running under. There should be a way for non-technical people to check that easily.

Some of the things on this installer screen would definitely be part of it. Others wouldn't make much sense (like information about installed PHP modules, you worry about that only once in the beginning).

**Comment by matteoraggi** [comment]
Yes it is an easy page for a developer and big time saving for the assistance.
Ok, but sometiems peopel change the server configuiration for the compatibility to other software and they change the config, plus people can change the php version and change the php servicces too with it..

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PHP Compatibility check (feature suggestion)](https://trello.com/c/hHIafmOm/14-php-compatibility-check-feature-suggestion)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
