### ISSUE TITLE
The codebase must be rewritten from scratch - let's start afresh with 8.x

### ISSUE THREAD

**Issue by muratyaman** [salesagility/SuiteCRM#3329]
- separate frontend-related code to create a "proper" JavaScript app with its own repository
- maybe even create separate repositories for mobile apps
- separate backend-related code to create a "proper" API layer -  e.g. by implementing "modules" as "micro-services" to provide simplicity, modularity, easy maintenance, performance and security by choosing the right tech stack for each micro-service

**Comment by chris001** [comment]
Agreed.  See #3183 and #855.
* For front end JavaScript app, Sugar 7 is using UnderscoreJS and BackboneJS - very good choices for SuiteCRM 8.
* Mobile app just works, because HTML5 responsive CSS design.  Same front end theme, same javascript app as desktop.  Automatically fits the screen size and ppi of smart phone and tablet.
* Backend needs to be compatible with Sugar REST v10 API - for full compatibility with thousands of Sugar 7 (REST v10) compatible modules.

If you want to start immediately, you should fork https://github.com/jakubpas/SuiteCRM - and add UnderscoreJS and BackboneJS to existing REST API, soon will add REST v10 compatible API.

**Comment by muratyaman** [comment]
Thanks Chris.

I was talking at very high level concerns which we share.

For implementation side of frontend, Backbone is very old. I think Node.js + React.js "ecosystem" can help a lot.

For mobiles, I am talking about proper/native mobile apps. Research is needed but I don't think many users enjoy browsing so-called "mobile-friendly" websites on smartphones esp. - certainly not me.

For backend, I was suggesting an overhaul which is much bigger change than a simple RESTful "wrap" around a terrible architecture. I'd not worry about the backward compatibility for old code because the change can even include "ditching" PHP for the sake of a particular micro-service - don't be afraid :)

**Comment by horus68** [comment]
asking for directions from @salesagility and @mattlorimer

**Comment by pgorod** [comment]
Let me explain my downvote on this issue. First, I'm not being offensive, I thank the author for his suggestion and for his architectural recommendations which are wise (in the abstract).

I'm just not convinced that this "rewrite from scratch" attitude will get us anywhere. This is a huge project. We're tied to existing installations, existing add-ons, etc. 

SalesAgility, with its limited resources, has trouble keeping up with even minor fixes to the code. When SugarCRM went into rewriting a lot of code, they poured immense resources into it, lots of developers for a long time... so much, that when they finished it, they got greedy and didn't want to share that value.

So I prefer that these architectural ideas are discussed, of course, but put forward in small-steps, manageable steps. There's no way such an overhaul would go into v. 8. Maybe v. 10 if you're lucky.

Some of the small (and maybe not so small) steps I'm referring to are already started, by people like @adamjakab, @chris001 and @jakubpas, and others (from SalesAgility also, of course).

Anyway, I hope I didn't offend anyone and I _am_ in favor of progress! Peace. : - )

**Comment by chris001** [comment]
Good read about REST Service Oriented Architecture and Microservices.
http://www.ibm.com/developerworks/websphere/library/techarticles/1601_clark-trs/1601_clark.html
Definitely need to be able to install Sugar PHP modules - self developed and 3rd party - and have them just work with the app core.
Modules should talk to one another thru micro services and REST API.
The app core should probably expose module micro services by introspecting the modules and route requests to their interfaces' public functions.

**Comment by muratyaman** [comment]
No worries.
I cannot see this codebase getting anywhere on time with the current pace :(
(The codebase/architecture itself is an obstacle for progress.) The number of issues are not going down, the pull requests are not dealt with in a timely manner either! There are many fundamental mistakes; and I don't see the logic in adopting them for any longer.
Thanks.

**Comment by samus-aran** [comment]
Hi Everyone,

Let me talk to @muratyaman first since he commented last that was outwith the topic of this suggestion.

Yes, we are aware of these issues, and yes we are aware of the 'lack' of activity, but that is an internal process that wasn't dealt with previously but it is now one of higher priorities and will always be improved upon.  I can confirm to say is that for 7.9 we already have our own ambitious KPIs to tackle and have acquired additional resource to reduce these bottlenecks.

Now, regards to addresses those issues of community interaction further, it will be a team effort by ourselves and the community – which I'm hopeful you muratyaman will be a part of since it seems you have a developer knowledge of reviewing Prs? We will approach the community very soon about tackling this resource gap so please do stay tune.

Now, onto the rewrite topic.  To start off I think that it is fantastic that the community is being extremely proactive and voicing your thoughts on how SuiteCRM can and should evolve for the future and at SalesAgility we completely agree and appreciate your enthusiasm to see those changes happen.

However, the question isn't whether we do it, its when and with what resources.  @pgorod pretty much hit the nail on the head.

Building from scratch is not feasible even for an open source project and certainly not for the user base of SuiteCRM.  Rewriting all from scratch we would have the following concerns:

* We will still have to fix the issues in the product. They won't simply disappear with codebase rewrite.
* A rewrite simply adds additional work with minimal pay off – yes for the longer term but how long will this transition be?
* It would likely create new issues (oh joy)
* It won't provide a good upgrade path (lose developers and customers)
* It won't help 3rd developers upgrade their code. Nor will it encourage them to. They might event leave us.
* All the administrative tasks will need to be considered, rewrite all documentation, retrain/retest all areas of the application and upgrade,installation paths etc.

From the above you can kinda get the idea.  Starting a fresh is not possible in a big swoop.

However we should (and are) scheduling in a larger overhaul for v8 and we always had.  However we ourselves need to plan these bigger changes whilst always be mindful of the key statements that we aim to make SuiteCRM the best open source CRM:

* SuiteCRM stays open source
* Keep the development features that makes SuiteCRM a great product for our community
* Ensure SuiteCRM as intuitive as possible – this including our developers and end users
* Appeals to developers
* Provides quality and stability
* Encourages the community to "scratch an itch"
* Easier to maintain
* Moves third party libraries out to composer (which is already planned)
* Has excellent documentation (always improving)
* Enpowers everyone who interacts with it

We need to ensure that we maintain a reasonable number of continued users throughout these 'overhauls' but satisfy the growing community's development needs.  Its a very difficult balancing act we at SalesAgility need to maintain as the main contributor to SuiteCRM.

But, I'm trying not to list excuses, but really emphasis that we do require community contributions to assist these larger progressions.  But please do not suggest a whole rewrite in a single release as that just will not happen :)

I've already given a little hint that we are planning introducing a larger overhaul for SuiteCRM 8 which pretty much covers all what you guys have spoken about and we feel we'll start with the API first and get that functioning as the groundwork for front end changes in larger major releases.  But, we are still in discussions and planning a much longer and more feasible roadmap which will certainly be available before 7.9 is released (May 2017).

**Comment by chris001** [comment]
@muratyaman   Just want to encourage you to give it a go and rapidly make a new front end, with NodeJS + ReactJS talking to the existing PHP REST back end.  The best part about this, is how making a new front end forces you to separate and refactor the code at a high level, pulling apart the bits that are intermingled where they shouldn't be (e.g. Smarty templates in SugarField data field objects) , and refactor them into the appropriate proper separate layers.  The result of which would then be to reduce friction and raise the level of quality, which then would being to accelerate development speed to higher levels.

**Comment by pgorod** [comment]
@muratyaman @chris001 I think #3237 is a good example on how to introduce major overhauls:

- include code with the proposal
- provide the proof of concept
- make it work in a small portion of the app, without breaking the rest, and without changing everything at once
- wait for the rest to catch up, with time, bit by bit

This could easily be applied to the decoupling of the front-end. Start with just some aspect of the app. 

And watch out for possible interference with work being done by SalesAgility on the REST interface - there's no point in doing things that they're already working on.

**Comment by pgorod** [comment]
@muratyaman @chris001 I think #3237 is a good example on how to introduce major overhauls:

- include code with the proposal
- provide the proof of concept
- make it work in a small portion of the app, without breaking the rest, and without changing everything at once
- wait for the rest to catch up, with time, bit by bit

This could easily be applied to the decoupling of the front-end. Start with just some aspect of the app. 

And watch out for possible interference with work being done by SalesAgility on the REST interface - there's no point in doing things that they're already working on.

**Comment by jakubpas** [comment]
I proposed Composer and PSR-4 introduction some time ago but it's still not merged to dev. #3237
