### ISSUE TITLE
Export Target List fails (Database failure)

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#3363]
#### Issue

I get a database error when trying to export the target list as csv as soon as any of the related records include a custom HTML field.

#### Expected Behavior

Target list export works no matter what custom fields are added to modules contacts, leads, targets and accounts.

#### Actual Behavior

Target list export fails when any of the linked modules have a custom HTML field set up.

#### Possible Fix

Reason for the bug:
The mysql query being fired upon export action treats the static HTML field type the same as normal module fields, i.e. it's looking for a column in the ".cstm" table for the respective module. For field type HTML (and perhaps others?) there is no column in the ".cstm" field, so mysql throws an error.

#### Steps to Reproduce

1. set up a custom field of type HTML in one of the four target-list related modules
2. add a record of respective module to a target list
3. export target list as csv (from the actions menu in target list detail view)
4. -> Database error

#### Your Environment

* SuiteCRM Version used: 7.7.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by ChangezKhan** [comment]
@EZS-JD , what exactly database error you got? Kindly let us know.

**Comment by ChangezKhan** [comment]
The issue is in  function `create_export_members_query` available in `modules/ProspectLists/ProspectLists.php` file, where it fetches required data from `fields_meta_data` table and generates query for targetlist modules. Here, the solution will be, we can check whether field type is `html` or not and skip that if we found it. 
But, as we know, that html fields are non-db fields, so I think the proper solution will be if we add one new column `source` in `fields_meta_data` table or do not make entry of fields which are `non-db` by nature.
