### ISSUE TITLE
Email Template - Note Date Entered - Format remains yyyy-mm-dd

### ISSUE THREAD

**Issue by stevejenkin** [salesagility/SuiteCRM#3468]
#### Issue

We have created a workflow from the module Notes as follows:

Condition:
Module - Notes
Field - Platform
Operator - Equal
Type - One of
Value - Currency Cloud, Ebury

Action:
Send Email to Related Field - Leads : Leads

The email template (Attached) contains the $note_date_entered variable, when the email is received by the lead the varaiable is populated however the data format is not correct according to the system date/time format.
   
#### Expected Behavior

The date in the template should read: dd-mm-yyyy

#### Actual Behavior

The date in the template reads yyyy-mm-dd

#### Steps to Reproduce

1. Create a workflow based on the Notes module and set the action to send an email template to a related lead which includes the the variable $note_date_entered variable.
2.
3.
4.

#### Context

Emails sent to customers have the incorrect date format and changing the System Locale settings does not updated the format.

#### Your Environment

* SuiteCRM Version used: 7.7.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 57.0.2987.133
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6, PHP 5.6 & Apache 2.4
* Operating System and version (e.g Ubuntu 16.04): Linux Centos 7.3

![image](https://cloud.githubusercontent.com/assets/23236967/25482750/f7d4e6ac-2b4a-11e7-9af8-c86557d8b757.png)

![image](https://cloud.githubusercontent.com/assets/23236967/25482796/2cfb8a52-2b4b-11e7-8ed3-869f37beed08.png)

![image](https://cloud.githubusercontent.com/assets/23236967/25482826/4e1f2cf2-2b4b-11e7-9028-858d25521ac0.png)

**Comment by sanchezfauste** [comment]
We have been investigating what causes this problem and we have noticed that it occurs in workflows that have set the option to run 'Only On Save'. The workflows with option run 'Only in the scheduler' do not present this error.

Debugging this problem we have detected that when the aowTemplateParser parses the email, specifically in https://github.com/salesagility/SuiteCRM/blob/master/modules/AOW_Actions/actions/templateParser.php#L38 are given two cases:

1. If the workflow is of type run only in the scheduler, the BeanFactory::getBean() function returns the bean by calling the retrieve method. In this case the datetime fields are in the format specified in the locale settings. So the issue is not present on this case.

2. If the flow is of type run only on save, the BeanFactory::getBean() function returns the bean it has in the cache ($loadedBeans of BeanFactory). This cached bean has the datetime fields using the MySQL format. That is why when the e-mail template is parsed the datetime type fields are in the wrong format.


We have developed a workaround consisting in that when the parse_template() function of aowTemplateParser requests the beans with the BeanFactory::getBean() method, the cache is not used to get the bean. So intead of search the bean on the cache and return the cached bean, the retrieve function is called as it would be if the bean was not found in the cache.

With this modification the format with which the fields of datetime type are displayed is correct.


This two commits implements this workaround:

https://github.com/sanchezfauste/SuiteCRM/commit/efa52e7de507e7916d04ef4e33ba8a924979d72e
https://github.com/sanchezfauste/SuiteCRM/commit/c030b45bc06e335b00e5be4b885a4392956a0327
