### ISSUE TITLE
/modules/Tasks/vardefs.php line 121

### ISSUE THREAD

**Issue by a277913835** [salesagility/SuiteCRM#3497]
/modules/Tasks/vardefs.php line 121
Is the LBL_PARENT_NAME label correct?

**Comment by pgorod** [comment]
I'm going to try and guess what you mean (you didn't explain much!)

You're saying that this piece of the vardefs...
```
        'parent_type' =>
            array(
                'name' => 'parent_type',
                'vname' => 'LBL_PARENT_NAME',
                'type' => 'parent_type',
                'dbType' => 'varchar',
                'group' => 'parent_name',
                'options' => 'parent_type_display',
                'required' => false,
                'len' => '255',
                'comment' => 'The Sugar object to which the call is related',
                'options' => 'parent_type_display',
            ),
```
... doesn't seem to make much sense because it labels the `parent_type` as if it was a `parent_name`.

Well, then the actual label definition reverts the situation:

```
/var/www/html/modules/Tasks/language/en_us.lang.php:108:  'LBL_PARENT_NAME' => 'Parent Type:',
```
So, in a twisted way, it is correct :-). Of course changing the label name to `LBL_PARENT_TYPE` in both places would be more correct, but I'm not sure anyone is going to take the time to make that change...

**Comment by horus68** [comment]
@pgorod I can speed solve this in the language files available on Crowdin, so we don't have to wait for code changes been approved. But would prefer a proper fix:
1- Create a PR to fix the code.
2- In that PR place a mention to me requesting a temporary fix on the language side for Crowdin. 
Then "when PR is merged" the language fix I can also make it synced again with the language on Github.

Else someone could fix this later without any relation to this issue and breaks our language fix!

**Comment by pgorod** [comment]
With so much stuff delayed, I don't think it's worth pursuing this, I would just leave this as it is. Of course if anyone wants to do the PR, I'm not opposing it either...

**Comment by a277913835** [comment]
It's simple , just replace the LABEL and add a new LABEL in the language file then mark the old LABEL as compatible. Forgive my poor English.

**Comment by pgorod** [comment]
If it's easy, then you can do it yourself, right?

What would you gain? What is the actual problem you're feeling? This has absolutely no consequence. 

You're bothered because a small detail in the code readability could be improved, is that why you started this issue? I'm just trying to understand, it seems we're talking about different things...
