### ISSUE TITLE
Mark As Flaged/Unflaged isn't in 7.9 mail system

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3636]
#### Issue

The common function of IMAP is

Mark As Flaged/Unflaged

isn't in SuiteCRM 7.9 mail system yet. (in older version 7.8.x was and was very usefull)

![flag](https://cloud.githubusercontent.com/assets/5773777/26719371/89afd50a-4784-11e7-9b62-7a7c52c2a228.png)

#### Expected Behavior

User will available to mark the emails as flaged/unflaged

**Comment by Dillon-Brown** [comment]
Hi @Mausino Mark as Flagged/Unflaged has already been raised here: #3616 as a high priority issue. Please edit the title to Mark As Read/unread or update the other PR and close this one. Thanks.

**Comment by Mausino** [comment]
@Dillon-Brown i know.. but @daniel-samson did the patch only for Relate to, Reply To All and Forward functions. 

There is nothing about Read/Unread function nad flag function is not explained good.

Do you want that i close this ticket or i will rewrite the old one that i remove the text about flag part ?

**Comment by Dillon-Brown** [comment]
@Mausino It's better to have the issues as separated as possible instead of having them all in a single issue. 

I would remove the "Mark As Read/Unread" from the other PR and keep it here. Or alternatively you could separate them further and make a new PR for "Mark As Read" and make this one just for "Mark As Flaged/Unflaged".

**Comment by Mausino** [comment]
@Dillon-Brown ok...  I will do this as you wroted :)

**Comment by Dillon-Brown** [comment]
PR: #3648
