### ISSUE TITLE
Anyone can delete config.php by calling testinstall.php (7.9)

### ISSUE THREAD

**Issue by krzyc** [salesagility/SuiteCRM#3698]
#### Issue
Calling testinstall.php will delete config.php - no login required.

#### Possible Fix
Remove testinstall.php before releasing production version.

#### Your Environment
* SuiteCRM Version used: 7.9.0

**Comment by sergio91pt** [comment]
Can we please stop posting security vulnerabilities here, before contacting SalesAgility.
 There is actually an email for security, security@suitecrm.com. The devs should really consider having it on the README or the contribution guide, instead of buried on issue comments and forum posts.

This one is actually quite serious, as it can be used for RCE (tested it on the weekend - sucessfully installed a reverse shell). The file is present in all Github releases from atleast v7.7-rc.
On the suitecrm website the file is in the 7.8.4 and 7.9.0 zip files, but not in the 7.7.9 zip.

I would suggest using the same thing cron.php uses, so the Travis CI is not impacted:


    if (PHP_SAPI !== 'cli') {
        die('cli only');
    }

**Comment by samus-aran** [comment]
Updating all affected installers and packages.  LTS and 7.9.1 will include fix to remove file and Readme updated to include security process.

**Comment by sergio91pt** [comment]
This file was not patched: https://github.com/salesagility/SuiteCRM/blob/hotfix/testinstall.php
It is basically identical to the one in `tests/`.

**Comment by chris001** [comment]
@samus-aran 
Cleanest is just update the code in the file to exit if not running from cli.

**Comment by samus-aran** [comment]
@sergio91pt & @chris001 - Thanks guys updated now.
