### ISSUE TITLE
Map areas error

### ISSUE THREAD

**Issue by zoltan2017** [salesagility/SuiteCRM#3726]
Hi
I install suitecrm 7.9 to hosting1 and have error in map areas module "oops something went wrong"
I put api key. Other modules with map work perfect. In hosting2 install the same suitecrm 7.9 but all modules with map work ok.
Can you help me?

**Comment by pgorod** [comment]
Hi @zoltan2017 did you try asking for help on the [forums](https://suitecrm.com/forum)?

Here it's for developers to work on code, not for general help for users. If on the forums we come to the conclusion that this is a bug for everyone, not just a problem with your system, we can open an Issue here (hopefully with greater technical detail at that time).

If that's alright with you, please close the Issue here and open a new thread on the forums, stating your versions of everything (OS, database, web server, PHP, SuiteCRM). Thanks!
