### ISSUE TITLE
Issue when replying to email with email address population - 7.9.1

### ISSUE THREAD

**Issue by PhillyD1973** [salesagility/SuiteCRM#3782]
#### Issue
Upgraded system from 7.8.4 -> 7.9.1

When trying to reply to an email, rather than populating the from address with the address setup in my profile.  It is inserting the email address of the person who emailed me.

#### Expected Behavior
I would anticipate, when replying to an email, that it would insert the address that is setup within my profile

#### Actual Behavior
The from address is being populated with the address of the person who sent me the email (which should be in the from)

![image](https://user-images.githubusercontent.com/29067877/27503841-6603954e-584e-11e7-9e5c-86542c0d913f.png)

#### Steps to Reproduce

1. Open existing received email
2. Select reply

#### Your Environment
* SuiteCRM Version used: 7.9.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome (MAC) Version 58.0.3029.110 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL PHP 5.4
* Operating System and version (e.g Ubuntu 16.04): Unknown (hostgator)

**Comment by daniel-samson** [comment]
Hi @PhillyD1973 ,

I think this issue may be related to #3655, as it your screenshot has a plain from field instead of the dropdown. 
When I use the reply to in 7.9.2 I get the following:

![screenshot_20170704_140553](https://user-images.githubusercontent.com/12231216/27831476-cacad57e-60c2-11e7-8bbd-3c55486016f6.png)

So can you please verify that this is still an issue in 7.9.2?

**Comment by Dillon-Brown** [comment]
Closed due to inability to replicate / inactivity.
