### ISSUE TITLE
own saved filters under calls is missing - only Suite P

### ISSUE THREAD

**Issue by margoux** [salesagility/SuiteCRM#3784]
#### Issue

under calls, extended filter, I save a new filter with for example **calls sarah**. In Suite 7 and Suite R I find the filter under extended filter. In Suite P the filter selection is not available (select own stored filters). The problem is with Suite 7.8.5 and 7.9.1, only Suite P Theme.

![2017-06-20 21_48_05-calls suitecrm-filter](https://user-images.githubusercontent.com/23278690/27508610-510f8544-58e9-11e7-9397-e2353a5653a0.png)
![2017-06-20 21_49_41-suitecrm-filter-2](https://user-images.githubusercontent.com/23278690/27508609-510dd32a-58e9-11e7-9bd7-440f88369b89.png)

#### Steps to Reproduce

1. tested Suite 7 - my filter under calls works
2. tested Suite R - my filter under calls works
3. Suite P - 7.8.5 - my filter under calls not available
4. Suite P - 7.9.1 - my filter under calls not available

#### Your Environment

* SuiteCRM Version used: 7.8.5 + 7.9.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 59.0.3071.104 (64-Bit), Firefox Version 53.0.3 
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.6
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Dillon-Brown** [comment]
Issue is also present in meetings module.

**Comment by pgorod** [comment]
According to [this discussion](https://suitecrm.com/forum/suitecrm-7-0-discussion/16226-no-my-filters-button-on-calls-and-meetings) on the forums, this problem is present for both Calls and Meetings, on both v. 7.8.7 and on v. 7.9.6 (live demo). 

If I understand correctly, this confirms what was already known in previous versions (as expected, since the Issue didn't solve itself without any PR).
