### ISSUE TITLE
Email DetailView does not show recipient/sender-data

### ISSUE THREAD

**Issue by halest** [salesagility/SuiteCRM#4033]
#### Issue

Followup from @Dillon-Brown comment on #3919, emails do not show recipien/sender data
#### Expected Behavior

Show sender/recipient data
#### Actual Behavior

Empty fields

#### Steps to Reproduce

1. Open archived mail

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): sCRM 7.9.3
* Environment name and version (e.g. MySQL, PHP 7): MSSQL PHP7
* Operating System and version (e.g Ubuntu 16.04): Win Server 2008R2

**Comment by Mausino** [comment]
@halest this issue is also persist when you import email.. the recipient/sender data are not there... :)

**Comment by halest** [comment]
@Dillon-Brown I don't know about you guys but this does not fix it for me on already archived mails. I checked 10 of the 25.000 in our system and none of them showed sender/recipient

**Comment by Mausino** [comment]
@halest could i ask.. did you looked on emails which was imported or emails which was received by IMAP ? because if was showed the recipient/sender in received emails...

i think in imported emails this data will not exist.. we tried this code and it shows us the recipient/sender in received emails and after import are also to see in imported emails

but when this patch was not available.... it imported nothing for field sender/recipient and in older data will empty field forever :( 

Or i am wrong? @Dillon-Brown could exist some way how to imported emails put the sender/recipient data ?

**Comment by halest** [comment]
@Mausino I was looking at archived mails on an account record.
Looking in the Emails Module in the "live" inbox, that data is shown, but if I import it, only the sender name, but not the recipients are saved. And on the other previously imported 25k, no data is shown at all.

**Comment by Dillon-Brown** [comment]
@Mausino @halest Unfortunately already imported/archived emails will not have the "From" or "To" field populated. You would need to delete them and re-import with the fix.In regards to only seeing the sender name, I'm not able to replicate.

**Comment by Mausino** [comment]
@Dillon-Brown @halest when we send email in detail view of email is missing sender + recipient (the bcc. is showing) patch was applied and repair&rebuild system

![2017-08-03_1559](https://user-images.githubusercontent.com/5773777/28925799-3366ea68-7866-11e7-8d91-b84eb7f52fa5.png)

**Comment by bdragon28** [comment]
@Dillon-Brown The underlying issue here is that email fields need to be treated differently from both html and varchar fields, since the address portion looks to the html cleaner like an invalid HTML tag and gets stripped out, and then that cascades into the email address cleaner throwing out the mailbox name portion on the next save because the email address portion went missing.

I've been playing with a local workaround involving extending SugarBean::cleanBean() to ignore email fields, but I think the correct solution is to introduce a different field type for email fields that does the right thing (Email::cleanEmails() instead of SugarCleaner::cleanHtml() I guess?) and makes sure to turn on the htmlescape displayParam for display, so the email address and brackets display properly.
