### ISSUE TITLE
Saving outbound email account leaves me unable to send emails 7.9.4

### ISSUE THREAD

**Issue by Dillon-Brown** [salesagility/SuiteCRM#4057]
#### Issue

When saving an outbound email account through admin -> email settings without first sending a test email causes sending emails to fail.

#### Expected Behavior

Users should be able to save outbound email without first having to send a test email.

#### Actual Behavior

Emails fail to send. Further details by pgorod in issue #3841 

#### Steps to Reproduce

1. Admin -> email settings
2. Define outbound email account
3. Save settings without sending a test email
4. Compose and send an email

#### Context

High priority

#### Your Environment

* SuiteCRM Version used: 7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.5
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by jcloutz** [comment]
Version: 7.9.4

I had commented on #3841 and after farther investigation it seems that it isn't deleting the password, but it does refuse to send the email after saving the settings.

I verified in the database that the password is present in the outbound_email table, and can be changed (the hash changes).

However I get the following error.
1. Navigate to email settings.
2. Change Password
3. Test email successfully sends.
4. Save Settings
5. Refresh page
6. Test email fails to send.
7. Password hash is present in the database.

And
1. Navigate to email settings.
2. Change Password.
3. Save settings.
4. Refresh Page.
5. Test email fails to send.
6. Password hash is present in the database

**Comment by jcloutz** [comment]
I think i tracked down the root of the issue that I'm experiencing. The test email fails to send because the email password field is hidden and the modal script can't read the field.

https://github.com/salesagility/SuiteCRM/blob/master/modules/EmailMan/tpls/config.tpl on line 542.
Here it tries to parse the password into the request `&mail_smtppass=" + trim(document.getElementById('mail_smtppass').value` but it fails because there is no field to get the value of. You can see the resulting post request below from chrome.
<img width="906" alt="screen shot 2017-08-31 at 4 55 09 pm" src="https://user-images.githubusercontent.com/711186/29944999-7e1a109a-8e6d-11e7-9a75-93b93a1c7d8e.png">

https://github.com/salesagility/SuiteCRM/blob/master/modules/EmailMan/views/view.config.php line 118.
This may be the root of the problem? I haven't had a chance to run it in a dev environment.

If I have time i'll try it run it down a bit more.

**Comment by Dillon-Brown** [comment]
Unable to replicate on latest Hotfix. This issue has most likely been fixed by one of the many email PR's. Will re-open if I encounter it again or someone else can replicate.

**Comment by hilbaONE** [comment]
I get exactly the same error. I reinstalled 7.11.0.
As soon as I save the outbound email account, I get the error message and can no longer send emails!
