### ISSUE TITLE
Display users name who made the entries to the modules 

### ISSUE THREAD

**Issue by taragurung** [salesagility/SuiteCRM#4068]
#### Issue
I have posted this problem in Suite CRM forums too but cant get the proper response. I cannot find the name of the users who made the entries in the view list. What I mean is suppose a users added a contract details successfully. Now when a Administrator users view the contract list he must know who added that contract right. I cannot see that information.

#### Expected Behavior
Name of the users who made the entry to different modules like accounts or contracts or contracts or whatever is there.

#### Actual Behavior
I cannot find the name of user. There is one section call user manager but that sections can easily changed and does not fulfill the purpose.

#### Possible Fix
Whoever is logged in and when made an entry his  user name information also should be saved

**Comment by pgorod** [comment]
There's a `created by` field in almost every table in SuiteCRM. If you go into Studio, you can find it and add it to your screen layouts to make it visible.

You shouldn't open an Issue here just because you didn't get a reply in the forums. This is for bug reports and developer work... with a backlog of 671 Issues, it really doesn't help if people come here with basic queries about how the software works. Please close this Issue. Thanks.

And sorry if you didn't get any replies for so long, I know that is a problem and makes the SuiteCRM experience more complicated than it should be...
