### ISSUE TITLE
7.9.4 Wen you have problem with subscription of SecuritySuite it breaks the sending of emails

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4070]
#### Expected Behavior

When you have problem with subscription of SecuritySuite it breaks your email module.
You are not available send email because you have any email address which you can use. It is for personal + groups email accounts
![securitysuite](https://user-images.githubusercontent.com/5773777/28818636-f8a1beb4-76ab-11e7-9369-14fa58584fb2.png)

@eggsurplus  Could you let us know if emails are restricted by SecuritySuite ?

#### Actual Behavior

Email module will working without any restrictions

#### Your Environment

* SuiteCRM Version used: 7.9.4
* Browser name and version : Chrome 56.x 64bit
* Environment name and version MySQL 5.6, PHP 7.0.16:
* Operating System and version Win 10 home

**Comment by eggsurplus** [comment]
It looks like this is for a paid subscription for SecuritySuite and the subscription expired. Once the payment is made this error will go away, with the possible need of re-validating the license key. If the subscription is no longer needed then SecuritySuite should be uninstalled.

I don't expect that the expiration to cause this specific issue and will look into it, but addressing it with the options above will work in the short term.

**Comment by eggsurplus** [comment]
Also of note, I see this is for 7.9.4. A 7.9.4 version of SecuritySuite is being worked on right now.

**Comment by eggsurplus** [comment]
Wanted to confirm that I'm seeing the same issue in 7.9.4 even with an active subscription. Looking into the cause right now. It appears that a number of things have changed in the core code around this area recently.

**Comment by eggsurplus** [comment]
This happens without SecuritySuite Enhanced installed and it's due to a change in how email accounts are configured. To get the From populated go to the user record, edit, then go down to the Settings button underneath the email section. Then in the Mail Accounts at the top add a new account. Once saved the From will load.

**Comment by Mausino** [comment]
@eggsurplus ok.. my question is.. how it happend that before that licence was ok.. it worked.. but after next day, when licence was expired was broken.. Something must cause this change...  

Here are 2 options.. need something change in code of SuiteCMR or SecuritySuite... 

@salesagility @daniel-samson @samus-aran  could you look if has something with email module?

**Comment by daniel-samson** [comment]
@Mausino 

As of 7.9.x, the Email module is using the same views as any other module. Eg ListView, DetailView, and the EditView. There are some custom ACL rules for the list view which checks the access for contacts.

The screenshot you supplied is of the compose view, which essentially is the EditView view. So I can't see the issues relating to the SecuritySuite enhanced.

The new email client requires you to have an inbound email account, in order to send an email. Do you have an inbound email account?

**Comment by Mausino** [comment]
@daniel-samson yes, i have personal and also group account.. i fixed this issue that i setted the configuration again.. only the main point is.. why it happend when it was disabled the SecuritySuite..  it can be same problem for other users which are using this product :) 

when you see that this discussion doesn't have additional value to improve SuiteCRM, please close this ticket.
