### ISSUE TITLE
Can't find service in my quote previously created

### ISSUE THREAD

**Issue by general03** [salesagility/SuiteCRM#4090]
#### Issue
When I created "product" of type "service" I can't find it in my quote when I created a new line. 

#### Expected Behavior
The autocompletion have to show me my service in quote page inside service name field

#### Actual Behavior
The autocompletion is available with my "service" only for product and not for service in quote page

#### Steps to Reproduce
1. Create new "Product" type "Service"
2. Add the begin of this service name in the field service of quote page

#### Your Environment
* SuiteCRM Version used: Version 7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 59
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): ubuntu 14.04

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Can't find service in my quote previously created](https://trello.com/c/zw9mk2WK/216-cant-find-service-in-my-quote-previously-created)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by general03** [comment]
I would like to know when this issue will be solve ? 
(No answer on trello)

Thanks

**Comment by general03** [comment]
@Dillon-Brown can you tell me if a fix is in progress

**Comment by Dillon-Brown** [comment]
Hi @general03, this was determined to be a "suggestion" as opposed to a bug. From my understanding the "Product Line" in the quotes module should relate to both products of type "Good" and "Service" whereas the "Service Line" should be unrelated to the products module. 

This issue would need further discussion before we would be able to progress a possible solution on how to make this clearer / reduce confusion but ultimately I think "Service Line" not auto-completing with products of type service is intentional.

**Comment by general03** [comment]
Ok thanks for your explanation @Dillon-Brown
but why I can't use custom product name (without declare it) in the Product line ? Because the field it's clear after blur the input

**Comment by Dillon-Brown** [comment]
@general03 This would be due to "Product Line" in the quotes module being a relate field to the products module. You would need to create a product in the products module or you could add a service line and use that as a one off custom product.

When you are creating a quote you wouldn't want to have to modify details like part number, currency, price, etc. This should only need to be done once in the products module and then for any quotes you make in the future you already have those details ready to be autofilled in.
