### ISSUE TITLE
Edit/Detail view sync broken, tabs (fields inside) are repeating after 10th tab

### ISSUE THREAD

**Issue by itglaafs** [salesagility/SuiteCRM#4122]
Dear Sirs,

I have upgraded from 7.8.2 to 7.9.4 and I have similar issues with edit and detail view. All of my tabs from detail view are gone and there are just some of default, I presume from 7.9.4 setup. Before they were synced with edit view, this is now broken and it's not working. Buttons inside Studio/Detailview are not functioning.

Another issue is that if you have more then 10 tabs in any module, they start to repeat themselves from the 1st tab. All fields are the same in 11th as they are in 1st tab and so, 12th follows 2nd...

I tried to apply this fix and it only breaks the css style and connection to database, so it's even worse.

https://github.com/salesagility/SuiteCRM/pull/1948

Video explanation of problem:

https://screencast-o-matic.com/watch/cbjD2DlKwb

Best Regards,

Slaven.

**Comment by tsummerer** [comment]
+1

**Comment by seanfdo** [comment]
Hi Any resolution in this issue?

**Comment by td1984r** [comment]
The issue still exist on 7.11.18...the work around is to use panels after 10th tab, but if you want to create 11th tab it will just repeat again the fields that you have created in 1st tab.

**Comment by CrazyGoose** [comment]
Any solution to this.  This really needs to get fixed.

**Comment by td1984r** [comment]
The workaround is to split and use panels beneath each tab if you have more then 10 of them.


Sent from Yahoo Mail for iPhone


On Monday, November 1, 2021, 15:41, John Wreford ***@***.***> wrote:




Any solution to this. This really needs to get fixed.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kevconry** [comment]
Can't replicate in 7.13.2, 
when adding the 11th tab, it isnt the same as the 1st tab 
please re-raise or get in touch if you are still having this issue
