### ISSUE TITLE
AOR_Reports - "add to target list" not working for PARAMETERIZED reports with non-default values

### ISSUE THREAD

**Issue by mjd5** [salesagility/SuiteCRM#4123]
#### Issue
When I create a parameterized report of contacts with defaults (that for example displays 200 contacts), and change the parameter to non-default values (which may change the list to say just 5 contacts), then click "add to target list" the target list is populated with the original list (all 200) of the contacts, not the 5 contacts that are showing.

#### Expected Behavior
The "add to target list" should add the current set of parameterized records showing in the report (exactly like "export" on the parameterized report works...it will export just the current set of parameterized records showing on the screen.)

#### Actual Behavior
The original set of default records from the report is added to the target list no matter what parameterization is performed to filter the list of contacts.

#### Possible Fix
It should work exactly the same as export does, but instead of exporting the current set of parameterized/filtered records to a file, it should add them to the target list.

#### Steps to Reproduce
1. Create a report based on contacts module, and under report fields, select first name and last name
2. Under report conditions, select "salutation", tick the parameter box, and make it equal to "one of" and then select all salutations
3. Save the report and see it display 200 contacts let's pretend
4. Then change the parameter of salutations to display just "Dr" for example, and then see it display only 5 contacts let's pretend.
5. Select "add to target list" (and create a new list or add to an existing empty list, it doesn't matter)
6. View the target list and notice that there are 200 contacts in the list, NOT the 5 you expected!
7. (You can try to export the list to csv and see that sure enough, only the 5 you expected are exported)

#### Context
I filter contacts by state, by customer type, and by a few other factors by their associated Account status.  So I need to create a target list from reports, not from the contacts module search for example.
The number of combination reports I would have to create to achieve these goals is many, so it would be of medium priority

#### Your Environment

* SuiteCRM Version used: I've tried 7.8.2 and replicated the issue in 7.9.3, and also see it was mentioned a few years back at: https://suitecrm.com/forum/bug-tracker/5363-add-targets-to-target-list-by-report
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 60.0.3112.90 (Official Build) (64-bit) on OS/X
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.6.30
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.5 LTS

**Comment by ChangezKhan** [comment]
I haven't found the solution, but found the problem. In `AOR_Report.php` file, there is a function named `build_report_query_where`. In this function, it uses `$this->user_parameters` array, and by using that it generated `where` query. 

So, for other functionality like **Download PDF**, **Export**, etc. it is working fine. That means, this above issue is not being found. Because in these two scenarios, it is getting data in this `$this->user_parameters` array. 

But on **Add to Target List** scenario, this `$this->user_parameters` is blank, and due to that it is causing issue. 

Now, for right now, I couldn't exactly found the issue/solution. But if someone has an idea about why this is blank in **Add to Target List** scenario, it'll be big help.

**Comment by ChangezKhan** [comment]
Ok, there are couple of issues. 

First one is the function `requestToUserParameters` which sets the `$this->bean->user_parameter` is missing in `action_addToProspectList` function available in `controller.php` file of `AOR_Report` module. 

Second issue is, if we call this `requestToUserParameters` function, still it won't work, because it uses `$_REQUEST` global variable to set the `$this->bean._user_parameter`. So, when we do **Download PDF** or **Export**, in `$_REQUEST` variable we get all report condition values, but in **Add to Target List** scenario, we don't get any report condition values, as this function gets called from the **Popup** view of **Target List**. 

So, we need to find the solution for this.

**Comment by lazka** [comment]
I've created a PR for this: #473
