### ISSUE TITLE
Suite7 Theme - More tabs issue in 7.8.5 version

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#4126]
#### Issue

When i want to see more module tab on header, more tab stay under the notification icon.
![screenshot_1](https://user-images.githubusercontent.com/22373035/29409766-69ff1460-8356-11e7-820e-4e17d882b616.png)

#### Steps to Reproduce

1. Add more module tab to header in settings
2. See result
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.8.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 55.0.2
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04
* Theme: Suite7

**Comment by dursuntosun** [comment]
Any solution for this? I could not use more tabs in Suite7.

**Comment by Dillon-Brown** [comment]
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
