### ISSUE TITLE
Security: php code injection

### ISSUE THREAD

**Issue by bpabiszczak** [salesagility/SuiteCRM#4189]
https://yetiforce.com/en/news/blog/item/48-php-code-injection-using-an-image-in-popular-open-source-crm-systems-0-day

**Comment by sergio91pt** [comment]
Did you actually found a code injection vulnerability triggered by an uploaded image?

Your misleading and alarmist article doesn't make your company look good, specially considering it also makes CRM software.

There's no mention of any attempt at responsible disclosure to any vendor, of what you arguably classified as a critical vulnerability. Just because some software accepts user generated input, doesn't mean it is going to execute said input as code.

Note: I don't work for salesagility or any other CRM vendor. This is my personal opinion.

**Comment by bpabiszczak** [comment]
I don't care about reporting anything in your GitHub repository, I would rather not do it at all. Nobody is going to support or appreciate it here because we're Suite's direct competition. If, according to you, the error doesn't exist then all you gotta do is close the issue, I won't reopen it.

The problem is bigger though – we didn’t find one vulnerability in SuiteCRM, we found more than 30 verified errors and we will publish them every couple of days. The errors that only apply to SuiteCRM will first be emailed to the producer to give them some time to fix them; the problems that apply to all the systems we check will be published right away and we will send the producers links to a post on our website.

We're not a company that deals with security, finding vulnerabilities in SuiteCRM and many other systems [including our own] results only from the fact that these systems haven't undergone any security audits for years, otherwise we wouldn't have found 30 critical vulnerabilities in 3 days. If Suite did go though any security audits please show me the reports, I would like to know which audit companies we should avoid at all cost.

It's time to make people consider open source solutions safe. A few months of hard work is enough, then it gets easier.

**Comment by pgorod** [comment]
The nice way to report vulnerabilities is by email to security@suitecrm.com, not by opening a public issue.

Anyway, @bpabiszczak the question is: the ability to upload malicious files is a bad thing, to be prevented, of course, but not directly a threat. How are these malicious files executed? That's where SuiteCRM needs to be strong, not in the uploads. People can upload whatever they want as documents, attachments, etc., so it's not the images that are such an outstanding threat. (if I'm understanding things correctly, correct me if I'm wrong).

**Comment by gregsoper** [comment]
@bpabiszczak is a regular troll of the SuiteCRM project. He has been banned from the SuiteCRM forums and LinkedIn groups for consistently posting negative content in order to publicise his VTiger fork. He will probably end up being banned from here as well. 

The SuiteCRM project takes security very seriously. There is a published process for reporting security concerns which, had this hostile and malevolent person (@bpabiszczak) bothered to follow, would have enabled us to do this in a more measured fashion.

For the sake of all our users: 

- SuiteCRM is regularly security scanned by our enterprise customers. These include some of the world's largest companies in their fields. They use state-of-the-art, enterprise-class tools. If they are betting their business on open source, they make sure it's secure. Discovered vulnerabilities are reported to the project, fixed by the project and made available to all as security fixes.

- SuiteCRM is security and vulnerability scanned by a well-known and industry-recognised specialist third party  security/vulnerability testing partner. The project pays for this as part of our due diligence.

- SuiteCRM is security and vulnerability scanned on an ongoing basis by the product development team.

 Any and all vulnerabilities reported to the project are taken seriously and where verified, are  fixed by the project and made available as quickly as possible as a security release. Read back through the last few years to see the number of security releases we have done. We are not complacent about security.

Neither are we complacent about the reporting of this issue. We take substantial issue with the highly irresponsible, attention-seeking way it was reported, but we will do the right thing. We will triage and assess. If it is an issue, we will fix. We cannot comment further until we do the assessment.

We have however, in the interim, suspended @bpabiszczak from posting on this service too. 

**PLEASE NOTE**
On our Github home page regarding reporting security issues:

=============

Contributing to the project

**Security**


We take Security seriously here at SuiteCRM so if you have discovered a security risk report it by emailing security@suitecrm.com. This will be delivered to the product team who handle security issues. Please don't disclose security bugs publicly until they have been handled by the security team.

Your email will be acknowledged within 24 hours during the business week (Mon - Fri), and you’ll receive a more detailed response to your email within 72 hours during the business week (Mon - Fri) indicating the next steps in handling your report.

==========================

**Comment by gregsoper** [comment]
@bpabiszczak is a hostile and malevolent presence in the SuiteCRM ecosystem. He has already been banned from the SuiteCRM Community forums and the SuiteCRM LinkedIn group. He is now also banned from Github. We have no doubt he will pop up somewhere else, but hopefully users will be alerted to him when he does and treat his comments with the contempt they deserve.

His consistent motive for trolling is his hope that he can ride on the oxygen of publicity gained from attacking the SuiteCRM project. This thread is the latest manifestation of that. No doubt he gained a modicum of airtime from it. 

As we consistently state: The SuiteCRM project takes security seriously.

We passed this "Code Injection" vulnerability to the SuiteCRM product team. This is what they replied:

============================================
The tool used to come to this conclusion makes a lot of assumptions and provides too many false positives.

Providing good security is a multi faceted problem. SuiteCRM authenticates each request from a user,  It provides the mechanism for deciding what who is authorised to do an action, and It logs when someone attempts an action they are not permitted to do so. The responsibility remains of the administrator to provide SSL encryption and IPSec to protect against network attacks, and to implement an intrusion detection system (IDS), monitor potential security issues, using anti malware software etc.

What SuiteCRM is doing already:

- SuiteCRM already restricts the type of files which can be uploaded.

- SuiteCRM provides a public and private folder for uploads.

- SuiteCRM documents how to correctly install the web application.

- SuiteCRM already escapes SQL queries

- SuiteCRM provides security releases when and as they arise.

===============================================

As a coincidence, completely unrelated to this thread and with no fixes relating to this thread, a security release will be made in the next couple of days. It has been in development as part of our business-as-usual security practices and improves SuiteCRM security in numerous places. It has been in preparation for more than one month. We take security seriously.

**Comment by gregsoper** [comment]
https://suitecrm.com/suitecrm/blog/entry/php-code-injection-using-an-image-in-popular-open-source-crm-systems-0-day
