### ISSUE TITLE
listview looses preselected filters when adding columns (choose columns popin) 

### ISSUE THREAD

**Issue by lenz1979** [salesagility/SuiteCRM#4197]
#### Issue

it is not possible to use search-filters and the "choose columns" functionality combined.
if i search for a special accountname and then want to show some mor special columns with "choose columns"-popin the previously entered accountname (searchfilter) gets lost.

#### Expected Behavior

i want to be able to search for a special account (e.a. name) and show some more columns using the "choose columns" function

#### Actual Behavior

when using "choose columns" the search-filter are empty. 

#### Steps to Reproduce

1. Accounts-Listview - search by e.a. name
2. use "choose column" to add some columns in listview
3.now the account-filter is lost
4.

#### Your Environment

* SuiteCRM Version used: 7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chrome, but all browsers same 
* Environment name and version (e.g. MySQL, PHP 7): mysql,php7
* Operating System and version (e.g Ubuntu 16.04):debian 8

**Comment by JBrace1990** [comment]
+1. This makes it incredibly hard for users to dynamically change their view AND search for one of those columns.

It means that the column they want needs to be shown for everyone, and sometimes that's just not possible.

**Comment by JBrace1990** [comment]
To add more data to this:
This happens because of line 171 in /include/ListView/ListViewDisplay.php, inside of the "setupFilterFields" function.
`if(empty($filter_fields) || $this->mergeDisplayColumns) {`

Basically, if filter fields is ever setup, it doesn't display additional columns that the user selected.

There is also no way to overwrite this file outside of overwriting several other files.

**Comment by Mausino** [comment]
Before few weeks i added suggestion #4566

**Comment by Go2ClassPoorYorick** [comment]
I'm sure this bug could be considered more than low priority?

I can't really speak for any other company, but at least in the one I work for, we're forced to have a ridiculous amount of columns on screen in order to be able to use the columns for each department that our team uses: Some departments might need to sort by one column about incoming data, while another might sort by type of call or last contacted. 

Without persistent personal column changes, this has forced us to have too many columns on our default view, forcing users to scroll across the screen.

While seemingly small, it seems like this Quality of life feature would be worth the time to implement properly.

**Comment by lenz1979** [comment]
same here. our customers used this feature (Changing columns) very often but since new suitecrm this does not work correctly (looses filled filters).

**Comment by SoapJson** [comment]
we loose clients because of it.
It is often used. 
It's high priority!

**Comment by ubs-ua** [comment]
It's useful functionality, and really hard to fix this.

**Comment by JBrace1990** [comment]
Fix was in a comment by me on 12/14/2017. It just needs to be implemented.

**Comment by ubs-ua** [comment]
I tried it.
There were problems in the users module.
Need a normal fix.

**Comment by lenz1979** [comment]
this still does not fix the whole issue.
-->accountslistview: add custom row
-->open filter and use simple filter and search by name

this results in loosing the previously added row

in extended Searchfilter it seems to work now

**Comment by PedroErnst** [comment]
@lenz1979 

Yes that's true, it doesn't work on simple search. I didn't see an effective way to implement it.

I hope that using advanced search is not too much of a workaround.

This doesn't mean it won't get implemented at some point, but right now in the current release it only works on advanced search.

**Comment by pgorod** [comment]
@PedroErnst @Dillon-Brown then maybe we shouldn't close this issue, or maybe we need to open a new one for the part that is left to be done?
