### ISSUE TITLE
Update Check box field using Inline Editing display error "SQL Server error: Conversion failed when converting the nvarchar value 'on' to data type bit."

### ISSUE THREAD

**Issue by anhnhatuit** [salesagility/SuiteCRM#4270]
The cause raise issue "SQL Error" when update using Inline Edit for field type of checkbox
                if($('#'+ field).is(':checked')){
                    return "on";
                }else{
                    return "off";
                }
in the "getInputValue" function in path: "include/InlineEditing/inlineEditing.js". Because db type is bool but when update then set value for field is varchar. I've fixed in my project. Please fix above code to return 1 or 0 Instead return 'on' or 'off'

Environment
* SuiteCRM Version used: 7.8.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MSSQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by PedroErnst** [comment]
@anhnhatuit 

Cannot seem to reproduce this.

Added a custom, inline editable checkbox field to Accounts. Was able to inline edit it fine.

**Comment by Dillon-Brown** [comment]
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)

**Comment by pgorod** [comment]
A user on the Forums says she had to use this fix in 7.11.10...

https://community.suitecrm.com/t/inline-edit-of-checkbox-on-detail-view-doesnt-save-changes-suitecrm-7-11-10/71779/4
