### ISSUE TITLE
Small js issues after update to 7.9.6 (problem with compressed js files)

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#4371]
#### Issue

Many times we got small issues, which come back after upgrade of SuiteCRM.. the main part of issues are those which we fix by our-self.  if i asking developer why i still getting the answer

Fixed, is a problem with compressed js files...

Should be this issue with compressed js files fixed.. or can be do some procedure with them? 
If this ticked doesn't hit right place.. please let me know and i close it.

I am understand that compressing files is important to speed up page... 
 
#### Your Environment

* SuiteCRM Version used: Suite: SuiteCRM 7.9.6
* Browser name and version: Chrome 56.x
* Environment name and version: MySQL 5.6, PHP 7.1.9:
* Operating System and version: Win 10 Home

**Comment by Dillon-Brown** [comment]
Hi @Mausino, I'm not quite sure what issue you are encountering here. Could you be a bit more specific? normally when a javascript issue is fixed it gets included in (jssource/src_files) so that when running "Rebuild Minified JS Files" the jssource files are minified and replaces the old minified files.

**Comment by Mausino** [comment]
@Dillon-Brown thanks for your answer.. i will resend it to my developer.. if any questions from him, i put it here to better specific this ticket.
