### ISSUE TITLE
Small interface glitch : grey background flash

### ISSUE THREAD

**Issue by hubyhuby** [salesagility/SuiteCRM#4426]
In suite CRM 7.8.8, in several part of the CRM when loading there is a flash of 1/3 of a second with a grey background saying "SuiteCRM has been written and assembled by SalesAgility. The Program..."
Then the page display.
This flash is not very pleasant for the eye. But I guess we can live with (maybe not epileptics thought!)
My understanding is that it is the javascript in the link in the footer that shows up .

![display glitch](https://user-images.githubusercontent.com/26340942/31734530-474d3234-b43f-11e7-9165-8d72581f70e7.png)

**Comment by Dillon-Brown** [comment]
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
