### ISSUE TITLE
Email Quick Compose Hiding Confirmation Dialogs

### ISSUE THREAD

**Issue by joshuahilton** [salesagility/SuiteCRM#4427]
#### Issue

When selecting an email template, the confirmation dialog is hidden behind the main quick compose window.
![quickcomposewindow](https://user-images.githubusercontent.com/26759852/31751284-0ee46032-b4e1-11e7-9c0e-aee90ad614f1.PNG)

#### Expected Behavior

The confirmation dialog should be above the quick compose window

#### Steps to Reproduce

1. Click an email address to open the quick compose window
2. Select an email template

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.8.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):  Chrome Version 61.0.3163.100 (64-bit)

**Comment by Dillon-Brown** [comment]
Hi joshuahilton,

I'm unable to replicate this on 7.8.6. Have you tried clearing the cache?

**Comment by joshuahilton** [comment]
@Dillon-Brown Yes I have. Our users on tablets, desktops and laptops all experience the same issue. I'll try disabling the few addon modules we have installed and see if this makes a difference.

**Comment by joshuahilton** [comment]
@Dillon-Brown I installed a fresh instance of 7.8.5, and tested. The bug showed up in this version as well.

I then upgraded to 7.8.6 and the bug didn't show. I then disabled AJAX as it is disabled on our production site, and the bug occurred again. 

I enabled AJAX for the accounts module on our production site and sure enough, the bug went away and it started working as expected. So it would seem the bug is AJAX related.

We have experienced issues using AJAX so this is why we have turned this off for all our modules.

**Comment by Dillon-Brown** [comment]
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
