### ISSUE TITLE
Add ability for Scheduled Reports to only send emails when Report is not empty

### ISSUE THREAD

**Issue by isleshocky77** [salesagility/SuiteCRM#4432]
#### Issue

Allow for a Scheduled Report to specify not send out an Emailed Report if the Report contains no data (empty result)

#### Expected Behavior

Don't send out emails with a Report with no data

#### Actual Behavior

Receiving emails with a Report with no data

#### Possible Fix

Add an option to Schedule Report to tell it to send it conditionally, such as having specific data or any data

#### Steps to Reproduce

1. Create a Report with conditional Data Set
2. Schedule it to Send out an Email
3. Update the data so the Report is empty
4. Wait for an email with just headers

#### Context

Receiving empty emails every morning when really only want to receive them as alerts to specific data being present

#### Your Environment

* SuiteCRM Version used: 7.9.4

**Comment by pgorod** [comment]
I believe this would have to be an option, since in some cases it might be relevant to receive the empty report (to be notified that no records applied).

Maybe it could be a checkbox next to each recipient saying `Send even if empty`

![image](https://user-images.githubusercontent.com/15945027/31852606-6b165990-b672-11e7-9ccd-95e8f69cc84f.png)

Or possibly just a generic checkbox that would apply to all recipients.

**Comment by isleshocky77** [comment]
I think making it on the overall scheduled report is fine, rather than individually on the email, as it is just using a report, so you could just create other scheduled reports of the same report with it sending empty.

I also think you could go a little more advanced with it this way rather than just send empty or not. But could add other types of conditions for running the scheduled report. (i.e does it contains more than 5 records, does it have a record with a field equal to, etc).

**Comment by pgorod** [comment]
I think you are right, but that sounds like a Workflow. Instead of replicating the same sort of logic in several places, I am starting to think we could include this in the Workflow module, by making an action of running a report, which could be followed by an action of sending it by email (or any other action you might want).

I just looked in the Workflow module and found these options under `Workflow module` (on the top when you're creating the workflow):
- Reports 
- Reports Charts
- Reports Conditions
- Reports Fields

maybe this could be explored for uses like you were describing... I don't know.

**Comment by isleshocky77** [comment]
@pgorod I would agree, but then why have the Scheduled Reports module? Why add extra code and complicate it?

**Comment by pgorod** [comment]
I'm with you, the Scheduled Reports module would be dropped. I don't think it makes that much sense as an independent module, we already have Reports, scheduling their delivery should be an option within that module, not a separate one. 

I bet it's a separate thing for historical reasons - used to be sold as an add-on, probably.

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add ability for Scheduled Reports to only send emails when Report is not empty](https://trello.com/c/hyFEyxea/233-add-ability-for-scheduled-reports-to-only-send-emails-when-report-is-not-empty)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
