### ISSUE TITLE
PDF template issues

### ISSUE THREAD

**Issue by vic-t** [salesagility/SuiteCRM#445]
I played around with the PDF templates and created a test template for the contacts group. I just used the sample that was provided in the system and didn't change anything in it. 

When generating the letter, I can choose my newly created template and open the generated PDF file. However, the PDF is empty. 

Nothing is logged in _suitecrm.log_, but my **nginx** error log spits out the following error message: 

```
2015/09/06 22:03:00 [error] 515#0: *659 FastCGI sent in stderr: "PHP message: PHP Warning:
  opendir(/var/www/suitecrm/modules/AOS_PDF_Templates/PDF_Lib/tmp): failed to open dir: 
No such file or directory in /var/www/suitecrm/modules/AOS_PDF_Templates/PDF_Lib/mpdf.php on line 7506
PHP message: PHP Warning:  opendir(/var/www/suitecrm/modules/AOS_PDF_Templates/PDF_Lib/tmp): 
failed to open dir: No such file or directory in /var/www/suitecrm/modules/AOS_PDF_Templates/PDF_Lib/mpdf.php on line 7506" 
while reading response header from upstream, client: ::ffff:192.168.79.1, server: mycrm.org, 
request: "POST /index.php?entryPoint=formLetter HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "mycrm.org:8081", 
referrer: "http://mycrm.org:8081/index.php?action=ajaxui"
```

Since a PDF file is in fact provided, although empty, I assume that the purpose of the tmp folder is to provide the content to the PDF. Something fails here. All I can confirm is that the mentioned tmp directory indeed does not exist.  

**Update**

OK, I just went back to the contact overview to check something else. The PDF files are all there, in the history (why not under documents?) with the correct content. Which doesn't rectify the issue but might help clarify things. So all I do now is abort the download and get the PDF from a manual download. 

But then I stumbled on two more potential bugs. First, I believe the mime type is set wrong for the PDF download, it seems to be set to text/html. I can manually override this by forcing to open with a PDF viewer but that shouldn't be. Secondly, I now see that trying to generate a PDF file removes the fragment identifier from the URI in the browser. A page refresh will thus kick you back to the main page. 

Log that could point to the mime-type issue (maybe): 
`2015/09/06 23:08:22 [error] 515#0: *904 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: doc_type in /var/www/suitecrm/include/SugarFields/Fields/File/SugarFieldFile.php on line 153`
## 

[config]
Linux Server:
SuiteCRM 7.3.1 (fresh install, repaired and rebuilt)
Nginx 1.8.0
PHP 5.6.0
Windows Client:
Firefox and Chrome on Windows 7/10

**Comment by vladbar** [comment]
Hello vic-t ,

try creating a folder called tmp inside your PDF_Lib folder.  This should eliminate the "No such file or directory" error message and might solve the issue.

I am unable to reproduce this error and would like to ask you a few questions.

- which PDF viewer are you using;

- can you please give us the name of the PDF template that you use in order to create your custom template;

- have you made any changes to any pdf handling php files;

- are you logged in as administrator or regular user;

- how big is you PDF file (how many lines or pages does it have)

- is there any chance that you can provide a print screen of your custom pdf template or maybe list the variables that you use in this template.

Thanks!

**Comment by samus-aran** [comment]
Unable to replicate - if you still continue to have this issue please re-open and supply the additional information asked.
