### ISSUE TITLE
Print page - Suite7 link issue 

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#4546]
#### Issue

Using the Print button at the bottom, with Suite7 theme it gives URL of data instead of data itself.
![screenshot_1](https://user-images.githubusercontent.com/22373035/33018810-f1060b1a-ce08-11e7-91a2-506123e0d780.gif)

#### Expected Behavior

Should give only data
#### Possible Fix

Possible correction in Style.css
#### Steps to Reproduce

1. Use Print button with any modules
2. Will display URL instead of data
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.8.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 57
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04
* Theme: Suite7

**Comment by Mausino** [comment]
#1338 try to apply this patch..  it's working for me.. but i have those issues:

1. listview... it prints only first 2 columns... but i have more as 2 there... 
2. detailview.. it doesn't print subpanels
3. detailview prints very horryble

**Comment by dursuntosun** [comment]
When i try to apply #1338  patch, it does not change? it is important for me. How can i solve this issue for Suite 7 theme. There some fix for Suite P and Suite R theme, but not for Suite 7 theme.

**Comment by Dillon-Brown** [comment]
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)

*To note. this is still an issue in 7.10.x with the SuiteP theme. See issue #7465
