### ISSUE TITLE
Selecting all delegates in events module does not work

### ISSUE THREAD

**Issue by ndarr** [salesagility/SuiteCRM#4560]
#### Issue

When you are opening the delegates sub panel in an event and click on the checkbox in the sub panel header to select all records, nothing happens
#### Expected Behavior

All records should be selected

#### Actual Behavior

No records are selected only the checkbox in the sub panel header
<img width="229" alt="bildschirmfoto 2017-11-21 um 12 45 24" src="https://user-images.githubusercontent.com/14993570/33071007-2fba0f9e-ceba-11e7-940f-0d9556213084.png">

#### Steps to Reproduce

1. Create a new event
2. Add some delegates to the event
3. Click the checkbox in the sub panel header

#### Your Environment

* SuiteCRM Version used: 7.9.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari, Chrome
* Operating system: MacOS Sierra

**Comment by adminibt** [comment]
In addition to that: This works with 7.8.8 and SuiteR:

![grafik](https://user-images.githubusercontent.com/19223035/33391890-bd50efa4-d53a-11e7-8729-18573f67a711.png)

But there is another problem: When I change the order all checkboxes disappear:

![grafik](https://user-images.githubusercontent.com/19223035/33392004-0b65688c-d53b-11e7-9a8e-2344bb2b9648.png)


This also happens when I use the filter. The checkboxes are needed in case you try to find a delegate and modify his status. Again: This is the current behaviour in 7.8.8.

**Comment by barthalexander** [comment]
Hi,
what is the status quo?
Will this solution merged sometime?
The bug is still present in the Master Branch.

**Comment by Myddleware** [comment]
Hi,
First of all, thanks for SuiteCRM which is an great application.
I have upgraded my SuiteCRM from version 7.6.2 (with template Suite7) to version 7.10.11 (with template SuiteP). 
I have the same issue and the fix proposed doesn't seem to work anymore as the Suite7 template files have changed.
Could you propose another fix for the version 7.10, and if possible commit it to the master branch ? 
Thanks.

**Comment by pgorod** [comment]
@Myddleware this fix also includes changes for the current 7.10 theme, SuiteP. Are you sure it's not working? What happens?

**Comment by Myddleware** [comment]
Thanks for your quick answer.

When I click on the check box "checkallContacts", the check boxes of all delegates aren't checked : 
![image](https://user-images.githubusercontent.com/11330301/50973349-0bc0bb00-14bf-11e9-8cc0-d1b495e9a231.png)

I have the version 7.10.11:
![image](https://user-images.githubusercontent.com/11330301/50973378-25620280-14bf-11e9-921b-4ddbaf45b129.png)

Please let me know if you need more detail.
Thanks.

**Comment by Mausino** [comment]
@Myddleware please try to apply this patch https://github.com/PedroErnst/SuiteCRM/commit/880ed7b28cc3fc9bdc32bdc3f4ab0835480eaa84 and should it work

**Comment by J-Light** [comment]
Any progress on this issue?

**Comment by Myddleware** [comment]
Hi,
Sorry, I should have reply sooner. 
I have quicky tried  this patch : PedroErnst@880ed7b . But this patch wasn't done on my SuiteCRM version (7.11.0) and the files has been changed. So I tried to apply the patch without success. But I did it quickly so not sure the problem comes from the patch ;)
So we still have the problem but we have other priorities for now so I didn't took more time to work on it.
Thanks for your help.

**Comment by Dillon-Brown** [comment]
Removed the fix proposed label as this still needs a fix. The closed PR #4643 should work but it's more of a hacky workaround than a proper fix.

**Comment by sravanitedla** [comment]
HI Team, Any update on this .. waiting for the fix .. tried the suggested changes as per 4643 but it did not work .

**Comment by PedroErnst** [comment]
The above PR should fix the issue. If anyone gets a chance to test it, let me know how it went. Thanks.

**Comment by Mac-Rae** [comment]
Working in 7.12

**Comment by Myddleware** [comment]
Thanks @Mac-Rae
