### ISSUE TITLE
Modern deployment options

### ISSUE THREAD

**Issue by skynet** [salesagility/SuiteCRM#461]
Are there any efforts on implementing automated installation and updating. For example, Wordpress, as a well designed php solution, can be installed automatically using (Ansible playbooks)[https://github.com/ansible/ansible-examples/tree/master/wordpress-nginx]. Wordpress also has a wp-cli command-line interface: https://github.com/wp-cli/wp-cli
Any modern platform would provide such options. Also see https://about.gitlab.com/downloads/ (Ruby)

**Comment by ghermans** [comment]
:+1 this would be a great feature for the LTS release.

**Comment by gunnicom** [comment]
+1

**Comment by vogelap** [comment]
+1

**Comment by chris001** [comment]
:+1: the beauty of open source, much of the wordpress-nginx and wordpress-apache ansible playbooks could be reused and adapted to make suitecrm-nginx and suitecrm-apache

**Comment by vjaro** [comment]
:+1:

**Comment by skynet** [comment]
:+1:  Let me add another thumb-up, maybe we can get someone to reply

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Modern deployment options](https://trello.com/c/RUsTWwPT/178-modern-deployment-options)

**Comment by Dillon-Brown** [comment]
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Comment by pgorod** [comment]
I think everybody in this thread will appreciate knowing that @Abuelodelanada has created an Ansible role to install SuiteCRM in one command:

https://github.com/gcoop-libre/ansible-role-suitecrm

**Comment by chris001** [comment]
@skynet  
* Inside `.travis.yml` is the commands to install from the command line by calling a php based installer.
* A symfony console app by @adamjakab https://github.com/adamjakab/SuiteCRM/tree/console-installer for running admin commands from the command line.  He was going to make a PR as he stated in #944 , as soon as the `feature/codeception` branch #3600 will be added to not only `feature` but also to `master`, `hotfix` and `develop` - so that it actually runs the tests on the code, to prevent further code which fails tests from being merged.
