### ISSUE TITLE
Published API Docs for v8

### ISSUE THREAD

**Issue by isleshocky77** [salesagility/SuiteCRM#4634]
It doesn't appear that the swagger docs for v8 have been published anywhere yet or even documented on how to generate them.

I've also been able to find any PR or issue on actually using the new API for testing purposes.

**Comment by daniel-samson** [comment]
Hi @isleshocky77  

The swagger docs, are a work in progress. I have a pull request (#4619) with a half finished version of the swagger.json. I just has the urls at the moment. Since the new API will follow the JSON API Spec. We need to convert the schema from that specification into swagger version 3, so that we can fully support the JSON API using swagger.

As for testing, my pull request(s) uses codeception with unit and acceptance tests. see tests/api and tests/unit/lib.

**Comment by daniel-samson** [comment]
Update: Beta 3

My pull request has been merged into the Beta 3 release.

The swagger.json is available on lib/Api/v8/swagger.json. Currently, we do not have a admin panel for the [OAuth 2](http://oauth2.thephpleague.com/authorization-server/resource-owner-password-credentials-grant/) server. In order to authenticate, you need to create a client id with a secret in the oauth2clients table. we currently support the password grant. You may need to rebuild the .htaccess file before you access the resources. Please ensure that you meet the requirements in the composer.json file.

The OAuth2 entrypoint is in http://path-to-instance/oauth/access_token.
The swagger entrypoint is in  http://path-to-instance/v8/swagger.json
The json schema entrypoint is in  http://path-to-instance/v8/schema
The modules entrypoint is http://path-to-instance/v8/modules

See lib/API/v8/route directory for details.

Also I have an other pull request for supporting the notes and documents (see #4749)

**Comment by pgorod** [comment]
For future reference in case Google brings somebody here:

[Documentation for SuiteCRM REST APIv8](http://docs.suitecrm.com/developer/api/api-8/)

http://docs.suitecrm.com/developer/api/api-8/
