### ISSUE TITLE
[language] Hard coded messages in Surveys module

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#4646]
Some messages in these files are hard coded:

Question, Text, Type, New Question
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/tpls/detailsurveyquestions.tpl#L4-L13
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/tpls/editsurveyquestions.tpl#L4-L17

Add option
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/tpls/editsurveyquestions.tpl#L143

Responses, Surveys Sent, Distinct Surveys Sent
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/tpls/reports.tpl#L3-L14

Draft
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/vardefs.php#L51

Submit
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/vardefs.php#L124

Satisfied
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/vardefs.php#L132

Neither Satisfied nor Dissatisfied
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/vardefs.php#L140

Dissatisfied
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/vardefs.php#L148

Stars
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/views/view.reports.php#L187-L196

Module, Body, Border, Text
https://github.com/salesagility/SuiteCRM/blob/master/themes/SuiteP/modules/Calendar/tpls/settings.tpl#L194

Some labels without value:
LBL_SURVEYQUESTIONS_SURVEYQUESTIONOPTIONS_FROM_SURVEYQUESTIONS_TITLE

**Comment by likhobory** [comment]
The messages 'Hide responses' and 'Show responses' are also hard coded:
https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/Surveys/javascript/Survey.js#L9

Please pay attention to Survay module, almost half of the labels on the Edit View are not translatable!

![default](https://user-images.githubusercontent.com/5983672/36939594-80e24cf8-1f44-11e8-90ac-471444b7ee24.png)

**Comment by horus68** [comment]
@Dillon-Brown one more look into this one?

**Comment by Dillon-Brown** [comment]
@horus68 Will take a look and will also see if we can get all the other PR's you mentioned merged for the next release. Thanks!

**Comment by willrennie** [comment]
@Dillon-Brown worth a review?

**Comment by SinergiaCRM** [comment]
Hi,

Is there any update on this issue?

Thanks

**Comment by SinergiaCRM** [comment]
@jack7anderson7, @clemente-raposo, @johnM2401, @likhobory and @Dillon-Brown

We have detected that this change is generating an error as the CRM treats the LBL_DRAFT value as a text string and not as a label:

https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/vardefs.php#L51

It seems to work since when the LBL_DRATF value is not found in the list associated with the field, the first result of the list is returned, which in this case is Draft.

We think you should revert the change and leave the value 'Draft'. Also, we think the LBL_DRAFT tag can be removed from the language file, as it is not used elsewhere.
