### ISSUE TITLE
Filter button not working for each module in search result (global basic search)

### ISSUE THREAD

**Issue by bmd-benita** [salesagility/SuiteCRM#4827]
#### Issue

When I searched data using global search, I saw the filter button in each module.
But, when I clicked the button, there was no response. And, there was javascript console log error from browser's developer tools.

#### Expected Behavior

The SuiteCRM should display a search form and user could filter the search result for related module.

#### Actual Behavior

There was a javascript console log error.
`Uncaught ReferenceError: listViewSearchIcon is not defined
    at HTMLAnchorElement.onclick`

#### Steps to Reproduce

1. Search something using global search
2. SuiteCRM would display search result that categorized by modules available. 
3. Click the filter button
4. No response after button has clicked and it produce error in JS console log.

#### Context

We have requirement from our organization that need us to customize this feature (priority medium to high). We hope that you can help us to fix this bug. 

#### Your Environment

* SuiteCRM Version used: 7.8.5
* Browser name and version: Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7, MariaDB 10
* Operating System and version (e.g Ubuntu 16.04): Ubuntu Xenial64

**Comment by gunnicom** [comment]
Can you clear the browser cache, and do a quick repair in Suite. Sometimes that helps.

**Comment by bmd-benita** [comment]
I have cleared the browser cache and do a quick repair. But, still doesn't solve the error.

**Comment by PedroErnst** [comment]
Can confirm this happens for me too. Thanks for bringing it up.

I'm looking into it.

**Comment by PedroErnst** [comment]
I'm just looking at the code and I'm not quite sure that the expected behavior is actually for the filter to work on this search result. Can anyone confirm that this has actually worked in the past?

Otherwise I am inclined to think that the problem is that those two buttons (filter and column chooser) are showing in this view at all. They don't show in the advanced view, and the JS for the filtering function doesn't seem to be compatible with multiple instances of search result list showing simultaneously.

But please let me know if you have seen these two buttons working on this view in a previous version.

**Comment by sanjaykumar2338** [comment]
![OnPaste 20211231-224015](https://user-images.githubusercontent.com/15665281/147833587-537b81bc-d372-4a0f-af37-2b45d9f1aa0e.png)

I am getting the same issue ? how to resolve it

**Comment by rahunak** [comment]
+1
