### ISSUE TITLE
Inline Editing on Dropdown - Blank Values after saving Edit

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#492]
This seems to occur when editing a Dropdown that has an "item name" that is not the exact same as the "Display Name" 
i.e Value_1 as Item Name and value 1 as Display Name

Initially, it will show a blank value when loading Detail view. If you then Inline edit, it will change + save the correct value, but refreshing the page will show it as blank again. 
If you start Inline Edit, but then cancel your changes, it will show the previously saved value as normal.

**Comment by Mausino** [comment]
Yes, 

i have same issue, if  are you edititing the dropdown via inline edit function on detailview or listview layer, it shows you value after save (brier icon), but after refresh, the value isn't there (only blank field)

The normal (usual) edit via editview layout works fine, it saves you value in dropdown field :)

Miky

**Comment by ventoh** [comment]
I confirm this issue. The problem is related to the value field. If the dropdown is changed via Inline Editing on ListView then the value stored in database is those of the label not the value self.
Example:
if i have a custom field "In_Progress" with label "In Progress", when i change it via ListView thru Inline Edit then in db is stored  "In Progress" not "In_Progress". So the search also not working and the Edit View show a blank field.

**Comment by Mausino** [comment]
@samus-aran @gymad could you help us ?

**Comment by Mausino** [comment]
We tested and it's working great :) Thanks :+1:

**Comment by EZS-JD** [comment]
Is this being implemented in an updated release?
