### ISSUE TITLE
Subpanel select not working in 7.8.11 and 7.9.10

### ISSUE THREAD

**Issue by eggsurplus** [salesagility/SuiteCRM#5028]
To test, open an Account and in the detail view go down to a subpanel. Pick a subpanel such as Bugs and open. Choose Select. In the popup click on a row to select (instead of the checkboxes). The popup will disappear, but the selection is not loaded in the subpanel.

Reload the page and the selection still does not show.

Tested in Firefox 57 and Safari on new installs of SuiteCRM 7.8.11 and 7.9.10.

**Comment by edmondklai** [comment]
I had a similar issue with 7.9.10.  When working with security group, I have the role and security group created, but role failed to be added to the security group.  Tested in both Chrome and Firefox. 

**Expected behavior**
Role should be added to security group

**Actual behavior**
Pop-up window disappear and role not added

**Steps to reproduce**
create a security group in security group module
create a role in role management module
select the newly created group
expand roles subpanel
click select
click the role

It cannot use the checkboxes because it is not available in this pop-up window.

**Comment by eggsurplus** [comment]
Now that you mention it, I'm having this issue in 7.9.10 as well. A clean install of 7.9.4 does not have this issue.

**Comment by eggsurplus** [comment]
7.9.9 works as expected.

**Comment by pgorod** [comment]
I confirmed this on 7.8.11.

**Comment by edmondklai** [comment]
I tested this in 7.10RC and it didn't work.

**Comment by pgorod** [comment]
@edmondklai interesting that 7.10 RC works for me, but not for you. What is your OS / PHP version?

Mine is Ubuntu 16.04, PHP 7.0

**Comment by eggsurplus** [comment]
Awesome! Thank you.

**Comment by pgorod** [comment]
I confirm the fix works in 7.8.10 (I applied it manually, I didn't install the new release).

**Comment by edmondklai** [comment]
@pgorod I am running docker on ubuntu server 16.04.3 and PHP 7.1

**Comment by eggsurplus** [comment]
Any idea when the update will be available on SourceForge?

**Comment by Dillon-Brown** [comment]
Hi @eggsurplus, v7.8.11 and v7.9.12 have now been uploaded to SourceForge. Thanks!

**Comment by fmojo** [comment]
Hello, all.

I am having the exact same problem with version 7.6.10

Changes to the following 2 files does not work for me (and my file is an older copy):
https://github.com/salesagility/SuiteCRM/commit/98bd9f67bef60fa1ddaddf407a7ae9a4053a6580

I tried all repairs, clear cache, permissions are confirmed correct, etc. 

I did a few upgrades back to back so I can not be certain the issue started in 7.6.10, the problem may have started with the upgrade to 7.4.4

Our team can't "select" any options from popups when adding relationships.  For example, we can't relate/select contacts to opportunities, contacts to accounts, etc.

All sub panels are not working properly.  The popup seems to work, select seems to work, window goes away and then nothing happens.  There are no errors in logs.

Please help! :(  

Thoughts?

Thanks

Joe

**Comment by eggsurplus** [comment]
Are you able to keep upgrading to the latest versions on a test instance and see if that does the trick? It doesn't happen on the latest releases. If it still does for you after upgrading then I wonder what customizations may be conflicting with that logic.

**Comment by fmojo** [comment]
I can't go any further with upgrades; from the upgrades available.  The next upgrade seems to be to 7.8.17 and upgrade wizard complains of php version not meeting requirements.  Is there another upgrade available that supports php 5.3.3 or am I screwed?  

Is there a closer upgrade I can try that is next after 7.6.10?

On this server it's an older CentOS and I have latest OS updates and latest PHP available for OS installed on the machine.  How do I "downgrade" Suite or otherwise keep 7.6.10 and go about troubleshooting the issue?

**Comment by eggsurplus** [comment]
I highly suggest moving away from 5.3. Too many issues and vulnerabilities on it and not supported anymore. Plus, you get a huge performance benefit if you move all the way up to 7.

7.9.16 still allows PHP 5.3 to be used.

**Comment by fmojo** [comment]
We are in the process of moving to a new Ubuntu server and PHP 7.  In the meantime we have moved to production with 7.6.10 before this bug was identified. 

Is there an upgrade file available for 7.6.10 to 7.9.16?

Thanks!

**Comment by eggsurplus** [comment]
It complains, but you can opt to keep installing. The min version for 7.8.17 is set to 5.3.0.

**Comment by fmojo** [comment]
I thought it stopped me from continuing.  I will try again.

**Comment by fmojo** [comment]
Upgrade to 7.8.17 complete.  

Problem still exists.  Strange.

Moving on to 7.8.17 upgrade now.

**Comment by fmojo** [comment]
Upgrade to 7.9.16 successful!

It's painfully slow...I know it will be faster with PHP 7 and upgraded mariadb, however, is there anything I can do to make it faster?

Is there any caching you may recommend?

The older 7.6.10 is running in production and I am testing 7.9.16 now in sandbox.

Is there a theme I can download that is similar to Suite R?

Thanks!

**Comment by fmojo** [comment]
Prolem is fixed after upgrade to 7.9.16.  :)

I can't deploy the Suite P theme as I have reviewed with team and they all don't like it.  Are there any other themes?  

Thanks!

**Comment by fmojo** [comment]
I would like to use Suite R so I have turned it on.  The issue still persists. 

Problem goes away when I set theme to Suite P.

**Comment by horus68** [comment]
@fmojo for questions, requests or problems related to your install, please use the forum.
Github should be used only for system bugs. 
https://suitecrm.com/suitecrm/forum/index
Note: SuiteR is not an option for your system anymore.

**Comment by sameekshaagrawal** [comment]
hi json i am getting same issue that select all button is not working in 7.8.2 ,can you provide the solution for this issue.

**Comment by eggsurplus** [comment]
You will need to upgrade to the latest version of SuiteCRM for the fix. You can stay on 7.8 and grab 7.8.30 if you do not want to go to 7.11.

**Comment by sameekshaagrawal** [comment]
Can we fix it on only 7.8.2?

**Comment by eggsurplus** [comment]
Feel free to. It is open source. You'll need to find the fix in the latest release and merge it in.

**Comment by sameekshaagrawal** [comment]
Can you let me know how to do that which file we need to change.

**Comment by eggsurplus** [comment]
I do not have that info. Sorry.

**Comment by sameekshaagrawal** [comment]
In which version it is resolved

**Comment by pgorod** [comment]
Try these changes
https://github.com/salesagility/SuiteCRM/commit/98bd9f67bef60fa1ddaddf407a7ae9a4053a6580

**Comment by sameekshaagrawal** [comment]
it is not working , as i am having issue with select all button in subpanel
popup.

**Comment by pgorod** [comment]
Attempting a fix manually is harder than upgrading. There are hundreds of reasons to upgrade: bug fixes, security fixes, compatibility with newer PHP's (which add performance and more security).

So my suggestion is to upgrade to the latest instead of trying it manually. I can't give you extended technical support to get something working, when we already fixed it in the product. I'm sure you'll understand.
