### ISSUE TITLE
Layout editor broken in module builder 7.10-RC

### ISSUE THREAD

**Issue by jamiemurray** [salesagility/SuiteCRM#5055]
#### Issue
Unable to edit layouts on module builder. 

#### Expected Behavior
When clicking the edit or detail view layout on module builder, the layout should appear to be edited. 

#### Actual Behavior
A message is displayed after clicking on "Edit View" or "Detail View" within module builder:  "An error has occurred".
The following is present in suitecrm.log:
Sun Jan 28 17:39:11 2018 [3694][1][FATAL] Exception handling in /usr/share/nginx/suitecrm/include/MVC/Controller/SugarController.php:402
Sun Jan 28 17:39:11 2018 [3694][1][FATAL] Exception in Controller: UndeployedMetaDataImplementation: view definitions for View editview and Module Claim are missing
Sun Jan 28 17:39:11 2018 [3694][1][FATAL] backtrace:
#0 /usr/share/nginx/suitecrm/modules/ModuleBuilder/parsers/views/GridLayoutMetaDataParser.php(96): UndeployedMetaDataImplementation->__construct('editview', 'Claim', 'S75')
#1 /usr/share/nginx/suitecrm/modules/ModuleBuilder/parsers/ParserFactory.php(89): GridLayoutMetaDataParser->__construct('editview', 'Claim', 'S75')
#2 /usr/share/nginx/suitecrm/modules/ModuleBuilder/views/view.layoutview.php(107): ParserFactory::getParser('editview', 'Claim', 'S75')
#3 /usr/share/nginx/suitecrm/include/MVC/View/SugarView.php(207): ViewLayoutView->display()
#4 /usr/share/nginx/suitecrm/include/MVC/Controller/SugarController.php(432): SugarView->process()
#5 /usr/share/nginx/suitecrm/include/MVC/Controller/SugarController.php(375): SugarController->processView()
#6 /usr/share/nginx/suitecrm/include/MVC/SugarApplication.php(109): SugarController->execute()
#7 /usr/share/nginx/suitecrm/index.php(52): SugarApplication->execute()
#8 {main}

#### Steps to Reproduce
1. Create a new package within Module Builder
2. Create a new module within the package
3. Add some fields 
4. Access the detail view layout and edit it
5. Try and access it again - Error

#### Your Environment
* SuiteCRM Version used: 7.10 RC
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 57.0.4 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7):  MariaDB-5.5.56 PHP 7.1.13
* Operating System and version (e.g Ubuntu 16.04): CentOS 7

**Comment by goingsmart** [comment]
Have applied the FIX #5055 but still getting Following ERROR.

Using 7.10 RC Linux CentOS7 PHP 7.2

Using STUDIO attempting to change ACCOUNT Module Dashlet ListView.

Can move fields around but SAVE & DEPLOY gets ERROR "An Error has occurred". Since this is a new install problem could be my platform (e.g. missing PHP 7.2 extension or wrong CHMOD. The ERROR LOG HAS:

Uncaught Error: Cannot access protected property DeployedMetaDataImplementation

[19-Jan-2018 22:54:59 UTC] PHP Fatal error: Uncaught Error: Cannot access protected property DeployedMetaDataImplementation::$_history in /modules/ModuleBuilder/parsers/views/DashletMetaDataParser.php:193
Stack trace:
#0 /modules/ModuleBuilder/controller.php(805): DashletMetaDataParser->handleSave()
#1 /include/MVC/Controller/SugarController.php(523): ModuleBuilderController->action_dashletSave()
#2 /include/MVC/Controller/SugarController.php(491): SugarController->do_action()
#3 /include/MVC/Controller/SugarController.php(465): SugarController->handle_action()
#4 /modules/ModuleBuilder/controller.php(108): SugarController->process()
#5 /include/MVC/Controller/SugarController.php(373): ModuleBuilderController->process()
#6 /include/MVC/SugarApplication.p in /home/patientpathsnet/public_html/beta/modules/ModuleBuilder/parsers/views/DashletMetaDataParser.php on line 193

STUDIO Labels, Fields, and Layouts WORK OK, except Layouts SuiteCRM Dashlet and PopUp View get posted ERROR.

This condition exists for multiple Modules.

**Comment by e-reeley** [comment]
Hi @goingsmart 

I'm sorry for the late response.

I just had a read of your error log and I believe that these 2 links may help you out:

The first is the [forum](https://suitecrm.com/suitecrm/forum/suitecrm-beta/17411-change-dashlet-error)  which discusses a similar error.
The second is FIX [#5086](https://github.com/salesagility/SuiteCRM/pull/5086) which is also mentioned in the forum andseems to be the fix for the issue that you are seeing here.

These will be added in to the next release, however, please add them in if you would like to resolve the issue before :)

Thanks for raising the issue!
