### ISSUE TITLE
Ellipsis with 5 dots in language files

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#5074]
#### Issue

There are some strings using 5 dots  `.....` for punctuation mark instead of an Ellipsis (typically three, such as `…`). There should be a consistency on this

See modules/Calendar/language/en_us.lang.php

    'LBL_LOADING' => 'Loading ......',
    'LBL_SAVING' => 'Saving ......',
    'LBL_SENDING_INVITES' => 'Saving & Sending Invites .....',

https://github.com/salesagility/SuiteCRM/blob/master/modules/Calendar/language/en_us.lang.php#L106-L108

If looking for consistency on Ellipsis usage in language files...
- There is a lack of consistency as some files uses 2 or 3 dots for an ellipsis
See /modules/ModuleBuilder/language/en_us.lang.php : 
```
    'LBL_AJAX_LOADING_TITLE' => 'In Progress..',
    'LBL_AJAX_LOADING_MESSAGE' => 'Please wait, loading..',
```

but in the same file, just 3 lines above, there are 3 dots Ellipsis in use:
```
    'LBL_AJAX_LOADING' => 'Loading...',
    'LBL_AJAX_DELETING' => 'Deleting...',
    'LBL_AJAX_BUILDPROGRESS' => 'Build In Progress...',
    'LBL_AJAX_DEPLOYPROGRESS' => 'Deploy In Progress...',
```

- You can also find spaces used before ellipsis as in 
`'LBL_SAVING' => 'Saving Spots ...',`

#### Expected Behavior

Normal Ellipsis (with 3 dots)

#### Context

To avoid alerts when translating to other languages as almost all uses 3 dots ellipsis
![5dots](https://user-images.githubusercontent.com/3055443/35681597-c4edd892-0755-11e8-80d6-0f166b8926e2.png)

**Comment by PedroErnst** [comment]
I've made all of the ellipsis have exactly 3 dots, which seems to be the standard.

There was also the question of whether there should be a space between the last word and the dots, and a quick search told me that this is mostly a matter of preference, but since the vast majority of cases in our language files have no space, I went and changed the 15 or so cases in which there was a space.

So now they should be consistent everywhere.
