### ISSUE TITLE
Your password has expired

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#5166]
#### Issue

related to the closed issue #4639 but with some differences.
The message `Your password has expired. Please provide a new password.`  keeps showing in 7.10.RC2. This is a system test, plain stock and upgraded from several versions before. The issue started with 7.10 and its not gone. The password is not generated by the system.

#### Expected Behavior

There are 2 problems:
1- It should'n happen at all. Password expiring should not be a default setting.
2- If you want this to show for expired passwords then the menu should be visible without allowing to see the admin contents as you can see the "recent viewed" menu.

#### Possible Fix

There should be a message displayed when the admin first login to say: 
`please go to Admin / Password Management and change: "System-Generated Password Expiration" to None or else you will have to create a new password each time you login. `
You see my point!
Why use Password Expiration ON by default?!

#### Actual Behavior

```
Please provide a new password.
Your password has expired. Please provide a new password.
```
![2018-02-09 22_10_58-suitecrm php7](https://user-images.githubusercontent.com/3055443/36052696-9ca075ec-0de6-11e8-8f1e-6530c8157e14.png)
#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Windows 10 32bit - Chrome / Firefox
* Environment name and version (e.g. MySQL, PHP 7): apache 2.4.18 / PHP Version 7.0.11 / mysql 5.7.17
* Operating System and version (e.g Ubuntu 16.04):

**Comment by davenz** [comment]
Same behaviour observed here in the full 7.10 release, under a similar setup scenario (test system upgraded directly from 7.9.8, which itself was a fresh install). No third-party themes are active nor any modules loaded.

Passwords are not system generated.

Ubuntu 16.04 Server with a stock LAMP stack is the underlying platform.

**Comment by Landver** [comment]
The same problem. Appeared after upgrade from 7.8 to 7.10 few days ago.
Also I can't turn that feature off, because few settings are missing from 'Password Manager' page
![1](https://user-images.githubusercontent.com/15925657/37086937-8e38d4fc-2201-11e8-89fc-9f6850b5b1f6.PNG)

Before typing that message:

- I used `chown www-data:www-data -R /var/www/suitecrm`
- Also I tried to replace `suitecrm/modules/Administration/PasswordManager.tpl` and `PasswordManager.php` with the same files from 'master' branch of GitHub.

But nothing changed.

I do not use any custom theme.
Version 7.10

**Comment by stancel** [comment]
We are experiencing this same behavior since upgrading to SuiteCRM version 7.10. In the meanwhile to prevent the passwords from expiring on any integration users I have just been setting the users.pwd_last_changed to a future date (6 months in the future). Hopefully there will be a more permanent/appropriate fix soon.

**Comment by Landver** [comment]
"setting the users.pwd_last_changed"
what are you talking about? That was some setting in database or what?

**Comment by rholighaus** [comment]
I have created pull request #5642 that should fix this bug by adding a condition that would check for expired passwords only if the password was system generated. This is in line with the settings panel.
