### ISSUE TITLE
MS Edge: The color of the ticks is allways green , regardless of the Email status (ver.7.10-RC-2)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5174]
MS Edge:
![default](https://user-images.githubusercontent.com/5983672/36066033-5c5cd5d8-0eb4-11e8-99ca-6b3f5e9239fd.png)

The same ListView in the FF or IE11:
![default](https://user-images.githubusercontent.com/5983672/36066058-8d49f2ca-0eb4-11e8-820e-9c58a29710a3.png)

**Comment by daniel-samson** [comment]
I am able to replicated this issue. The ticks work on edge 14 however, on edge 15 and above this issues occurs. 

![edge17](https://user-images.githubusercontent.com/12231216/36838201-7463d1c8-1d36-11e8-9a29-501949728865.png)


It seems to be a rendering issue in windows instead of a css issue. Edge is correctly selecting the css selector. other browsers such as firefox have the same issue on windows.

The solution would be to use an icon instead, so that it is not using the unicode value.
