### ISSUE TITLE
Changes inside include/SubPanel done in v7.8.10 broke completely the SubPanels in Suite7

### ISSUE THREAD

**Issue by hertell** [salesagility/SuiteCRM#5189]
After upgrading to v7.8.10 the SubPanels are completely blank, i.e. in the Contacts-section there is no Create Button, no row showing headers or navigationg-button. In other words, absolutely nothing is visible. This issue is still in 7.8.13, and only way i got it fixed was replacing the include/SubPanel-directory from v7.8.9.

**Comment by horus68** [comment]
When you created this issue there was a template to include your setup details.
Please do edit your reply and include the details required in template.
You also should include details on if you have done a quick repair, verified your permissions and if there are any the log messages related with this file

**Comment by hertell** [comment]
This issue can be tested with a fresh install of 7.8.10 with the Suite7 theme selected. As i wrote in my first post, the problem seem to be in the commits done to the files in include/SubPanel between versions 7.8.9 and 7.8.10.

**Comment by horus68** [comment]
I believe in you but to replicate this you should provide full details so someone can setup a similar system.
Please edit your first post using this template to include Environment and System:
https://github.com/salesagility/SuiteCRM/issues/new

**Comment by hertell** [comment]
This is nonsense. Why should i document every step in how to install and reproduce a bug that is broken in a plain install? If this is too difficult, then nevermind this bugreport. Let the LTS be broken and people should stick to 7.8.9 if they want to use the Suite7-theme.

**Comment by horus68** [comment]
@hertell Don't get me wrong but you are not reading what I'm saying: Its not how to install, its what system have you installed? What template you use (you only said this one in your second post)
If I want to test your bug, would I test it on Linux or on Windows? Which PHP/Mysql version? Those things can be important as your bug can be visible in a specific implementation and not visible on other system.

I'm not from SalesAgility, I'm a plain user. 
I don't use 7.8.x and I was only replying to you to make it easier for the ones that will came after me and eventually require more information.

If you read back this discussion you should note that only on your second reply you detailed that the bug is noted with a specific theme!
This is a community project, if you have a problem make it easy to people help you.
So lets start fresh:
- reopen issue, edit the first post using the issue template details
- delete all your replys
- I will do the same after that with my own reply

Next someone can read it clean and help you solve this

**Comment by horus68** [comment]
@hertell There is a fix here: https://github.com/salesagility/SuiteCRM/pull/5067
