### ISSUE TITLE
SuiteCRM 7.10 released as non LTS version!?

### ISSUE THREAD

**Issue by cumanacr** [salesagility/SuiteCRM#5260]
#### Issue

SuiteCRM 7.10 should be an LTS release version according to [RoadMap](https://suitecrm.com/lts/)
#### Expected Behavior

SuiteCRM 7.10 labeled as an LTS release version or [RoadMap](https://suitecrm.com/lts/) corrected

#### Actual Behavior

SuiteCRM 7.10 isn't an LTS release version yet!? or [RoadMap](https://suitecrm.com/lts/) is wrong

#### Possible Fix

Fix [RoadMap](https://suitecrm.com/lts/) or relabelling SuiteCRM 7.10 as SuiteCRM 7.10 LTS

**Comment by samus-aran** [comment]
Hi @cumanacr 
You are correct (and so is the roadmap) :)
This is a LTS release, but we will attach the LTS label to it when it has gone through the intensive bug fixing sprints following the 'version 0' release. This post-production bug fixing sprints usually deploys a couple of minor releases (v7.10.1/2) to ensure that when we apply LTS that we can guarantee a greater stability and security of the 7.10 version

**Comment by horus68** [comment]
I would prefer that a .0 its the LTS version, not some random number afterwards

**Comment by pgorod** [comment]
I can't say I agree with the objectors here :-)

7.10 is LTS, and it will have a life of around two years, it really makes no difference if the first week or two it isn't called LTS. 

And since LTS implies a certain assurance of robustness, and that robustness is very hard to achieve in this project, due to the characteristics of the code and the diversity of the community, I think it's a good idea to be patient and let the robustness come with the successive minor releases.
