### ISSUE TITLE
Workflow - Setting Date field based on Another Date field. Always 1 Save behind.

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#533]
https://suitecrm.com/forum/advanced-opensales-workflow-portal-support/6566-workflow-for-date-not-working

A rough Description would be if you:
Created Workflow to set Datefield2 to equal Datefield1 +6 Months, Does not change on record save.
Edit>Save record again, Datefield2 is set to the correct date.

However, if you make Datefield1 Equal to vastly different dates for each save, you can clearly see that Datefield2 is set to the previous value of Datefield1 +6 months

While not exactly a fix, Scheduled tasks does help with this as the next run will set it to the correct date.

**Comment by adriangibanelbtactic** [comment]
If you modify:
https://github.com/salesagility/SuiteCRM/blob/0b031f46e7715974782a386b3ce8d02596bedaf9/modules/AOW_Actions/actions/actionCreateRecord.php#L208-L216

so that previously you had:
```
                                if($params['value'][$key][0] == 'now'){
                                    $date = gmdate($dformat);
                                } else if($params['value'][$key][0] == 'field'){
                                    $date = $record->fetched_row[$params['field'][$key]];
                                } else if ($params['value'][$key][0] == 'today') {
                                    $date = $params['value'][$key][0];
                                } else {
                                    $date = $bean->fetched_row[$params['value'][$key][0]];
                                }
```

and then:

```
                                if($params['value'][$key][0] == 'now'){
                                    $date = gmdate($dformat);
                                } else if($params['value'][$key][0] == 'field'){
                                    $date = $record->$params['field'][$key];
                                } else if ($params['value'][$key][0] == 'today') {
                                    $date = $params['value'][$key][0];
                                } else {
                                    $date = $bean->$params['value'][$key][0];
                                }
```

then it fixed the problem for us in 7.4.3.

Note that I also modified the line:
```
                                } else if($params['value'][$key][0] == 'field'){
                                    $date = $record->$params['field'][$key];
```
in addition to the one suggested in:
https://suitecrm.com/forum/advanced-opensales-workflow-portal-support/6566-workflow-for-date-not-working#23876
because I suspect that if you had to modify the latter you also had to modify the former.

I have not checked if that extra modification had unexpected effects.
