### ISSUE TITLE
AOR - Date field not generated correctly with some Timezones

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#537]
As the Database stores Date & Datetime fields in UTC:
If the Timezone is anything behind UTC+0:00, it will show the wrong date.
e.g: If the Date field's time value is, for example, 1/01/2001 12:00AM
And the Timezone is equivalent to UTC -1:00, the report may generate it as 12/31/2000 11:00pm

**Comment by paulgodley** [comment]
The AOR Reporting build_report_html method calls TimeDate to get the display date.  This uses the time zone to format the value and this is where the UTC +/- times potentially causes the date to be incorrect (as there is no time part to a date, it uses midnight by default).  If the value is a date (as opposed to a date time) no time zone conversion should be applied.  This however, could have quite a far-reaching effect on the system (it could change the value of a range of dates).  @JimMackin  can you please mark this as an enhancement rather than a bug?

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AOR - Date field not generated correctly with some Timezones](https://trello.com/c/8bqhYyzt/145-aor-date-field-not-generated-correctly-with-some-timezones)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
