### ISSUE TITLE
Questions regarding SuiteCRM license.

### ISSUE THREAD

**Issue by Als09** [salesagility/SuiteCRM#5374]
I’m thinking about implementing your software in our company but our legal advisor pointed out a few problems. Help me figure if these are actually problems, or we don’t completely understand the license in English. If some of my questions aren’t clear enough I’ll try to rephrase them. I’m a computer guy not a lawyer so I might be writing nonsense after all.

_Question 1_ – Do you have a list of all the libraries you used in the system, all the licenses for these libraries, and which is the default license if several licenses are allowed ?

I’ve seen a PDF like this in SugarCRM (Third Party Software List Sugar 7.10.1.0) and I’m looking for something like this in SuiteCRM.

_Question 2_ – Is it allowed to combine AGPL v3 license with GPL v2 license ?

The legal advisor said it’s not allowed, but I see you combine them in your system (I didn’t see it in SugarCRM tho).

_Question 3_ – What are the licenses for these add-ons https://store.suitecrm.com/?tag=suitecrm ?

Why is there no license info for every module ?

_Question 4_ – If an add-on is published under AGPL does the developer have to give me the source code ?

I mean two situations: first, I buy an add-on and from what I understood the developer must give me the source code ? If not then when does he have to do that and when he doesn’t ?

Second, the add-on developer gives me an online demo, does he have to give me the source code for the add-on that is in SuiteCRM (even if I don’t buy the add-on) ?

_Question 5_ – Why do you change the original SugarCRM license and add your own terms ?

Our legal advisor says that it’s not allowed to change anything in the original license. If you wanna change anything (even a comma) you must have a consent from SugarCRM who owns the copy right for the file. If you have this consent can you send it to me ? If you don’t have this consent can your legal team explain how you are allowed to do this ?

_Question 6_ – When is it called “distribution” ? (According to AGPL)

There are 3 business cases in our company:
- Company A has 20 employees and we want to install SuiteCRM there (don’t we have to give the employees the source code ?)
- Company B has 11 employees (capital ties between companies) and they are supposed to connect to SuiteCRM in company A (according to the license do I have to give the employees of company B the source code of SuiteCRM and all the modifications we make ?)
- Some employees own their own businesses and they issue invoices to us, we wanna give them access to the CRM in company A, do I have to give them the source code and all modifications ?

_Question 7_ – What limitations/problems you faced ?

_Question 8_ – Any chance SuiteCRM will publish the system under a different, less complicated and simpler license ?

**Comment by Als09** [comment]
Hey guys, sorry for being impatient but could anybody help me out ? We have to decide by Monday which CRM we'll go for and I would really appreciate some answers... At least for the questions you know the answer to, I think most of them apply to pretty much any implementation so I'm sure you've answered them before.
Don't get me wrong, I really want us to pick SuiteCRM, but I don't think I can convince our legal advisor to approve of this choice if I don't get these answers. 
I know you guys are busy and I'm sorry for bugging you again, but as you see it's pretty urgent. Looking forward to hearing from you.

**Comment by horus68** [comment]
@salesagility

**Comment by Als09** [comment]
Alright! Thanks a lot!

**Comment by samus-aran** [comment]
Hi @Als09 

Sorry for the delay – but anything legal is always a melting pot of internal discussions but hopefully the response will help you guide you to using the SuiteCRM project appropriately.
First off, we highly recommend you seek legal advice from a lawyer with open source experience and carry out your own research. Free software licenses are relatively new compared to other types of licenses but the GNU is a really good source of information.
https://www.gnu.org/licenses/license-list.html#SoftwareLicenses
Secondly, from the sounds of it the legal advisor is seeking assurance on open source software due to the lack of liability and warranties these free licenses generally don’t provide. However, we have specifically address this by releasing SuiteAssured which provides a legal agreement that delivers indemnities, warranties, support and performance guarantees that the SuiteCRM project can not. I would recommend you look at SuiteAssured if this was a key element in your decision making :) https://suiteassured.com/

However, lets answer your questions as best we can.
Question 1: No we don’t but we include GNU and MIT suitable licenses. Regards to Sugar it is now a property software so it will have different licenses to consider when using third party libraries.
Question 2: 
Under the GNU.org (a definitive guide to GNU compatible licenses) define for AGPL(v3):
https://www.gnu.org/licenses/license-list.html#AGPLv3.0

“However, you are allowed to combine separate modules or source files released under both of those licenses in a single project, which will provide many programmers with all the permission they need to make the programs they want. See section 13 of both licenses for details.”
Question 3 & 4:
The plugins within the SuiteCRM store (except where stated) are not developed or maintained by us, so it will be up to the plug-ins owner to choose an appropriate license.
Regarding to providing source for an instance, or plug-in I would direct you again to GNU:
https://www.gnu.org/licenses/gpl-faq.html#CanIDemandACopy
So the short answer is generally no.
Question 5: We feel that what you were advised is incorrect. As Sugar released the source code as AGPL it can be modified and redistributed following the AGPL specification. We also adhere to the original legal notices throughout the application. We do recommend you seek a more open software experienced legal advisor if you need clarity.
Question 6 & 7: I think you are getting confused with access which is different from distribute. I’ve included a link that I hope helps provides clarify of what is ‘distribute’ under AGPL
https://www.gnu.org/licenses/gpl-faq.html#DoesTheGPLRequireAvailabilityToPublic

Question 8: I can understand why you may feel its more complicated but once you research it abit more it becomes a lot clearer. But to answer your question, no, not in the foreseeable future :)

**Comment by Als09** [comment]
Hi. Thank you for your answer.  I'm still looking for some more relevant information so I'll try to describe my problem again. 

Our legal advisor has a lot of experience with open source licenses, all our questions result from actual problems related to the license. Your answers seem to be about GPL but all our questions were about AGPL. Even tho they are very similar, our questions can't be answered using a GPL link. 
We're not really looking for assurance as far as warranties and liability are concerned; we know it's open source and that our company is responsible for everything, this is exactly why it's so important. Could you send me the SuiteAssured agreement to look through ? I can send you our company info if you need it. But I would like to get the answers first. 

1. If you don't mind me asking, how do you provide your clients with info about the license of the software  if you don't have this list ? From what I understood the system is under AGPL but to verify the whole program you gotta consider all the other licenses. It's only possible if you make order with all licenses. Otherwise it's just "good intentions" and unfortunately there's no place for good intentions in business.

2. In the same paragraph it says "Please note that the GNU AGPL is not compatible with GPLv2" so I'm not sure how relevant the fragment about GPL v3 is that you quoted. Am I missing something ?  My issue was that you combine AGPL v3 with GPL v2 which is forbidden, at least according to wikipedia and some other sources. 

3. I thought that since this is your store you also are in charge of the licenses and safety, like all the other large companies like Apple or Google, who enforce the license in their stores. If somebody sells a plugin in your store and the plugin is incompatible with AGPL then what's the point of publishing and selling it at all ?

4. Please take a look at my 4th question again. All the questions I asked were previously analyzed by a lawyer. If someone adds a module to SuiteCRM it must be under AGPL, or a compatible one (MIT for example). Even tho it's under MIT, due to AGPL that it's combined with, it "inherits" AGPL properties. In practice it means that access to demo means "distribution" and the person who gives the demo access must also give SuiteCRM source code and source code of the module added to SuiteCRM. You have to understand that AGPL is not GPL, especially when it comes to "distribution", all problems I described are related mostly to "distribution" and the rules for when distribution takes place for GPL and for AGPL are totally different.

5. Is there legal basis that allows you to alter the original SugarCRM license ? I didn't think you could change anything in the license (even a comma) because any change can alter the license terms, and what you did indeed seems to alter the license terms. Since SugarCRM released a file that says that info about SugarCRM must be included, then how can you change to also include SuiteCRM ? Shouldn't Sugar's permission be necessary ? It violates their terms. I might be wrong, and if I am please show me a similar case, some legal advice, or maybe just solve it be releasing a statement by your legal team that you are allowed to do that. New files can have the SuiteCRM notice, but I'm not sure the old ones published by SugarCRM can. 

6. I think you are confusing GPL with AGPL... The case I'm referring to in here is related to "distribution" in a network, which is something that AGPL describes differently than GPL.

If there are any terms that violate the license then our company is liable, not you... That's why this is absolutely important for us to understand these aspects. 

Sorry for the long post, like you said, anything legal always comes with a ton of discussions.

**Comment by samus-aran** [comment]
Hi @Als09

Feel free to enter your contact details on the SuiteAssured website so one of the team can contact you directly.

I linked in the FAQs because, if you visit the AGPL page itself, they too link to the GPL FAQs. Perhaps bad linking on GNU’s part but take that as what you will. https://www.gnu.org/licenses/agpl.html

If any of the clients request for a list of licenses then we can make that list up but it hasn’t been something we have done yet for the core.

We are not affiliated with the SuiteCRM store. If there was a misused license then users would direct the report to the copyright owner (of the plug-in). We have in the past being notified of violations but that was on rare occasions.

However I think we are going in too deep around much of the legal terminology here and moving into the territory of legal advice which we are not in a position to provide. For example we can’t dictate if a demo is a type of distribution. And finally for question 5 we have already had our legal team look at the project at the point of release back in 2013 so there shouldn’t be any requirement for a statement. 

I appreciate your need for clarity on certain aspects but I feel most has been addressed as much as we can here on github. Contact us [directly](mailto:community@suitecrm.com) if you have further concerns but as I said I feel we have addressed your queries and interpreting the terminology of the license itself is something we can’t provide.

**Comment by Als09** [comment]
Unfortunately I still didn’t get the answers; I feel like I’m talking to a programmer, not to someone who  knows something more about AGPL apart from the fact that it’s similar to GPL.

If your company doesn’t have any legal reviews regarding AGPL (eg. when “distribution” takes place) and you don’t see any problems with incorrectly combining incompatible licenses, then no paid support and no warranty will help. It seems like you guys either don’t understand AGPL or don’t want to tell how it really is.

I’m mad at myself for having spent so much time trying to convince my company that it was worth choosing SuiteCRM as our CRM, unfortunately without answers to these basic and simple questions it’s impossible.

**Comment by samus-aran** [comment]
Hi @Als09 
You are talking to a programmer :smiley: That is why I suggested you talk to us directly (from the link provided) were we can put you in contact with someone more specialised.
I also would make a suggestion to seek your advice from [FSF directly](https://www.fsf.org/) - they appear to be responsive and are in more of a position to clarify your queries.
