### ISSUE TITLE
User's Outbound Email Settings redesign

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#5376]
#### Issue

There seem to be two different outbound settings screens, inside the user profile email settings.

1. Profile -> Scroll down to the bottom -> Settings -> Mail Accounts-> Mail Accounts (the top half of the screen)-> ADD(or EDIT) This one sends correctly, and has From name fields.

![image](https://user-images.githubusercontent.com/15945027/36850975-06ac1aee-1d60-11e8-9a0a-daa761224e47.png)

2. Profile -> Scroll down to the bottom -> Settings -> Mail Accounts -> Outgoing SMTP (lower half, list box) -> ADD (or in the list view, EDIT icon) This one doesn't send, and doesn't have these fields

![image](https://user-images.githubusercontent.com/15945027/36851217-a4ed8116-1d60-11e8-96eb-0135956682ce.png)

#### Expected Behavior
Now, I'm not sure there is actually a sending bug here, maybe it's just so convoluted to set it up that I wasn't able to do it. But that is also a problem, right?

#### Possible Fix
This needs a screen redesign.

1. There should be only one place to set up User's outbound email
2. It should have the `From` and `From name` fields, and they should be on the same screen as the `Send test email` button, since these fields are mandatory for some SMTP servers to allow sending

Since there can be multiple outbound accounts, careful consideration is needed about where to put this.

Another suggestion I have when redesigning this screen is this: 
3. Add some simple text labels with tips. Sentences like `This is the user's personal outbound account, but other system-wide accounts can be set up in Admin / Outbound email settings`. You know, whatever needs to be explained. Let's make this easier to understand.

The redesign needs to work closely with the code that fetches accounts to put in the `Email Compose` window, in the `From` list box. If accounts are discarded from there, for some reason, it should be explicit somewhere. So the settings screens pictured above could signal: `this account won't show up on Compose window because X`

I am not sure what reason this could be, but sometimes the logs have something about it being the same as an admin account, etc. Watch out for users who repeat the same accounts for system account and user's account (typical of admins trying out the system).

#### Environment
* SuiteCRM Version used: 7.9, 7.10

**Comment by Dillon-Brown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User's Outbound Email Settings redesign](https://trello.com/c/yxSTbqLJ/248-users-outbound-email-settings-redesign)

**Comment by labcerouno** [comment]
There could be a better distinction for the terms "Group" and "Personal" mail accounts. There are some pages that this distinction is not clear.

**Comment by pgorod** [comment]
@labcerouno do you mean pages in the app, or pages in the Documentation? 

In any case, can you please be more specific and tell me which pages you mean? I'd like to make all this more intuitive and easier to use. Thanks

**Comment by angar321** [comment]
Apologies if I am raising this in the wrong place (new here).  When working on the email functionality, please bear in mind that not everybody wants inbound email, some only want outbound. We use SuiteCRM to send out emails based on templates, but all inbound email is handled by another system and not SuiiteCRM. It appears 7.10.4 requires us to setup inbound email in order to be able to send anything from a user (and as such our outbound email has stopped working since we upgraded to 7.10.4 from 7.8.x).  Thanks

**Comment by angar321** [comment]
fantastic, thanks for the feedback.

**Comment by labcerouno** [comment]
Hi @pgorod ! I meant in the app. Although, in the Documentation, there is nothing about `Outbound email` (I guess it should be in this page https://docs.suitecrm.com/user/modules/email-settings). The only mention in the docs is about system notification outbound account.

Regarding the difference between personal and groups accounts, in the Admin page (for an Admin user), it could show a distinction for these two types of accounts. 

If I go to `Admin - Email - Inbound Email`, there is nothing that tells me I'll be configuring a group account. Only if I click this item, one of the buttons will show: `New group Email Account`. That's the only indication that these setting are for group email accounts. If I go to `Admin - Email - Outbound Email`, I guess I'll be configuring a group account. I'm not sure, though, because it's not quite clear. The equivalent button to create a new account, in this page says: `Create Outbound Email Accounts`.  

I suggest putting in the `Admin` page the label `Inbound Group Email Account` and `Outbound Group Email Account`.

If I go to `User Manager - User X - Edit - Email Settings - Settings - Mail Accounts - Outgoing SMTP Mail Servers - Add`, I'm almost sure I'll be configuring a personal account. The path to reach this section is a bit large. As a suggestion, this could be in a separate Tab in the User Edition Page. (Now the tabs available are User Profile, Advanced, External Accounts, Layout Options). There could be one more tab called Email Settings with all the settings in the same page, without the need to click in so many buttons to reach it.

These are my suggestions. Thank you very much

**Comment by pgorod** [comment]
In the Docs, there are some paragraphs about Outbound, right at the beginning of that page you linked (it's called "Outgoing" there, maybe we should fix that).

And in the app, there is _some_ indication of what the Inbound Email settings include...

![image](https://user-images.githubusercontent.com/15945027/39550323-bb5f9bea-4e58-11e8-883b-a1502a662885.png)

But I agree with you this is all too confusing and there are several misleading names.

A Group account...
- can be used by more than one user
- allows auto-import
- allows auto case creation
- has to be inbound, but the same account can also be configured for outbound

I think we should just drop the term "Group" which is only proper to the first function.

Thanks for your suggestions, they are useful and I will take them into account as I develop my thought on this problematic area of the app.
