### ISSUE TITLE
[language] Unused OAUTH2 Clients? (hotfix branch)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#5383]
These lines exist in language files only.
Can they be removed or is there an intention to use them in a future releases?

  'LNK_NEW_OAUTH2_IMPLICIT_CLIENT' => 'New Implicit Client',
  'LNK_NEW_OAUTH2_AUTHORIZATION_CLIENT' => 'New Authorization Client',

https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/OAuth2Clients/language/en_us.lang.php#L72-L73

https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/OAuth2Tokens/language/en_us.lang.php#L69-L70

**Comment by horus68** [comment]
True. It was added here but only for the language file: 
https://github.com/salesagility/SuiteCRM/commit/aa253a219cd66d2b7493e124676cd2ab261d9a3e

They are in 2 files since PR https://github.com/salesagility/SuiteCRM/pull/5321
modules/OAuth2Clients/language/en_us.lang.php
modules/OAuth2Tokens/language/en_us.lang.php

**Comment by PedroErnst** [comment]
They were included for use in future releases.

**Comment by likhobory** [comment]
OK
