### ISSUE TITLE
Removing a contact from a meeting prevents readding

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#540]
If there is an entry in the meetings_contacts table for a contact where the relationship has been marked deleted attempting to add the contact again from the meeting edit view silently ignores the contact and doesn't add them.
Looking in the meetings form handler it may just be a case of adding "deleted = 0" to the query.

May also be an issue for other invitee types (users, e.t.c.)

**Comment by vladbar** [comment]
/var/www/html/SuiteCRMfromGit/modules/Meetings/MeetingFormBase.php - 449 - } else if (!$focus->date_changed) { - does not allow to enter into the query statement

/var/www/html/SuiteCRMfromGit/modules/Meetings/MeetingFormBase.php - 225 because - $focus = populateFromPost($prefix, $focus); - gets date/time from $POST in a different format 

/var/www/html/SuiteCRMfromGit/modules/Meetings/MeetingFormBase.php - 92  because $form = <<<EOF ... sets the date/time in the different format

/var/www/html/SuiteCRMfromGit/modules/Meetings/MeetingFormBase.php - 405 - $focus->save(true); - already deals with saving date/time correctly
/var/www/html/SuiteCRMfromGit/modules/Meetings/Meeting.php - 161 - function save($check_notify = FALSE) { - called from the above place and deals with saving date/time correctly

Therefore $focus->date_changed is redundant
