### ISSUE TITLE
7.10.1 – "Base Impleme..." email address links in the Recently Viewed sidebar

### ISSUE THREAD

**Issue by davenz** [salesagility/SuiteCRM#5403]
#### Issue
In the Recently Viewed sidebar, a number of links appear that all contain the text "Base Impleme...". 

Clicking on any one of these links displays the following error text:

`Error: File [modules/EmailAddresses/metadata/detailviewdefs.php] is missing. Unable to create because no corresponding HTML file was found.`

![suitecrm7 10 1-emailrecentlyviewed-1](https://user-images.githubusercontent.com/3925818/37011763-6f964486-2156-11e8-9b91-3aea6c9dd457.png)

#### Expected Behavior
I cannot identify where these items have come from, so the expected behaviour is for them not to appear.

#### Actual Behavior
The items referred to appear in the absence of any obvious identifiable cause.

#### Steps to Reproduce
Unknown at this stage. Please refer to https://suitecrm.com/suitecrm/forum/installation-upgrade-help/17826-error-accessing-emailsaddresses-module

#### Context
Appeared in 7.10.1.

#### Your Environment

* SuiteCRM Version used: 7.10.1, updated from 7.9.8 with no customisations performed,
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 58.0.2
* Operating System and version (e.g Ubuntu 16.04): Ubuntu Server 16.04, stock LAMP stack

**Comment by davenz** [comment]
Possibly related to  #5295 ?

**Comment by Dillon-Brown** [comment]
Should be fixed here: #5411

**Comment by horus68** [comment]
@Dillon-Brown Getting this error too in v7.10.0 but the fix didn't work for me (Repair and rebuild, cache cleaned).
For me its related to EmailAddresses not to the Email module (I don't even have the email in use).

`Error: File [modules/EmailAddresses/metadata/detailviewdefs.php] is missing. Unable to create because no corresponding HTML file was found.`
![base implementation](https://user-images.githubusercontent.com/3055443/37149527-3c361762-22c6-11e8-9129-6d33ba80cf7a.png)

Same goes in the demo site. If you click the sidebar link the url is
`https://demo.suiteondemand.com/index.php?module=EmailAddresses&action=DetailView&record=4fd3e6c7-759e-c21e-b9d0-5aa122317b60`

**Comment by Dillon-Brown** [comment]
@horus68 Hmm, not sure why that would be the case. Have you checked to see if the code is the same? 

```
{if $item.module_name != 'Emails' && $item.module_name != 'InboundEmail' && $item.module_name != 'EmailAddresses'}
```

Should block anything from the Emails, InboundEmail and EmailAddresses module.

**Comment by horus68** [comment]
Working know! I had implemented only one commit on that PR! 
Implementing the ful PR worked without any issue.
Demo needs to be fixed too :)
