### ISSUE TITLE
Password is not saving

### ISSUE THREAD

**Issue by yawarnaqvi** [salesagility/SuiteCRM#5414]
#### Issue

In user profile, if the user pastes the password in the New Password field by right-clicking and pasting the value, the password will not be saved.

#### Expected Behavior

The password field value should be saved.

#### Actual Behavior

Password is not saving while creating and updating the password in user profile.

#### Steps to Reproduce

1. Go to the user profile.
2. Click on Create/Edit the user.
3. Fill the required fields
4. Copy the password from any file.
5. Right-click on the New Password Field.
6. Click the paste option.
7. Also, paste the value on the confirm password field by right-click.
8. Click Save.

#### Context

Low Priority

#### Your Environment

* SuiteCRM Version used: 7.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 60.0.3112.78 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.5.9-1ubuntu4.21
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by Dillon-Brown** [comment]
Hi @yawarnaqvi. I'm not able to replicate on 7.10.1. Are you using any sort of password manager that might be causing this?

**Comment by herrt** [comment]
Hi,
maybe related to #5396 ?
How long is your password?

**Comment by yawarnaqvi** [comment]
Hi @Dillon-Brown, following are the steps screenshots of SuiteCRM 7.10.1. Please follow these steps and I am sure you can replicate it.

![step 1](https://user-images.githubusercontent.com/19649189/37094881-26a90b7e-2236-11e8-8d61-7dd271c7eced.png)
![step 2](https://user-images.githubusercontent.com/19649189/37094884-27057ef4-2236-11e8-9b4c-3ef23db062a1.png)
![step 3](https://user-images.githubusercontent.com/19649189/37094954-62431e5e-2236-11e8-9685-4b6e0fd38bf2.png)

After performing the above steps, try to login with the password that you have set and you will see the password is not updated. Please let me know if you need any other details.

@herrt this is not something related to SMTP Password.

Thanks.

**Comment by mravery** [comment]
I'm seeing this too. My setup:

```
  ubuntu 18.04
  mysql 14.14
  php 7.2.10
  suitecrm 7.11
```

It doesn't look like a Javascript issue; upon pressing the 'Save' button I can see that the form submits. I would love to know what the endpoint is on the PHP side so I can track it. I tried looking to see how `index.php` processes POST requests, but I just got lost.

This issue is being reported on [the help forum](https://suitecrm.com/suitecrm/forum/installation-upgrade-help/21518-admin-login-works-but-not-new-user-logins).

**Comment by Mausino** [comment]
@Dillon-Brown isnt working on 7.11 also but only for Admin and only if want change user pass where doesnt need user pass because there are only 2 fields for new pass. It looks tat save it... No error but if you want login user the new pass wasnt applied and you cannot login... Only with old. You must click on login page on link forgot password and this is only way how admin can change pass if has also access to email of user.

**Comment by Dillon-Brown** [comment]
This issue was technically unrelated to the issue of creating a new user and having the password not save. Original issue should already be resolved. Closing in favour of #6787
