### ISSUE TITLE
Icons not shown

### ISSUE THREAD

**Issue by topesantos** [salesagility/SuiteCRM#5440]
#### Issue
I upgraded to 7.10.1 and with the change "Convert SuiteP Icons to font icons" there are missing icons

#### Expected Behavior

![image](https://user-images.githubusercontent.com/36194291/37148630-0f4ffa90-22c3-11e8-8507-4d24841386b9.png)

#### Actual Behavior

![image](https://user-images.githubusercontent.com/36194291/37148648-21874c86-22c3-11e8-8241-7152ae017ba0.png)

The code was change from 
src="themes/SuiteP/images/info_inline.gif?v=UdYXHyLulMVD07WeXHFoJw"
to 
class="info suitepicon suiteicon-action-info"

**Comment by Dillon-Brown** [comment]
@topesantos Have you tried checking permissions, clearing cache and repair + rebuild?

**Comment by connorshea** [comment]
We have a lot of files like `custom/themes/default/images/sub_panel/Custom_Module_Name.svg` and `custom/themes/default/images/Custom_Module_Name.svg` / `custom/themes/default/images/Custom_Module_Name.gif`, but they're no longer used after upgrading from 7.9 to 7.10.16 (presumably because of the icon font change in https://github.com/salesagility/SuiteCRM/pull/5273).

Previously the subpanels (and most other places) would just pick up the SVG automatically, but with the change we need to add the icons to their respective CSS classes (e.g. `suitepicon-module-custom-module-name`). Is there a good way to do that beyond just brute-forcing it and adding the icon styles to our custom CSS?
