### ISSUE TITLE
Can't send emails from Opportunities module

### ISSUE THREAD

**Issue by army113** [salesagility/SuiteCRM#5448]
#### Issue

I am unable to send any emails from the Activities subpanel in the Opportunities module. The Compose button is there, but nothing seems to happen upon clicking it.

#### Expected Behavior

A compose email popup (possibly with already inserted email from related account, contact, or history) should open.

#### Actual Behavior

Nothing visible happens.

#### Possible Fix

All the parameters in the related html tag are empty. It might be connected. Example:
<a class="email-link" href="javascript:void(0);" onclick="$(document).openComposeViewModal(this);" data-module="" data-record-id="" data-module-name="" data-email-address=""></a>

#### Steps to Reproduce

1. Open an opportunity.
2. Expand the Activities panel.
3. Open the Create Task drop down.
4. Click Compose Email.

#### Context

Trying to send an email directly from the Opportunities module.

#### Your Environment

* SuiteCRM Version used: 7.10.1
* Browser name and version: Latest Firefox, Chrome, probably others
* Environment name and version: MariaDB 10.0, PHP 7.0
* Operating System and version: Ubuntu 16.04

**Comment by pstevens71** [comment]
I also have this issue in 7.9.15 and 7.9.9, the only exception is the normal box pops up, but then just has the revolving "waiting" circle forever and never actually opens up the email compose box.
![box](https://user-images.githubusercontent.com/29544935/37425522-0da1a12c-279a-11e8-8245-17befb922340.jpg)

I uploaded a screen shot.

**Comment by goltra** [comment]
I don't know if I have same problem. I have an email assigned to an account and I can send an email form activity/ compose email (really instead of compose email I see email address). If I try to send an email from an opportunity of this account, I can't, I see compose email and I can't click.

I attach some a screenshot from account and from opportunity
![fromaccount](https://user-images.githubusercontent.com/1634767/38024620-e1a616d8-3285-11e8-8f86-ac34e4fe25b0.png)
![fromoportunity](https://user-images.githubusercontent.com/1634767/38024673-fb0f579c-3285-11e8-9bd3-e10e555d7ffb.png)

**Comment by Miroslav36** [comment]
Hello I have the same issue with 7.10.2 (just upgraded from 7.7)

expected behavior 
in opportunities, have a clickable button on the "compose email" message on the menu.
In 7.7 (and previous versions) it was possible to click on the button "compose email" in order to send a message directly from the opportunity. Then it used to be possible to select the contacts attached to the opportunity.

actual behavior
The "compose email" message appears in the menu, but it is not a clickable button. 
(see picture attached)
![bug-opportunities](https://user-images.githubusercontent.com/17055131/38141241-7cb31682-3437-11e8-9114-f4ae67d5b846.png)

Your Environment
SuiteCRM Version used: 7.10.2
Browser name and version: Firefox 58, 59 and Chrome 65
Environment name and version: MariaDB 10.0.32, PHP 5.6.33
Operating System and version: Debian 8.10 (Jessie)

Thank you
