### ISSUE TITLE
During instalation 7.10.2 Uncaught ReferenceError: YAHOO is not defined

### ISSUE THREAD

**Issue by goncaloLopesMarques** [salesagility/SuiteCRM#5532]
#### Issue

I´m trying to install new version of suiteCrm and when i´m the database and user configuration install menu and press next button the error install.php:1048 Uncaught ReferenceError: YAHOO is not defined pop up in chrome console
#### Expected Behavior

continue install guide
#### Actual Behavior

Dont do anything
#### Steps to Reproduce

1.Download lateste version from suiteCrm website
2.copy the rar to the provider server
3.open mydomain.com/suiteCrm
4.start the install guide

#### Your Environment

* SuiteCRM Version used: 7.10.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chrome version 64.0.3282.186
* Environment name and version (e.g. MySQL, PHP 7):ths installer check system passed on every test
* Operating System and version (e.g Ubuntu 16.04): ubuntu server from my provider

**Comment by pgorod** [comment]
From the steps you list, it doesn't look like you set permissions on the files. 
Anyway, you should close this issue here on Github, and open it on the Forums instead.

That is the place to troubleshoot individual installations. Here you just come to report bugs. 

https://suitecrm.com/suitecrm/forum
