### ISSUE TITLE
GDPR: confirmed opt-in

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#5548]
#### Suggestion

I've been testing the new double-opt-in functionality and it's a very good first implementation imho! Kudos!

Something that could be improved: It looks like any email address can be "confirmed" by simply loading the URL `http://[CRM-domain]/index.php?entryPoint=ConfirmOptIn&from=[email address]`?

If this is correct this almost certainly does not comply with GDPR "security of processing" and "proof of consent" guidelines. It is too easy to spoof/manipulate. And thereby unfortunately becomes useless for GDPR compliance.
There should be no feasible way for any external or internal actor to change the customers consent status (other than an IT-admin)

#### Possible Fix

1. At the very very least only accept confirmed-opt-in for email addresses that already have the "opt-in" checkbox checked. Currently I can confirm any email address in the system by loading the URL with the respective email address. (can still be very easily manipulated)

2. next step would be to track which email address has been sent a request for confirmed opt-in and only accept the URL-action for this email address if the email has been sent out. (looks like the confirm_opt_in_sent_date already tracks this, so you'd just have to add a rule to the ConfirmOptIn entryPoint action to check for this) (can still be easily manipulated)

3. clean solution: The addition of an obfuscation layer like SuiteCRM already uses for opt-out links in campaign emails. I.e. whenever SuiteCRM sends out an email asking for confirmed opt-in, it must create and save a custom ID for this request and add it to the GET-parameters of the confirmOptIn URL action. That way every user consent process has its own code. And this code is only generated once an email has been sent out to the user (automatically, manually in bulk, or manually for a single email address). (cannot be easily manipulated)

(4. next step after that would be the additional functionality to let users opt-in to individual target lists. Analogous to the way opt-out links allow users to be put on suppression lists for individual newsletter campaigns)

#### Your Environment

* SuiteCRM Version used: 7.10.0

**Comment by samus-aran** [comment]
Thank you @EZS-JD for raising this and we'll supply a fix immediately.

**Comment by poynter2** [comment]
Still seem to have this issue in Version 7.10.4
This is shown when user clicks on opt-in link in email:
MySQL error 1054: Unknown column 'confirm_opt_in_token' in 'field list'

Also missing the "ticks" from the contacts list.

**Comment by Kristianostman** [comment]
Does anybody have the double option in working? My biggest consern is that Suite CRM 7.10.4 does not compile with EU GDPR. Deadline for renewal of opt in from existing contacts is Thursday 24.5.2018, since from Friday 25.5.2018 (after 3 days) you are ot allowed to send mail to contacts that has not renewed the opt-in. 

My problem is that I can not manually send out confirmed opt-in emails. Or I can do it, but nothing changes. I should see that they have optioned in again. So once again, does anybody have this working? For existing contacts it would be stupid to use web forms and have them to double opt-in that way. I has to be simple, and it should be easy to admin too.

I do also miss the green ticks, do not see singe neither doulbe ticks.
