### ISSUE TITLE
Can't submit all hidden fields on EditView

### ISSUE THREAD

**Issue by topesantos** [salesagility/SuiteCRM#5580]
#### Issue
Since the form hidden fields are duplicated, ones near the first SAVE button and the others on the second SAVE, if I dynamically alter a field it doesn't submit since the javascript alters only the first one.
This didn't happen on old versions since there wasn't duplicated fields.
What's the reason for duplicated fields?!

#### Expected Behavior
Submit all the fields with the last value dinamically set.

#### Actual Behavior
Submits the original values since the form hidden fields are at the last position.

#### Possible Fix
In include/EditView/footer.tpl delete or comment lines 56 to 60:

           

#### Your Environment

SuiteCRM 7.10

**Comment by PedroErnst** [comment]
Hello @topesantos 

Thank you for reporting this.

I'm looking at the second save button in the Contacts but can't seem to find the hidden fields you mention.

Also, the tpl file you mention is not the one that produces the standard Editview.

In order to find this issue, could you please detail the exact steps to reproduce it? In which module does this happen? Maybe provide screenshot.

Thanks!
