### ISSUE TITLE
forward/reply email: lower buttons (send-file, save-draft, etc.) all send email

### ISSUE THREAD

**Issue by tech-ch1** [salesagility/SuiteCRM#5628]
On some occasion, when replying to an email, the attach file, attach document, save draft, etc. buttons actually send the email instead of doing what they are supposed to do.

This issue may be related to #5627

#### Issue
- On a user account synced with an Imap mailbox (user@example.org)
- Using an external client, send an email to user@example.org with subject "Bla" and body "There is an apostrophe in this email. That's unfortunate."
- Using the user account, open the email and try to reply to it or to forward it.
- Click on the "Attach file" button (or another button) in the lower bar.

#### Expected Behavior
This should open the file selection window.

#### Actual Behavior
It actually try to send the email.

#### Steps to Reproduce
I was not able to identify exactly what kind of e-mail had to be sent to trigger the bug.
Empirically, it didn't happen with text emails, but happened with large HTML emails with attachments, apostrophes, and all.

#### Context
After upgrading suitecrm to 7.10.2, tried to forward a mail. Raised a lot of issues, this is one (an other is that emails are truncated on reply/forward, see #5627)
I feel this should be a high priority issue.

#### Your Environment
* SuiteCRM Version used: 7.10.2
* Browser name and version: Firefox 58, 59 and Chrome 65
* Environment name and version: MariaDB 10.0.32, PHP 5.6.33
* Operating System and version: Debian 8.10 (Jessie)

**Comment by PedroErnst** [comment]
Hello @tech-ch1 

Thanks for reporting these issues.

I'm looking at this one but unable to reproduce this. You said it's not clear what exactly triggers it, but I'd still ask you to provide a few more details, and maybe screenshots if possible, in order to enable us to fix it ASAP.

So far I've tried sending emails with very large html bodies, containing styles and images as well a lot of text, but no luck. You mentioned also attachments, but then you said when pressing attachments the email gets sent... so do you get to add some attachments but at some point when adding another it just sends it? Or does this happen with reply/forward?

Any information would be much appreciated, thanks in advance!

**Comment by Miroslav36** [comment]
Hello @PedroErnst ,
(I work with @tech-ch1  but he is currently out of the office)
I have noticed that when trying to 'reply'  to a  message already containing attachements, I get the described behavior. Replying to a message without attachments works normally.
Steps to reproduce :
- Reply to a message with attachements (a file, a picture, ...)
- click on the "attach a file" button -> the email has been sent instead of opening the window in order to select a file. (see attached picture)
![bug-reply](https://user-images.githubusercontent.com/17055131/38142600-3f4e594a-343d-11e8-8c4b-d76ed524567e.png)

**Comment by PedroErnst** [comment]
Thank you @Miroslav36 

I've tried this to no avail. It looks like a JS issue, is there anything in the dev tool console?

**Comment by tech-ch1** [comment]
After applying the fix for #5627, it seems that the symptoms are different.
Now, the buttons aren't displayed for the "faulty" e-mails.
To me, it looks like a DOM problem, either due to a malformated e-mail or to some parsing errors. Here is a screenshot of Firefox DOM explorer. All the way down is the div containing the lowerbar's buttons. 
Which is inside a lot of divs… I would expect the div location in the DOM not to depend on the displayed e-mail. Also, the DOM structure looked a bit… strange.
![complex_dom](https://user-images.githubusercontent.com/37901650/38246243-70b4472c-3741-11e8-8e05-5ab95a9145fd.png)

**Comment by tech-ch1** [comment]
If I set
`$this->bean->description_html = ""`
in modules/Emails/EmailsController.php line 805 (instead of `$this->bean->description_html = json_encode([$this->bean->description_html]);`, the bottom bar appears again.

**Comment by tech-ch1** [comment]
I managed to anonymise one of the buggy email raising the bug:
[Buggy message.eml.gz](https://github.com/salesagility/SuiteCRM/files/1879774/Buggy.message.eml.gz)

**Comment by sanchezfauste** [comment]
Same issue on SuiteCRM 7.9.17.
