### ISSUE TITLE
VAT Display in PDF Templates wrong when Currency Significant Digits set to 0

### ISSUE THREAD

**Issue by triluu-gms** [salesagility/SuiteCRM#5653]
VAT (percent) display wrong if VAT set to 0, 10, 20, ... (end with 0) when set Currency Significant Digits is 0 in user preference.

#### Issue

Issue occur follow steps:

After change user profile set Currency Significant Digits = 0. Create PDF templates with VAT percent display in quotes, invoices has issue: VAT percent display lost character "0". VAT percent just display: %, 1%, 2% instead correct VAT percent is: 0%, 10%, 20%. 

#### Expected Behavior

Cannot send quotation to contact. Customer maybe claim VAT value different with VAT percent.
#### Actual Behavior

Cannot send quotation to contact.
#### Possible Fix

set Currency Significant Digits > 0. 
#### Steps to Reproduce

1. Open User profile -> Select Advance tab, choose Currency Significant Digits = 0.
2. Create new pdf templates (from quotes, invoice templates), display VAT ($aos_products_quotes_vat, $aos_services_quotes_vat).
3. Create quotes, add product lines, select VAT (0%, 10%, 20%, ...) -> Save quotes.
4. Click to Actions -> Email quotations/Print as PDF, Email PDF.  Check output file, VAT column display wrong (%, 1%, 2%) instead (0%, 10%, 20%).

#### Your Environment

* SuiteCRM Version used: Version 7.10.2 - Sugar Version 6.5.25 (Build 344)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 65.0.3325.181 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 10.2, PHP 5.6.3
* Operating System and version (e.g Ubuntu 16.04): Centos 7.4

**Comment by filev-svt** [comment]
This issue still persists, in my case, the content of the vat in the database contained "21" and the display value in the PDF was 0%, by changing it to "21.0" the display value became 21% and the issue was fixed. I'm guessing a wrong parsing method for the PDF – which is unnecessary, I don't need an automatic percentage suffix, I'd much prefer a simple value display, I can always add the percentage to the template field myself. Also, I consider the automatic parsing of a VAT field unexpected, because none of the other PDF template fields have formatting or parsing associated with them.
