### ISSUE TITLE
Export Customizations feature of Studio does not work in 7.10.4

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#5737]
Export Customizations feature of Studio does not export the custom fields properly, so when you import the package on another SuiteCRM installation the custom fields are not created.
Issue

The manifest file generated by MBPackage.php does not include the 'custom_fields' array.

This works as expected on 7.8.14 version. The issue appears on 7.10.4.
Expected Behavior

The generated manifest must include the 'custom_fields' array definition.
Actual Behavior

The 'custom_fields' array is missing on the manifest file, so when you import the package the custom fields are not created and are not displayed on the studio.

Steps to Reproduce

Installation of SuiteCRM v7.10.4

    Enter to the Studio of a SuiteCRM.
    Go to the Accounts module.
    Create a custom field:

    Data Type: TextField
    Field Name: test_field
    Display Label: Test Field

    Save the custom fiel.
    Go to the main screen of Studio.
    Select the 'Export Customizations' option.
    Provide a Package Name: 'export_test'.
    Select the Accounts module.
    Click on 'Export' and save the file.

Look at manifest file: custom fileds are missing.

Context

I'm trying to export the customizations of SuiteCRM Account module to another intallation.
Your Environment

    SuiteCRM Version used: 710.4
    Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome / firefox
    Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6, PHP 7.0
    Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by PedroErnst** [comment]
Hi @Lehnerr 

Thanks for reporting this.

I have followed your steps, but my manifest does include the custom fields array.

![image](https://user-images.githubusercontent.com/34056696/38880216-0f8aaeb0-425d-11e8-8252-45a0d885f82d.png)

The failure to do so on your instance could be due to other customizations or possibly something to do with the upgrade process if you upgraded from 7.8.x to 7.10.x, and it might prove a little difficult to track down, so any additional details you can provide will be useful to help us locate the issue.

Is yours a clean install of 7.10 or an upgraded version?
Do you have any customizations outside of studio?
Are you trying to export all modules customizations or just accounts?
Anything in the logs?
Anything in the php error log?
Can you post the relevant part of the generated manifest?

Thanks for your help.

**Comment by Lehnerr** [comment]
Hi.
I've checked again and it was still missing in manifest file. But I found the reason. It was a bad file permission. After repairing it. it works again.
Sorry for this.
thx and kindest regards Robert

**Comment by Lehnerr** [comment]
thx
