### ISSUE TITLE
Subpanels - missing the names of them after reset of module

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#5779]
#### Issue

I reset the Project Holiday module in studio and i get error page... 

After in all modules are missing the names of subpanels.. only History and Activities  + Campain log stayed.

![2018-04-24_1209](https://user-images.githubusercontent.com/5773777/39181025-a953350c-47b8-11e8-9dd3-1d379dae2bb6.png)

#### Steps to Reproduce

1. Reseted module Project Holiday ( i didn't tried other)

#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version: Chrome 64.x
* Environment name and version:Php 7.2.16
* Operating System and version Win 10 Home

**Comment by Mausino** [comment]
@PedroErnst the Repair/Rebuild fixed the problem... should i let this issue open ??? or you want add some function which will automatically repair/rebuild after when user push Repair of module in Studio

**Comment by PedroErnst** [comment]
I don't know, this is for someone else to decide. Maybe @samus-aran ?

**Comment by PedroErnst** [comment]
I think it's generally a good idea to Repair and Rebuild often, I do it pretty much after **any** change in Studio. Half of the time something doesn't work it's fixed by a RR. But including forced RR in Studio actions might just slow down the system needlessly.

So I'd personally say it's fine the way it is. Get in the habit of RRing every time :)

**Comment by Dillon-Brown** [comment]
1.
