### ISSUE TITLE
Cannot find documentation to use 

### ISSUE THREAD

**Issue by ThomasGmeinder** [salesagility/SuiteCRM#5825]
#### Issue
I'm trying to use MBPackage.php to create a manifest .zip file that I can upload with Module Loader.
I can't find documentation on using MBPackage.php in this repo so I just tried to run 
 php MBPackage.php 

This produces errors.
See Actual Behaviour.

#### Expected Behavior
There should be documentation describing how to create a manifest .zip with MBPackage.php  

#### Actual Behavior
Running  php MBPackage.php  produces this error:
Warning: require_once(modules/ModuleBuilder/MB/MBModule.php): failed to open stream: No such file or directory in /Users/thomas/dev/sugarCRM/Manifests/SuiteCRM/modules/ModuleBuilder/MB/MBPackage.php on line 43

Fatal error: require_once(): Failed opening required 'modules/ModuleBuilder/MB/MBModule.php' (include_path='.:') in /Users/thomas/dev/sugarCRM/Manifests/SuiteCRM/modules/ModuleBuilder/MB/MBPackage.php on line 43

When I set php include path at the beginning of MBPackage.php
set_include_path('/Users/thomas/dev/sugarCRM/Manifests/SuiteCRM');
I get another error:
Not A Valid Entry Point

#### Your Environment
* SuiteCRM Version used: latest master branch
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):Version 66.0.3359.139 
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.5.38 
* Operating System and version (e.g Ubuntu 16.04): MacOS 10.11.6

**Comment by pgorod** [comment]
How about this, does this help?

https://docs.suitecrm.com/developer/module-installer/

If you find you still need something else, please open an Issue from that page, it will create an Issue in our Documentation GitHub, which is different from this one.

Also consider the possibility of contributing to the Documentation yourself, once you find out how to do things, the site is kept by the Community and we need help. We don't have resources to write all the Docs we need...

Please close this Issue here. Thanks
