### ISSUE TITLE
Navigation module highlighting

### ISSUE THREAD

**Issue by jobvector** [salesagility/SuiteCRM#583]
SuiteCRM currently does not highlight the module you're currently using in the navigation.

![bildschirmfoto 2015-10-20 um 12 33 47](https://cloud.githubusercontent.com/assets/15199551/10604807/59d92950-7727-11e5-94ba-381437881904.png)

improved usability:
![bildschirmfoto 2015-10-20 um 12 37 05](https://cloud.githubusercontent.com/assets/15199551/10604840/993e69e8-7727-11e5-986a-0bba0d07f892.png)

SuiteCRM Version: 7.3.1

**Comment by jobvector** [comment]
the highlighting is availibale for the Suite 7 theme but not for Suite R

**Comment by ghermans** [comment]
+1

**Comment by simbanic** [comment]
+1

**Comment by jobvector** [comment]
For now we simply impemented this feature ourselves:
1. create the following javascript file 

$(document).ready(function() {
   $("li.topnav:has(span.currentTab)").addClass("currentSelectedModule");
   $("li.topnav span.currentTab a").addClass("currentSelectedModuleLink");
});

2. create the corresponding CSS classes
.currentSelectedModule {
    background-color: #5880BA;
}
/* optional: reimplement the link underline to support the visibility */ 
.currentSelectedModuleLink {
    text-decoration: underline !important;
}

3. include both files in /custom/themes/SuiteR/tpls/_head.tpl
<link rel="stylesheet" type="text/css" href="custom/themes/SuiteR/css/highlighting.css">
<script type="text/javascript" src="custom/themes/SuiteR/javascript/highlighting.js"></script>

**Comment by ghermans** [comment]
@jobvector can you make a pull request for this?

**Comment by pgorod** [comment]
I came here to start an issue about the Top Navigation, but since this one is here already I will just add to the discussion.

This issue is more important than just a small visual detail. I find that the initial impact of SuiteCRM is considerably hindered by this, because when people first start looking at the program and trying to understand it, this unnoticeable-shifting-menu-structure is a real pain. 

I am in favor of (urgently) adding some visual differentiation, but on a more fundamental level I question whether that is the best place to have that sort of contextual menu. That is not a good place to be moving things around, because that is where users start reading the screen to look for what they need. I would say that the basic menu structure should be fixed, and any contextual, changing option would either need to be very different visually, or placed elsewhere (e.g. on the right). Possibly a differentiated text could also help ("Accounts actions" instead of just "Accounts").

Ideally it could also be visually connected to the left sidebar, because it is the same sort of thing: a contextual menu with module actions, recents and favorites. I suggest using the same icon (glyphicon-th-list) on the Top navbar, next to the text ("Accounts"), to make that visual connection.

A final idea: if you decide to keep the current module menu where it is, make it stay there permanently: instead of disappearing when we are in the home screen, just gray it out, or have some "Home actions" there also. This way users would more easily realise what the thing is.

Take your pick from these ideas... whatever looks better and is more understandable. Thanks in advance.

**Comment by pgorod** [comment]
I'm afraid this is forgotten but anyway I'd like to post my own customizations so that other people can see if they like them...

I went with this:
 
![currenttab](https://cloud.githubusercontent.com/assets/15945027/15217859/5531b578-1855-11e6-9968-5eceb80289cb.jpg)

- a very clear visual differentiation; 
- using round corners similar to the ones used in the notification "green balloon", also present on the menu bar;
- using the glyph to separate from the rest of the options, and to induce a visual connection to the collapsible left menu (with the favorites, etc).

Here's another view:

![currenttab2](https://cloud.githubusercontent.com/assets/15945027/15218223/cfb699ac-1856-11e6-893b-f6b6ba637041.jpg)

- the `currentTab` element with the new visuals is not hidden on the Home screen, for stability and comprehensibility;
- the color used is the same color used for the hover effect on the rest of the menus.

Here's the relevant part of my `custom\themes\SuiteR\tpls\_headerModuleList.tpl`

```
                        {if $name == $MODULE_TAB}
                            <li class="topnav">
                                {if $name != 'Home.DISABLED_IF'}
                                    <span class="currentTabLeft">&nbsp;</span>
                                    <span class="currentTab" style="background:#597DBC; padding: 5px 10px; -webkit-border-radius: 12px; -moz-border-radius: 12px; -o-border-radius: 12px; border-radius: 12px;color:#ffffff!important;font-weight:bold;">{sugar_link id="moduleTab_$name" module=$name data=$module}<span class="glyphicon glyphicon-th-list" style="color:#ffffff;margin-left:5px;font-weight:normal;"></span></span>
									<span>&nbsp;</span>
                                {/if}
```

This code is the lazy version, just for you to see. To put this into the actual product we would have to improve it and separate the CSS to it's proper place, remove the "if" instead of just making the condition always true, and fetch the colors from the theme definitions.

I think this makes a difference in the clarity and usability of the product.

**Comment by chris001** [comment]
:+1:  I approve!  Looks nice.
@pgorod  Could you make a pull request for this? Separate the CSS to its proper place in `themes/SuiteR`

**Comment by pgorod** [comment]
Does anybody know how to reference the Theme's default colors from within `_headerModuleList.tpl`?

**Comment by samus-aran** [comment]
Hi everyone.  I'm changing this to a bug as the theme7 & themeR are still currently supported.

**Comment by pgorod** [comment]
I would be willing to do a PR for this if anybody could help me with my question above, namely, how to properly reference the theme colors from inside the .tpl. My code snippet has a hard-coded color in there, how do I change it to whatever color is configured in Settings?
