### ISSUE TITLE
SAML Authentication fails when SAML2Authenticate ticked

### ISSUE THREAD

**Issue by poynter2** [salesagility/SuiteCRM#5885]
When SAML is setup and working OK.

Edit a user > advanced > tick "SAML2Authenticate"

SAML Authentication fails.

This looks like the external_auth_only field in the users table.

Untick and SAML works fine again.

**Comment by ebogaard** [comment]
Adding:
```
require_once dirname(dirname(__FILE__)).'/SAML2Authenticate/lib/onelogin/php-saml/_toolkit_loader.php';
```
to "modules/Users/authentication/SAML2Authenticate/SAML2Authenticate.php" again (used to be that way) is actually a 'wrong' fix to this problem. At least, that's assuming SuiteCRM wants to go more to a composer-way of loading external libraries.

The actual issue is that you upgraded the php-saml library to 3.0-dev in composer.json, instead of the stable version:
```
"onelogin/php-saml": "3.0.0.x-dev as 3.0.0",
```

This version uses some otgher class names, which breaks SAML2 authentication.

Internally, we've fixed this by setting php-saml to a working version:
```
    "onelogin/php-saml": "2.14",
```

Then use composer to get this version and have the autoloader include this.

In this commit a move is made to use composer (which specifies php-saml 2.*):
https://github.com/salesagility/SuiteCRM/commit/abb424a6a426428dd75ff0212719c1804ef2cb97

This commit is the main cause of breaking this again:
https://github.com/salesagility/SuiteCRM/commit/3f70df771fed130d3bb4be0c18961bc94804e4f3
