### ISSUE TITLE
bug with fresh clean install 7.10.6

### ISSUE THREAD

**Issue by vmijalkovic** [salesagility/SuiteCRM#6000]
I have a bug with fresh installation on empty database. It is related to reminders. It is expecting to see min and max dates but I believe the problems lies in a fact that I don't have any reminders yet. How ever this should be solved in future releases.
Will also open an issue in git hub.

Thu Jun 7 12:56:47 2018 [696][1][FATAL] Query Failed: SELECT reminders.* , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner , N'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner , N'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner , N'Users' assigned_user_name_mod FROM reminders LEFT JOIN users jt0 ON reminders.modified_user_id=jt0.id AND jt0.deleted=0

AND jt0.deleted=0 LEFT JOIN users jt1 ON reminders.created_by=jt1.id AND jt1.deleted=0

AND jt1.deleted=0 LEFT JOIN users jt2 ON reminders.assigned_user_id=jt2.id AND jt2.deleted=0

AND jt2.deleted=0 where (reminders.popup = 1 AND (reminders.date_willexecute = -1 OR reminders.date_willexecute **BETWEEN  AND**)) AND reminders.deleted=0::: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near the keyword 'AND'.

**Comment by PedroErnst** [comment]
This seems to come from Reminder.php L324, apparently the values for start and end time are null.

I wonder if this has to do with the way the timestamps are built in that function. Might not be correct for MSSQL.

**Comment by Spillo89** [comment]
so, i've find a fix for suitecrm 7.10.7, actually in Reminder.php on L323
there is the code:
`
$dateTimeNowStamp = strtotime(self::unQuoteTime($dateTimeNow));
        $dateTimeMaxStamp = strtotime(self::unQuoteTime($dateTimeMax));

        $popupReminders = BeanFactory::getBean('Reminders')->get_full_list(
            '',
            "reminders.popup = 1 AND (reminders.date_willexecute = -1 OR reminders.date_willexecute BETWEEN "
                . $dateTimeNowStamp . " AND " . $dateTimeMaxStamp . ")"
        );
`
But this code for me has no sense. Because for example, the value of
$dateTimeMaxStamp is empty cause he is trying to strtotime(CONVERT(datetime,'2018-10-02 15:41:28',120)), and this has really no sense to me. so i've fixed this by avoid using those 2 var and using directly on the where query the $dateTimeNow and $dateTimeMax and works smooth to me. Let me know if someone else with this fix has some problem.

**Comment by pgorod** [comment]
@Spillo89 normally these "unquote" functions are for security reasons. We need to sanitize any input that comes from the UI or from any other external source. Making sure it doesn't include quotes and other escape characters ensures that you avoid [injection attacks](https://phpsecurity.readthedocs.io/en/latest/Injection-Attacks.html).

So it would be better to leave those calls there, and fix whatever the real problem is. Can you provide us with examples of what your actual values are like when they go into those functions, and what they look like when they come out? Thanks.

**Comment by Spillo89** [comment]
so, i've put a log: in l321 the code is:

```
$dateTimeNowStamp = strtotime(self::unQuoteTime($dateTimeNow));
 $dateTimeMaxStamp` = strtotime(self::unQuoteTime($dateTimeMax));

  echo "dateTimeNowStamp: ".$dateTimeNowStamp." dateTimeNow: ".$dateTimeNow;

die();
```

the result is:



dateTimeNowStamp: dateTimeNow: CONVERT(datetime,'2018-10-08 09:19:52',120)

so the actual problem is the function: strtotime(self::unQuoteTime($$dateTimeNow)) because it can't convert the value CONVERT(datetime,'2018-10-08 09:19:52',120) into datetime.

so in the query(l225):

```
$popupReminders = BeanFactory::getBean('Reminders')->get_full_list(
           '',
            "reminders.popup = 1 AND (reminders.date_willexecute = -1 OR reminders.date_willexecute BETWEEN "
                . $dateTimeNowStamp. " AND " . $dateTimeMaxStamp. ")"
        );
```

there are 2 empty value in the between statment. and the log shows me:

```

Query Failed: SELECT  reminders.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , N'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , N'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , N'Users' assigned_user_name_mod FROM reminders   LEFT JOIN  users jt0 ON reminders.modified_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON reminders.created_by=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON reminders.assigned_user_id=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0 where (reminders.popup = 1 AND (reminders.date_willexecute = -1 OR reminders.date_willexecute BETWEEN  AND )) AND reminders.deleted=0

```

To fix this i've substitute the $dateTimeNowStamp and $dateTimeMaxStamp with $dateTimeNow and $dateTimeMax, and for me works.

**Comment by pgorod** [comment]
A few lines above that value is assigned:

https://github.com/salesagility/SuiteCRM/blob/master/modules/Reminders/Reminder.php#L306

It would be nice to compare what that line does in MySQL vs. MSSQL... I find your output `CONVERT(datetime,'2018-10-08 09:19:52',120)` very curious indeed... I would think we could do all the conversions in PHP, but for MSSQL it seems we're using the SQL CONVERT function instead:

https://github.com/salesagility/SuiteCRM/blob/master/include/database/SqlsrvManager.php#L299

**Comment by Spillo89** [comment]
```
Is there a way to something like:
if mysql
    do something
else
  do something else

```
?

**Comment by pgorod** [comment]
Yes, it's already in place, the generic classes are overridden in the specific drivers, that's why it behaves differently for each.

But if you mean a way to do that branch here in `Reminder.php` code, it's probably possible, but also probably unnecessary. I guess that once we're aware that `quote` is doing different things to the date value, we just rearrange our code to avoid that pitfall altogether. We don't need to rely on that.

**Comment by Spillo89** [comment]
good to know, atm i will stay with "my fix", at last i don't get any error.

**Comment by pgorod** [comment]
@vmijalkovic can you please rename the Issue to something like `7.10.6 bug with reminders on MS-SQL` ? Thanks

**Comment by FKWagner** [comment]
Hello,

I would like to push this issue, as it does hit two of my installations.
I have a bit knowlegde on PHP, so as long as you provide me with informations, I am glad to help to find out what is going wrong with PHP7, SQLSRV 17 and a SQL Server 2014.
SuiteCRM CVersion is 7.10.7

**Comment by pgorod** [comment]
☝️ If anybody in this thread can please help test the above fix, that would be helpful

Thanks
