### ISSUE TITLE
Audit module is not working in custom directory

### ISSUE THREAD

**Issue by indivar-hk** [salesagility/SuiteCRM#6029]
I am adding a different layout for Created By in view change log screen with fields (name, date_entered, created_by_name). Also changing layout for this screen. However, Its not working.

Steps followed:
1) Copy the Audit module from {dir_name}/modules and paste it in {dir_name}/custom/modules
2) make the necessary changes and its not working

Later, I removed other files and keep the necessary files (english folder, Popup_picker.html, Popup_picker.php). Still, its not working. Any help will be appreciated.

**Comment by PedroErnst** [comment]
Hi @indivar-hk 

I think this issue is more suitable to be solved on the [forums](https://suitecrm.com/suitecrm/forum/index). You will get more of a response there.

In the meantime you may consider closing this issue here. If it turns out the be an actual bug, please open a new issue, making sure to complete all the details in the issue report template.

Thanks!

**Comment by indivar-hk** [comment]
Posted in forum..Closing it from here.
