### ISSUE TITLE
& --> symbol issues

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#604]
For example, 

if will i use this symbol in case update, it doesn't save the update text after & symbol, 

same issue in reports if are you filter via parameter (if company or another module record have & symbol in name of record)

Miky

**Comment by paulgodley** [comment]
This requires a call to ecodeURIComponent before the text containing the special characters are sent to the server.  Ideally all client data being passed to the server in a URI should be encoded in this way.  I will see where this needs to be called across the project, rather than just fixing a single issue with this.
