### ISSUE TITLE
Change mail folders is not working in suitecrm 7.10.7

### ISSUE THREAD

**Issue by yassinefrikha** [salesagility/SuiteCRM#6102]
1) Go to module E-mails
2) Click : "select folder"
3) select your folder
4) the Folder doesn't change

Any one having the same Problem?

**Comment by Mausino** [comment]
@yassinefrikha for me as admin is possible to choose the folder... but for users without admin rights isn't possible to get for example group folders because they got message:

Error: There are no folders available. Please check your email settings.

Also as admin i see if push inbox/folder icon on email list view in pop up windows the bounced emails which are used for campaigns and by my opinion they shouldn't be there.

But with revamped email module are assigned here in github around 200 bug tickets.. that's to say where your issue begun. 

Only one question @yassinefrikha  Did you upgraded your SuiteCRM or is it fresh installation ?

**Comment by ltodys** [comment]
I have the same problem in 7.10.4, and I can't find resolution... I've tried QR&R and disable AJAX

**Comment by Mausino** [comment]
@ltodys @yassinefrikha  try simply hack

when you're on email listview... push the filter icon... click on clear button in pop up window and after on search button... after should the swithing between folders (email accounts) work

**Comment by frikhayessine** [comment]
@Mausino ty very much. that solved my problem. 🥇

**Comment by Mausino** [comment]
@samus-aran shold be this issue marked with some priority label. Users which don't know the hack https://github.com/salesagility/SuiteCRM/issues/6102#issuecomment-408408079 see the swiching beteween email accounts (folders) as broken and throw away whole SuiteCRM if can't access other email address folders.

**Comment by ebogaard** [comment]
Hopefully a fix for this issue gets included in the 7.10.12 'email-bulk-fix-release'

**Comment by ebogaard** [comment]
By having a look at the 7.10.12-milestone, I deducted this will be a release focussed on issues concerning working with emails. See: https://github.com/salesagility/SuiteCRM/milestone/6

**Comment by Mausino** [comment]
@samus-aran should be this issue added to milestone 7.10.12 because without this hack are changing folders/email accounts unusable for old and new users if have more as 1 email account.

**Comment by Dillon-Brown** [comment]
Taking a look at this but so far I can't seem to replicate.... Was this with personal email accounts through the user profile? @Mausino @ebogaard

**Comment by Mausino** [comment]
@Dillon-Brown 
Here are my email settings

![2018-12-29_0041](https://user-images.githubusercontent.com/5773777/50530952-4ca1f280-0b03-11e9-8fe0-31b14ff48be7.png)

And here is the behaviour of emial module in real world. Problem with hack is that one time working and one time not. Main issue is that you're  can't switch between email accounts because is still loading.. look on gif :) 

![email](https://user-images.githubusercontent.com/5773777/50531030-65f76e80-0b04-11e9-9f52-df78416c4532.gif)

**Comment by Dillon-Brown** [comment]
This should be resolved with 7.11.1, I'm now unable to replicate. Let me know if this is still an issue you can replicate and we can re-open this and investigate further. Thanks.

**Comment by yassinefrikha** [comment]
I updated to Version 7.11.15; i am still having the same problem:  i have to  push the filter icon, click on clear button in pop up window and after on search button.  I am also having a security vulnerability; when i push the "Inbox" button, i get a list of all user mailboxes and i can access individual mailboxes. An employee had access to our manager's mailbox
![Bildschirmfoto vom 2020-07-07 15-24-03](https://user-images.githubusercontent.com/35258387/86789774-f7379180-c067-11ea-87e5-f44894f0c58e.png)

**Comment by mattlorimer** [comment]
@yassinefrikha if you feel you have found a security vulnerability please email it directly to security@suitecrm.com and don't post it here, as per our security guidelines , we willremove you comment for now, thanks
