### ISSUE TITLE
Campaign wizard - step 4 (marketing) Missing required field: From Name

### ISSUE THREAD

**Issue by ichilver** [salesagility/SuiteCRM#6139]
#### Issue
Running SuiteCRM 7.10.7 Creating an email campaign and on step 4 of the wizard it doesn't matter what I put in the "From Name:" and "From Address" when I click next I get errors saying "Missing required field: From Name" and "Missing required field: From Email Address"

If this is a SuiteCRM setup issue then its not obvious by the error message.

I have gone in the Admin area and my own profile area and both have outbound SMTP setup and tested.  My account is also linked to my mailbox and I can see my emails.

Is this a SuiteCRM issue?  or have I missed something?

#### Steps to Reproduce
1. Go to Campaigns
2. Create Campaign
3. Complete Step1 - Campaign Header
4. Complete Step2 - Target List
5. Complete Step3 - Templates (I'm using a created template and added a OptOut Tracker)
6. Fill in Step 4 - But Errors out.

#### Your Environment
* SuiteCRM Version used: 7.10.7
* Hosted on an ubuntu 16.04 LTS, with Apache2, PHP7.1 FPM, MySQL
* Firefox and IE and Chrome (all does the same thing)

![capture](https://user-images.githubusercontent.com/14807477/42509929-f22e3a7c-843c-11e8-9c68-9235d8653970.PNG)

**Comment by PedroErnst** [comment]
Hi @ichilver 

It would appear that there isn't a suitable Outgoing Email Account available / configured. Otherwise it would be showing in this dropdown:

![image](https://user-images.githubusercontent.com/34056696/42818451-dee0e0aa-89c8-11e8-8b8d-c13cdd5299d3.png)

It should look show like this:

![image](https://user-images.githubusercontent.com/34056696/42818593-2e96f832-89c9-11e8-9279-052b4e671078.png)

I know from experience that the process of getting Campaigns to work with Emails can be _a little confusing_ at times...

I'd suggest taking this over to the [forums](https://suitecrm.com/suitecrm/forum/index) rather than here on GitHub, it's a much better place to get help.

**Comment by willrennie** [comment]
Closing as per @PedroErnst helpful comments and assistance, can be re-opened if deemed a bug or requiring further input.
