### ISSUE TITLE
Auto Import of Sent emails

### ISSUE THREAD

**Issue by prldoyle** [salesagility/SuiteCRM#6177]
#### Issue
Sent email are not imported into CRM (or the associated case)

#### Expected Behavior
I would expect that sent emails are import like received emails. At the moment, when looking at the emails attached to the case, it is very one sided, you can only see emails being received.

#### Actual Behavior
The sent items are seen in the sent box, but just not imported, I have tried two different email providers, Gmail and a hosted exchange server.  for more details please see this thread here: [https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/19776-auto-import-sent-emails](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/19776-auto-import-sent-emails) It was these people who pointed me here. 

I have also noticed both sent items and draft items are pointing to the sent folder, maybe this is causing an issue? a screen shot is included in the thread at the link above.

#### Steps to Reproduce

1. Send email from with client or suiteCRM
2. sent email does not get imported. 

#### Your Environment
Version 7.10.7
Sugar Version 6.5.25 (Build 344)
Ubuntu 16.04 LTS
PHP Version => 7.0.30-0ubuntu0.16.04.1
mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper

**Comment by cameronblaikie** [comment]
I'm unable to replicate this issue. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.

**Comment by prldoyle** [comment]
Thanks, I am not sure if it is still an issue, we have found a work around using exchange/outlook rules, where sent emails are copied into CRM sent folder and this is then imported. It was as issue when using the default sent item folder.

This way works better for us, as we then have control over what emails are imported in to the CRM, by using exchange/outlook rules.

Thanks for your follow up.

Regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by bjoern86** [comment]
It is still an issue. E Mails in inbox are being imported after update to 7.11.6, sent e-mails are not. Please re open this issue.

**Comment by wonich** [comment]
Yes, we can confirm it. It still exist. Also in our company... This is very important for us, for using the CRM in practise.

**Comment by Mac-Rae** [comment]
Hi @bjoern86 @wonich,

We haven't been able to replicate this issue in the most recent versions of SuiteCRM such as 7.10.x or 7.11.x. If you believe this to be an issue in these versions still, please leave a comment explaining further steps to reproduce otherwise this issue will be closed.

Thanks :+1:

**Comment by Chabi01** [comment]
Recreating the group mail account : no more success.
Back to 7.11.10 + htaccess to allow only some ip to access (must have due to "critical update in 7.11.13).
I will try other CRM solution to see if i see so much issue on upgrade for other tools : i have to find a reliable tool (even if i find SuiteCrm the best tool so far, i cannot advise people to use a tool which can lead to so much issue as soon there is an update, moveover if the update is for security issues).
Regards,
