### ISSUE TITLE
Documentation: crontab command may need to specify php version

### ISSUE THREAD

**Issue by belchfireid** [salesagility/SuiteCRM#6219]
#### Issue
Scheduler does not work if there is a different php used by crond than used by SuiteCRM. The documentation should warn the user of this.  Note that this is not a software bug in SuiteCRM; rather, just a documentation suggestion.

#### Expected Behavior
crond should kick off cron.php reliably.

#### Actual Behavior
The versions here are specific to Synology, but I suspect other users might have the same problem. 

SuiteCRM is running on php5.6.36, but it appears that when cron executes a command, php5.6.11 is used. This appears to have corrupted the stack somehow, so calls to subroutines did not return properly.  cron.php does not execute, as there is no return from entrypoint.php (on my system, YMMV)

This is what is currently recommended in the documentation and the Scheduler web page:

`*    *    *    *    *     cd /volume1/web/sugarcrm; php -f cron.php > /dev/null 2>&1 `

#### Possible Fix
Documentation should show that the crontab file might need to explicitly command the php version to use, e.g.
cd /volume1/web/sugarcrm; **php56** -f cron.php > /dev/null 2>&1

#### Steps to Reproduce
One way to check is to execute the php versions commands to see what's being done. Synology DSM 6.2 is the example here:
(this is the default, what crond will use)
```
php -v
PHP 5.6.11 (cli) (built: Jul  3 2018 21:15:18) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

What SuiteCRM is using:
```
php56 -v
PHP 5.6.36 (cli) (built: May  2 2018 16:13:10) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

#### Context
Scheduler was not working after upgrade of server hardware, including a change from DSM 5.x to 6.x. Synology made lots of OS changes in this transition. Everything was working properly, albeit slowly, before the transition.

This was hard to find, because just adding debug/log statements would change the what was happening, e.g. which routine failed to return.

In case another Synology user has questions, here is Synology's response (paraphrased):
-     This php 5.6 behavior is intended
-     There is no documentation describing it.
-     There is no plan to change it.
-     There is no plan to allow the user to change php version bindings for packages. Once installed as php5.6, you cannot change to php7.0, even if the package would otherwise allow it.

#### Your Environment
* SuiteCRM Version used: 7.10.7
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.6, MariaDB10
* Operating System and version (e.g Ubuntu 16.04): Synology DSM 6.2

**Comment by pgorod** [comment]
I seriously doubt this really needs any change to the documentation. For one, I've helped literally hundreds of people set up their cron jobs and this is the first time I've seen this very peculiar case.

Also - there should really no problem if cron executes with a different PHP version, as long as it is a supported version. It's normal for cron to execute from a different PHP environment.

So the real issue here is that there seems to be a serious bug in that version, causing it to mess up the stack. But that is a PHP issue. An old PHP issue...

So while I thank you for the nice and detailed report, IMHO this could be closed without further action. But I'd be glad to hear other opinions.

**Comment by belchfireid** [comment]
If you don't want to put it in the Scheduler web page, at least put a note in the online documentation.  This sort of thing is very hard to debug.

I have no idea if this is a PHP issue, but it doesn't surprise me that running two nearly identical versions  of PHP might result in compatibility issues.

**Comment by pgorod** [comment]
Actually it is _very_ surprising. These are different executables running different PHP files. They only come together when they access the database, but there the simultaneous access is perfectly handled (otherwise you couldn't have concurrent users).

They are not sharing any memory space, any stack, nothing. I don't think your problem is with the two different versions, I think it is with a nasty bug in one of the versions. Strictly a PHP issue, then (unless I am wrong).

**Comment by samus-aran** [comment]
I would agree with Pedro here that this is a very rare case and unfortunately unique to this particular platform. @pgorod Could we add it to the documentation site if @belchfireid is willing to add it themselves? A small note could help others but I don't think we need to explicitly state it on the code/interface.

Closing now but since you have made this public I'm sure google search can help others having this issue ;)
