### ISSUE TITLE
product image field not display anymore

### ISSUE THREAD

**Issue by mahmoudrashwan** [salesagility/SuiteCRM#6274]
#### Issue
after added a default field of product image to edit view and detailed view, the product image field became blank and non editable as there is no field beside "product image" to upload anyone. 

#### Expected Behavior
the product image field appear normal to upload images

#### Actual Behavior
he product image field became blank and non editable
![screenshot 28](https://user-images.githubusercontent.com/41969465/44965200-a408cb00-af34-11e8-9330-ba59b7a614d5.png)

#### Your Environment
SuiteCRM Version used: 7.10.7
Browser name and version: OPERA 48.0.2685.35 (PGO) (64-bit)
Environment name and version: WAMP SERVER 3.0.6 64 BIT
Operating System: windows 8.1 X64

**Comment by mahmoudrashwan** [comment]
any help ???!!

**Comment by pgorod** [comment]
Hello @mahmoudrashwan this is the kind of issue you should ask in the Forums. We need to ask you questions about your configuration, what's on your logs, your permissions settings, etc.

You should only post here on GitHub when you're sure it's a bug in the product and have some technical info for the developers.

Please close this issue here, and read the [Guidelines for posting on the Forums](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/18836-guidelines-to-post-in-these-forums), and I will help you out there.

**Comment by mahmoudrashwan** [comment]
@pgorod, I just not experienced where i have to post an issue, even i think it's not just a configure issue, because of there is no any change i have been made, the field just suddenly disappeared as picture above.
i will be appreciated if anyone can help

**Comment by mahmoudrashwan** [comment]
@pgorod  i also post the issue on forum 
https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/20312-product-image-field-not-display-anymore

**Comment by Dillon-Brown** [comment]
Closing this for now, we can re-open if this is determined to be a core issue. Thanks.
