### ISSUE TITLE
Unit Test on SuiteCRM

### ISSUE THREAD

**Issue by JoshuaQ** [salesagility/SuiteCRM#641]
Hello community, I am a sugar programmer from any year ago, and watching inside the code I think that is very difficult to progress with this open source if we don't make a common method to run Unit Test to the functionalities that we incorpore to the source, and to progress into the core.

I am doing a mini framework over QUnit to pass Unit Test to the modules of SuiteCRM. 

I am newbie in this community i don't know how you are working. I propose to open a discussion about how is the best method to implementate Unit Test in Sugar.

My code now make a iframe that communicate with Suite and i have some tools to fill the fields a check that the DetailView return the correct data. The tools simulate the click of the user, etc. All the code is on JavaScript to test all layers.

Anybody are interesting on the issue?
Please if the response is yes, i need feedback to discuss how to implement or share this mini framework.

**Comment by chris001** [comment]
Brilliant.  I second this.  Your QUnit mini framework should be a time saver for flushing out not only bugs and regressions, but also behavior discrepancies in the browers used in the field, chrome, firefox, ie, safari, edge, seamonkey, iceweasel, mobile broswers, etc.

How the application works in localized languages should also tested.  The entire UI should come up in whichever language the user requested, and Suite should be tested so that it would be proved that it does not mangle any of the user-inputted localized language charset text or data, localized collation is working as expected, and that neither while persisting to the database, nor while reading in from the database, passing thru the controller logic, and displaying on the view layer/broswer, are any of the expected characters diverging from their expected vales.

Obviously it would be great to provide base level tests, as well as data sets to populate the CRM database with a wide variety of languages, and to have new tests inherit some of the base tests abilities or settings so that copy paste syndrome would be avoided.

**Comment by JoshuaQ** [comment]
Goodness! I was beginning to think that nobody is interested in this one.

My miniframework is named Sugar Test (js namespace STest). In this moment is located in root/UnitTests/index.php 
and the Unit Test of the module are located in root/modules/TheModuleToTest/UnitTests/Main.test.js
To test a module, you need to config root/UnitTests/index.php and put a QUnit test on root/modules/TheModuleToTest/UnitTests/Main.test.js like this:

"use strict";

// This is to group the test in QUnit
module("ModuleName");

// This is a set of data to test that is saved and retrieve.
var fieldSet1 = [
    // If the field is related is needed to know the id, (in this versión, is improvable)
    STest.field.newRelateField("billing_account", "Test Account", "billing_account_id", "d9f6d2f2-b3ae-41f1-07f4-559e8c5ca882"),
    // To fill normal fields 
    STest.field.newField("name", "Test Fact"),
    // To fill fields that is not posible to check the feedback
    STest.field.newFieldNoCheckFeedback("service_name0", "Servicio 1"),
    STest.field.newFieldNoCheckFeedback("service_product_list_price0", "1000"),    
    STest.field.newFieldNoCheckFeedback("service_product_discount0", "10"),    
    STest.field.newField("shipping_amount", "123,00")
];

QUnit.test("ModuleName: Create-Load.", function(assert) {
    // Number of assertions to test. For each field to test and for each callback.
    assert.expect(4);
    // This test need control the callback to end the test when the DetailView is loaded
    STest.doneOkCallback = assert.async();
    
    // The page to Test, improvable
    STest.navigate("http://localhost/apps/index.php?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DAOS_Invoices%26action%3DEditView", cargaDatosEnNuevaFactura);
});

// The callback test when finish to load the first page   
function cargaDatosEnNuevaFactura(){
    // Click on add service line on Invoice Module
    STest.click("#service_group0addServiceLine");

    // Test the save and the feedback the fieldSet defined prevously
    STest.checkSaveForm(fieldSet1);
} 


Please i need suggestion/feedback for the method, the naming or the place to alocated the code, and how to add this utility to SuiteCRM.

**Comment by samus-aran** [comment]
suggestion superseded by https://github.com/salesagility/SuiteCRM/issues/944

**Comment by chris001** [comment]
Tests have been added to branch `feature/codeception`  by PR #3600 


For these tests to actually do the job and run on this github repo automatically and test the code, as they are intended to do, @samus-aran must do one more step, merge the tests from this `feature/codeception` branch PR #3600 to the `master`, `hotfix`, and `develop` branches.   The `.travis.yml` from `feature/codeception` contains new code needed for Travis to actually run this codeception test runner, on all of the code, every time a new PR is created against master, hotfix, develop, or feature.
