### ISSUE TITLE
JJWG Map fields shows as null in studio

### ISSUE THREAD

**Issue by vjaro** [salesagility/SuiteCRM#644]
Migration from SugarCRM CE Version 6.5.17 to SuiteCRM 7.4 makes the JJWG map fields on the modules that uses it to be displayed as null in studio

**Comment by crmwa-vincent** [comment]
Ok so the map fields seems to have been removed from the tables or better yet was not really on the tables in the first place. But i think the full definition on the extension vardef should be present so that it would be recompiled when repair and rebuilding.

Workaround script for reinstalling the map fields
<?php
 if(!defined('sugarEntry'))define('sugarEntry', true);
require_once('include/entryPoint.php');

require_once('install/suite_install/GoogleMaps.php');
install_gmaps();

require_once('modules/Administration/QuickRepairAndRebuild.php');
$actions = array('clearAll');
$randc = new RepairAndClear();
$randc->repairAndClearAll($actions, array(translate('LBL_ALL_MODULES')), true,false);

**Comment by evildotstudios** [comment]
This will be fixed on a near future. Migration is currently being rewritten.
