### ISSUE TITLE
Email module: Inline image not shown in received/sent email

### ISSUE THREAD

**Issue by afatac** [salesagility/SuiteCRM#6470]
#### Issue

See forum topic [https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/20735-email-module-why-is-the-inserted-image-not-shown-in-the-received-email](url)
#### Expected Behavior

Inline image should be shown in the email message
#### Actual Behavior

No image shown in the email message

No relevant error message found in suitecrm.log
#### Steps to Reproduce

1. Send an email with inline image using Outlook
2. View sent message in Outlook. Inline image is shown
3. View received message in Outlook. Inline image is shown
4. View sent/received message in SuiteCRM Email module. Inline image is not shown

#### Context

We use a lot of inline images in our email message when providing support to our customer. We will import/archive these messages to other modules, e.g. Case, Bug, etc. Sometimes, we need to trace back the message content directly within SuiteCRM when cross referencing with cases, bugs, etc.

medium priority
#### Your Environment

* SuiteCRM Version used: 7.10.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 70.0.3538.77 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.5.61, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): Shared Linux host

**Comment by pgorod** [comment]
Maybe the same as #6484 which was opened today.

@afatac can you please check if reverting this commit https://github.com/salesagility/SuiteCRM/commit/e840ea8968caf5c27bda2568830848b16e1ce472 solves your issue?

**Comment by drphuph** [comment]
Can confirm this issue is still present in 7.10.10 - and is pretty crippling for users who use incoming mail, for which inline images are an important feature.

Also, to add clarity to the thread, the issue is with **incoming emails**, not to email templates as suggested with the issue referenced by @pgorod - and might not have been tagged correctly by @Dillon-Brown 

Images inserted in-line in HTML formatted emails render as broken images, with the img src as: `<img src='cid:xxxxx'>`, where xxxxx is the MIME content ID of the image, which the web browser obviously cannot interpret.

The image does still create a valid record in the Notes module - requiring the user to navigate to the related note and downloading the inline image from there. (like an attachment.. but that defeats the purpose of in-line images.)

Have tested sending inline-image HTML emails from several mail clients: Outlook 2013, Outlook 2015, gmail, roundcube webmail.

**Comment by pgorod** [comment]
You're right, this doesn't seem to be related to @lazka 's Issue and PR, if this is about incoming email...

**Comment by jfd118** [comment]
This issue appears to also be https://github.com/salesagility/SuiteCRM/issues/5662

Looking forward to resolution.

**Comment by pgorod** [comment]
There's a proposed solution #7524 	

If you guys can help test that would be great. Thanks!
