### ISSUE TITLE
REST API - Prevent "Too few arguments to function SugarWebServiceImplv4" after API call

### ISSUE THREAD

**Issue by samwhatley** [salesagility/SuiteCRM#6480]
#### Issue
A previously functioning JSON API call that queries a custom field against API V4 no longer works 

#### Expected Behavior
Payload returned with response to query

#### Actual Behavior
Error 500 displayed

#### Possible Fix
Judging by other posts it's related to the reclassification of an argument missing warning in PHP >7.1 as an error that triggers the error 500.

#### Steps to Reproduce
1. Authenticate an API session
2. Send a get_entry_list call to query on a custom field, i.e:
{"session":"XXX","module_name":"AOS_Quotes","query":"custom_field_c=123"}
3. Receive 500 error message "Too few arguments to function SugarWebServiceImplv4::get_entry_list(), 3 passed in C:\inetpub\wwwroot\crm\service\core\REST\SugarRestJSON.php on line 99 and at least 9 expected in C:\inetpub\wwwroot\crm\service\v4\SugarWebServiceImplv4.php:254"

#### Context
This breaks previous functionality and renders querying/uploads of custom data not possible.

#### Your Environment

* SuiteCRM Version used: 7.10.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 70.0.3538.77 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): Windows Server 2016

**Comment by ebogaard** [comment]
The work around for now it to change:
`$max_results, $deleted`
to
`$max_results = false, $deleted = false`
in the function "get_entry_list" around row 254 in "service/v4/SugarWebServiceImplv4.php"

This is due to php 7.1 elevating 'too few arguments' to a fatal error. So this isn't a fatal error in php 7.0 and lower.
This should be fixed properly, though, as there are apparently other functions calling this with too few arguments.

**Comment by samus-aran** [comment]
1. Fix and confirm all methods have been updated
