### ISSUE TITLE
V8 API Doesn't popuplate created_by and modified_user_id

### ISSUE THREAD

**Issue by shijinkrishna** [salesagility/SuiteCRM#6483]
Issue
When a module record is created through V8 API Post request, the created_by and modified_user_id don't populate. I am on SuiteCRM 7.10.10 and the issue was found with password grant type.

Expected Behavior
The record created should have created_by and modified_by set to currently logged in user

Actual Behavior
The created_by and modified_by ids are set to null for a record created through V8 API

Possible Fix
When a user is authenticated and received access token, the $GLOBAL['current_user'] should be set to authenticated user.

Steps to Reproduce
1.Make request to Api/access_token api to get access token 
2.Now create a record with {{suitecrm.url}}/V8/module with type parameter set to any module
3. API creates a new record under the module you chosen
4. created_by and assigned_user_id are empty. 

Environment

* SuiteCRM Version used: 7.10.10
* Apache 2.4 , PHP 7.1.10 (cli) (built: Oct  2 2017 08:58:21) ( NTS )
* macOS Mojave version 10.14.

**Comment by Jason-Dang** [comment]
Currently looking at this.

**Comment by gmiweb** [comment]
I do not understand why this is closed. The global $_POST variable is empty. JSON is posted back, but you attempt to pull the username from the globals $_POST variable. I am still unable to populate the current user and the assigned_user_id field is blank in the DB for the oauth2 token. 
I am running 7.10.16 and PHP 7.2

The expected behavior should populate the id field to retrieve user from database then populate the token assigned_user_id field.

Please explain what step I am missing.  Thank you.

**Comment by vk-maurya** [comment]
I had same problem. It is because current user is not set in global variable in API. So I  have wrote this code.
```
global $db,$current_user;
$oauth2Token = BeanFactory::getBean('OAuth2Tokens', $oauth2Token->assigned_user_id);
$oauth2Token->retrieve_by_string_fields(
	['access_token' => $request->getAttribute('oauth_access_token_id')]
);
// Assigning userObject to $current_user
$current_user = BeanFactory::getBean('Users', $oauth2Token->assigned_user_id);
```
But Still in Logic Hooks not able to fetch $current_user.
