### ISSUE TITLE
rest api v4_1 giving same session id everytime.

### ISSUE THREAD

**Issue by mehulsbhandari** [salesagility/SuiteCRM#6598]
Hello Folks
Trying to login with rest api but session id is same always with all users.
Can you help on this ?

* SuiteCRM Version used: **Version 7.10.10**
* Browser name and version - **Chrome Version, 68**
* **MySQL, PHP 7**
* **Ubuntu 16.04**

**Comment by Mausino** [comment]
@mehulsbhandari maybe will help if you add here some examples of your calls + proof that the session is same for all users. 

look on documentation https://docs.suitecrm.com/developer/api/api-4_1/
**This documentation pertains to SuiteCRM versions up to v.7.9.x. Since SuiteCRM version 7.10, a brand new v8 REST API is available.**

Please close the ticket or try to find your answer on forum https://suitecrm.com/suitecrm/forum/index or create post there.

**Comment by Mausino** [comment]
@samus-aran @Dillon-Brown should be this ticket closed  and added label Question ?
