### ISSUE TITLE
Email module broken in 7.10.11 after upgrade from 7.8.3

### ISSUE THREAD

**Issue by aimran50** [salesagility/SuiteCRM#6724]
#### Issue
Upgraded an existing 7.8.3 install to 7.10.11. Email module is completely broken. Email accounts don't show. 

#### Expected Behavior
Email accounts as described in the user guide should show. https://docs.suitecrm.com/user/core-modules/emails/

#### Actual Behavior

Emails do not show. An exclamation mark on the right side shows. Clicking the exclamation shows a pop-up error saying no email found.

#### Steps to Reproduce

1. Add some group email accounts in a 7.8.3 version
2. Upgrade using the wizard
3. Emails disappear
4. 

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by cameronblaikie** [comment]
Hi there @aimran50 for right now the workaround is to delete the email and then add it back in, after that, you should be able to see and work with your emails again.

**Comment by JCucuzza** [comment]
@cameronblaikie  work around did not work for me.

**Compose Email** does not populate any emails on the **From**: drop-down.

This issue seems to reappear a few times, last time was a year ago with Issue #3741 and the work around for that was to make sure both outbound and inbound emails worked, and was closed. Now there's a pop up message instructing the user to check their in and outbound email settings. Well, my outbound and inbound emails are working according from the test. 

Can we get this fixed?

**Comment by Dillon-Brown** [comment]
@JCucuzza If the test email is successful it should display in the from dropdown assuming the user is allowed to use that account.

What kind of outbound email account were you trying to use, personal or system? if you setup outgoing email configuration in the admin panel -> email settings then you would need to also tick the "Users may send as themselves" checkbox in order for it to appear.

**Comment by JCucuzza** [comment]
Hey @Dillon-Brown  thanks for the quick response.
I am trying to send from a system (even tried a personal neither one seem to  want to appear at this point and neither seem to be populating). 

I have the outbound ticked, unless I am looking at the wrong screen and doing this completely wrong.
![capture](https://user-images.githubusercontent.com/20457759/50784368-741f5a80-127b-11e9-8bc6-a3d8dc99f6d6.PNG)
 
Also, I just noticed I'm on version **7.10.8**

**Comment by aimran50** [comment]
Sorry, I cannot provide any more information as we have rolled back to 7.8. With the steps provided, you should be able to reproduce it easily. Few others have mentioned observing the same problem.

Last year, we tried upgrading to 7.9 and faced lots of issue and had to roll back to 7.8. Will try again after 6 months or switch to something else. 

I like suitecrm, but feel that too much attention has been paid to "niceness" features and less to "robustness" features. It is sad that people cannot upgrade to latest versions seamlessly. I understand that it is open source and all but if people stop using it then what value will it be? For example, the campaign module, which is one of the most import function of a CRM, has tons of issues and they seem to remain in 7.11(based on some quick test we did).

Btw, this is a serious show stopper kind of bug and has been marked a "low priority". Really?

**Comment by Mausino** [comment]
Hi, @aimran50 you can look on #6515 where is big discussion about what you're writting
I count 25 issues which will solve in next 7.10.12 relase https://github.com/salesagility/SuiteCRM/milestone/6  almost half issues of all there

when you provide detailed crash examples or logs or screenshots or...  i think that we can move forward. Many companies/users are using 7.8 version because there is old email client is much better as current one. As you'll see it's big pressure from all to do the best and fix as much possible issues.

I will try install fresh installation of latest 7.8 version and will try to update to last version 7.10.12 if will relased. As in milestone 7.10.12 you can  see there is many issues which solving group + personal inboud email crasches and this is reason why i want test with 7.10.12 and not 7.10.11 with many bugs in this area. 

as @cameronblaikie wrote.. only workaround sometimes is delete imail accounts if  the Admin panel, select Repair and then Sync Inbound Email Accounts doesn't help.  Sorry for English

**Comment by Dillon-Brown** [comment]
This issue should be resolved in 7.10.13. Please let me know if this is still an issue you can replicate on that version and I'll re-open and investigate further. Thanks.

**Comment by aimran50** [comment]
Tried upgrading today. The email issue is not fixed. See a blank screen when I click All > Emails. The drop down on right is just a blank box that does nothing. The Dashboard > Email Dashlet shows the emails though.

![suitecrm-email-error](https://user-images.githubusercontent.com/25983194/52980341-38f66800-339f-11e9-923a-bba4e1ca260b.PNG)

**Comment by Dillon-Brown** [comment]
Hi @aimran50, this will be due to your email configuration. Do you have a personal inbound/outbound setup in user profile?

**Comment by aimran50** [comment]
No. All email accounts are set at global level via admin. No users are able to see the email module.

**Comment by aimran50** [comment]
Are the email module issues fixed in 7.11.3?
