### ISSUE TITLE
7.11 system sent email without attachments

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#6785]
#### Issue

Maybe has something similary with issue #5552

If you sent new email with attachments, you'll receive email without attachments

#### Expected Behavior

Should send attachments in email

#### Steps to Reproduce

1. Go to emial module
2. Compose Email
3. Add attachments
4. Send email

#### Your Environment

* SuiteCRM Version used:
* Browser name and version Chrome Version 71.x
* Environment name and version MySQL 5.6, PHP 7.3
* Operating System and version Win 10

**Comment by Mausino** [comment]
@Dillon-Brown i can confirm that email module in 7.11 doesn't send any attachment.. don't matter if compose email, email template, schneduled reports, documents and any other modules which want send attachment/attachments.

It's very critical issue which make again the email module unusable at all. I hope that somebody skilled find soon issue. 

I want ak @Abuelodelanada @connorshea @ApatheticCosmos if should in your free time look on it and help fix this problem.

**Comment by mgx1020** [comment]
Hi,

I know there are some other threads, I’ve checked the Email.php and it has the above already implemented, however I’m still unable to send emails with attachments. 

https://github.com/salesagility/SuiteCRM/pull/6938 Mentions this as well

Upgraded from 7.10x to 7.11.6

**Comment by kabbott-daxpy** [comment]
Trying to fix email attachments bug. Email attachments were not being send. The issue was that attachments were being saved in a funky directory, but the Emails.php code was looking for the attachments in the "upload" directory.

The steps below, fixes this and attachments are being along with the emails now.

Chante the setting for the upload_dir via the **config_ovwerride.php** file
$sugar_config['upload_dir'] = 'upload/';

In the config.php this was set to

  'upload_dir' => '5287-upload/', # at close to line 459
The '5287-upload' will vary with how your system was installed.

Ensure that the upload directory exists (create it if you need to). Also set the permissions to a+rw (chmod -R 755)

**Comment by pgorod** [comment]
For some weird reason Bitnami adds those numbers to the upload folder. SuiteCRM will never work well with this unless the `$sugar_config['upload_dir']` setting is correctly made. 

But I believe there are also a couple of bugs that make unconventional `upload` folder names break some parts of the code...
