### ISSUE TITLE
Sugar PRO references should be removed

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#6914]
#### Issue

16 files has some sort of Sugar Pro references in code as comments.
Those should be removed

#### Steps to Reproduce

Try the search with `BEGIN: pro`
https://github.com/salesagility/SuiteCRM/search?q=BEGIN%3A+pro&type=Code

`flav=pro`
https://github.com/salesagility/SuiteCRM/search?q=flav%3Dpro&unscoped_q=flav%3Dpro&type=Code

`"BEGIN: open_source"`
https://github.com/salesagility/SuiteCRM/search?q=%22BEGIN%3A+open_source%22&unscoped_q=%22BEGIN%3A+open_source%22&type=Code

#### Context

Removing references to former software in code

Related: https://github.com/salesagility/SuiteCRM/issues/5680

**Comment by asha15** [comment]
@horus68  Shall i work on this?

**Comment by pgorod** [comment]
@asha15 go ahead, you're welcome!

**Comment by asha15** [comment]
@horus68 @pgorod do i need to remove the commend and stripFlavorTags function from this file ?

![Screenshot from 2019-10-11 15-35-55](https://user-images.githubusercontent.com/28682701/66643713-ec68e100-ec3c-11e9-84ad-be1d90206d1d.png)

**Comment by pgorod** [comment]
I guess the answer is yes... Please pay attention to the locations where it is called: https://github.com/salesagility/SuiteCRM/search?utf8=%E2%9C%93&q=stripFlavorTags+&type=

**Comment by srcengine** [comment]
It looks like this has gone idle.... I can pick this up if still needed. @horus68, please let me know. Thanks!

**Comment by pgorod** [comment]
Hi @srcengine, sadly @horus68 is no longer with this project.

You can pick this up and work on it. Thanks

**Comment by srcengine** [comment]
My observations and recommendations: 
It seems like references to any sugar 'flavors' should be removed:
- from sugar_version.php, $sugar_version === 'CE', always. I do not think there are any other flavors. 
- function stripFlavorTags strips 'pro' and 'open_source' comments, but I do not think there are any of these tags left over. Therefore, I think the function stripFlavorTags can be removed or deprecated.
- $sugar_flavor influences $license_title... Therefore, $license_title should be set to 'LBL_UW_ACCEPT_THE_LICENSE' (instead of 'LBL_UW_CONVERT_THE_LICENSE')
- currently, getManifest function uses $sugar_flavor to put inside acceptable_sugar_flavors array in $manifest, which is returned by the fxn. It seem that the only acceptable_sugar_flavor now is 'CE'. Therefore, this function should only insert 'CE' as 'acceptable_sugar_flavors' 

@pgorod, please let me know your feedback, and anyone else interested. 

p.s. I am a newbie to contributing to open-source and do not have a history with suitecrm, so please bare with me :)

**Comment by pgorod** [comment]
It looks like you're doing a competent fine-grained analysis, but I am afraid I am not the best person to advise on these issues...

**Comment by horus68** [comment]
Too old to be looked at. It may still be valid, but it does not justify being open
