### ISSUE TITLE
New user password not being generated

### ISSUE THREAD

**Issue by wiatrp** [salesagility/SuiteCRM#6982]
#### Issue

Creating a new user does not generate a new password for the user and does not send a new account email. This started happening to me when I upgraded from 7.10.2 to 7.10.13
#### Expected Behavior

When a new user is created an email should be sent to the given email with a temporary password 
#### Actual Behavior

The user is being saved/created but with an empty password hash in the database
#### Possible Fix

I'm not sure what the fix is. But a few version ago when suite was still using the `Save.php` file in 7.10.2, the file `GeneratePassword.php` was being executed which generates a new password and sends an email to the user. This script is not called in the save function now and I cannot see anywhere in the user save function where a new password should be generated. 
#### Steps to Reproduce

1. Go to create new user page
2. Create new user
3. No password generated and no email sent to the new user
4.

#### Your Environment

* SuiteCRM Version used: 7.10.13
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by kockhwie** [comment]
This happen in 7.11.6 version too. But forget password is working,

**Comment by LeeAutore** [comment]
I might have the solution?  Not sure.  Fixed it on my system.  File: "modules/Users/User.php", Line 825 (the actual line of SQL Code that executes)...
`$query = "UPDATE $this->table_name SET user_hash='$user_hash', system_generated_password='$system_generated', pwd_last_changed='$now' where id='$this->id'";`

I changed it to:
`$query = "UPDATE $this->table_name SET user_hash='$user_hash', system_generated_password='$system_generated', pwd_last_changed='$now' where id='".$this->id."'";`

(because "$this->anything" anything doesn't work within double-quotes.  Only normal variables?)

Am I missing something else, or understanding this incorrectly?

-Lee Autore

**Comment by kockhwie** [comment]
@LeeAutore  Yes!! this solved the problem. Thanks!!

**Comment by kockhwie** [comment]
@LeeAutore Tried, but still not working.
