### ISSUE TITLE
Decimal points on emails template

### ISSUE THREAD

**Issue by liamvaughan** [salesagility/SuiteCRM#6991]
When doing a mail merge from a saved template which includes financials the output email is displaying as 6 decimal points rather than 2. 

The admin settings and the visible display of the decimal place is set as 2 and is working correctly its only when selecting a template.

**Comment by pgorod** [comment]
@liamvaughan please always include the full Issue template. Version numbers are very important for us because we need to try and reproduce exactly what's happening to you, and we don't have time to do it by trial-and-error.

The same goes for any other detail: which module is that template from? Are those values coming from fields? Which ones? Or are they custom fields? Which type? etc.

Just try to lead us to the point where we can make the exact same thing happen on our side, in a minute or two. That's very helpful.

**Comment by liamvaughan** [comment]
@pgorod Noted and Apologies for that.

The Version is: 7.11.0

Email is sent from a contact within an account and selecting a pre-configured template. 
The fields it is importing into the template are custom fields and they are set to Data Type: Currency marked for Audit and Inline Edit also they are importable.

The template includes the following tags which do display as the following:

Cash Price  £$account_cashprice_c
Deposit  £$account_cashdeposit_c
Part Ex £ $account_partex_c
Settlement £ $account_settlement_c

When generated these display as the following:

Cash Price  £10153.000000
Deposit  £1000.000000
Part Ex £ 0.000000
Settlement £ 0.000000

Thanks

**Comment by willrennie** [comment]
@liamvaughan I'm unable to replicate your issue. Are you able to attach a copy of your exact email template(with any sensitive/undesired information removed). Please can you also provide more detailed steps with screen shots to outline the exact process your are following in regards to navigating to and then selecting and sending your email to the contact.

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
