### ISSUE TITLE
Module Menu Filters not working after 7.8.27 upgrade

### ISSUE THREAD

**Issue by fcorluka** [salesagility/SuiteCRM#7066]
#### Issue
After 7.8.27 upgrade 'Module Menu Filters' value is not loaded (or saved).

User disables this, and everything looks OK. 
When user logout and log-in again, value is CHECKED and all modules are grouped in main toolbar.

#### Expected Behavior
Values should be saved and used when user logs in.

#### Actual Behavior
Change is visible only while user is logged.

#### Steps to Reproduce
1. Uncheck value 'Module Menu Filters'.
2. Modules are not grouped.
3. Log OUT and log IN.
4. Modules are grouped and values 'Module Menu Filters' is CHECKED.

#### Context
Horrible layout.

#### Your Environment

* SuiteCRM Version used: 7.8.24 ->upgrade 7.8.27
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):Firefox, Chrome
* Environment name and version (e.g. MySQL, PHP 7):PHP 7.2, MySQL 5.7.25
* Operating System and version (e.g Ubuntu 16.04): Linux Mint

**Comment by Dillon-Brown** [comment]
Hi @fcorluka, I'm unable to replicate this on hotfix-7.8.x or v7.8.27. I would try running a Quick Repair and Rebuild, Rebuild Minified JS Files and Rebuild JS Grouping Files.

I would also check your permissions.

**Comment by fcorluka** [comment]
Hi @Dillon-Brown ,
unfortunately none of that helps.

We have custom code in this project but everything was working perfectly in 7.8.24. Upgrade to 7.8.27. has killed 'Module Menu Filters'.

Do you know from which file are user settings pulled?
I have traced saving to User/Save.php, but can not see any values in the database?

**Comment by Dillon-Brown** [comment]
@fcorluka This would be a user preference so it would be saved in: modules/UserPreferences/UserPreference.php  ``` function savePreferencesToDB```, field is navigation_paradigm.

The database table is user_preferences, field is content but you'd need to unserialize(base64_decode()) hope this helps!

**Comment by samus-aran** [comment]
Hi @fcorluka Did you get any further with this or is this still an issue?

**Comment by fcorluka** [comment]
Hi @samus-aran,
unfortunantely i had to left this, due to deadlines, or to be precise FIX IT AND LEAVE IT.
I have disabled filters by theme (SuiteP):
themes/SuiteP/themedef.php
line 51: 'group_tabs' => false,  (originaly says 'true')

**Comment by bmwtourer** [comment]
I experienced the very same problem in test to upgrade from 7.8.13 to 7.8.30
I have the identical behavior using suiteR theme

If someone could propose fix to hard code "disable" menu filter for all I would also be interrested.

I will not upgrade to 7.8.30 and wait for fix, since this is an important problem for the users...

Your Environment
SuiteCRM Version used: 7.8.13 ->upgrade 7.8.
Browser name and version (e.g. Chrome and IE
Environment name and version (e.g. MySQL, PHP 7):PHP 7.1.7, MSSQL 2017
Operating System and version (e.g Ubuntu 16.04): windows server 2012

**Comment by bmwtourer** [comment]
I must add...  the other instance that I tried to  upgrade was a carbon copy of our production instance which has been modified somewhat...

But I am installing another site for another division and planned to go in produciton July 1st...  BUT

I started from plain unmodified 7.8.13 
worked with it without this issue
then since this is new instance, I taught "Why not install latest version?"

This unmodified instance upgrade from 7.8.13 to 7.8.30  shows the very same  behavior... 
I did not realized that untill today.

The environement is similar the hosting server is Windows 2019  php 7.2 same Mssql server

**Comment by bmwtourer** [comment]
@fcorluka  thank you for the quick fix (non upgrade safe, I understand) it worked 
for suiteR it is line 48
But please add this to the issues to be fixed...
Thank you!

**Comment by Mausino** [comment]
@Dillon-Brown i thing this is outdated issue, because version 7.8 is EOL. Should it be closed.

**Comment by Dillon-Brown** [comment]
Hi @Mausino, yes this can be closed. I'll be going through every issue this sprint and checking if they are still valid for 7.10.x/7.11.x. Thanks!

**Comment by Dillon-Brown** [comment]
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)
