### ISSUE TITLE
Bug in TemplateHandler.php

### ISSUE THREAD

**Issue by cartbar** [salesagility/SuiteCRM#7070]
#### Issue

I have been looking through the code to try to figure out how to change what is displayed in a parent field for the autocomplete and I noticed what I think is a bug in /include/TemplateHandler/TemplateHandler.php.  Currently it contains:

656                        } else {
657                            $sqs_objects[$name]['populate_list'] = $field['field_list'];
658                            $sqs_objects[$name]['field_list'] = $field['populate_list'];
659                        }

I think it should be:

656                        } else {
657                            $sqs_objects[$name]['populate_list'] = $field['populate_list'];
658                            $sqs_objects[$name]['field_list'] = $field['field_list'];
659                        }

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

Version 7.10.10
Sugar Version 6.5.25 (Build 344)

**Comment by Dillon-Brown** [comment]
Hi @cartbar, were you able to replicate this as an actual bug? it's potentially intentional, we'd need to trigger this code to check.

**Comment by cartbar** [comment]
Hello.

No, as I am still trying to figure out how the code works, but looking at the source in context, it looks wrong.

Regards,

Carl

**Comment by samus-aran** [comment]
Hi there, this has been inside the core code base since forking from Sugar. Unless there is a bug identified then this is bad naming that isn't affecting functionality. I'm closing this bug report but anyone is more than welcome to de-tangle those references to accurately reflect the end result.

https://github.com/salesagility/SuiteCRM/blob/8e51b0e900d7e8cf39529c39ab2976583c638e69/include/TemplateHandler/TemplateHandler.php#L378
