### ISSUE TITLE
"Add Field" and "New Module" within "Module Builder" are not being created.

### ISSUE THREAD

**Issue by Domiserver** [salesagility/SuiteCRM#7076]
#### Issue

The "Add Field" and the "New Module" within "Module Builder" from Admin do not create modules or fields.
#### Expected Behavior

Adding a new field or a new module within a new package should be created .
#### Actual Behavior

The New Field or New Modules are not created.

#### Steps to Reproduce

1. On the upper right, go to "Admin"
2. In Administration, go to the "Developer Tools" section and click on "Module Builder"
3. Click on "New Package" and fill in the required fileds: "Package Name" and "Key". 
4. Click on "New Module"
5. Complete the Module Name and Label fields required. Then SAVE.
6. The New Module and the New Fields were not created.

#### Context

Customization is required with new modules and fields.

#### Your Environment

* SuiteCRM Version used: v7.11.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome version 72.0.3626.121
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP v7.2
* Operating System and version (e.g Ubuntu 16.04):  CentOS

**Comment by samus-aran** [comment]
Hi there,
Not that we don't believe you its just that we have acceptance tests that run with every PR that test that exact functionality. 
I believe the problem here is that when you are in module builder you need to DEPLOY your package in order for your module/new fields to be physically created in your instance.
Just checked the documentation site... and that section needs to be completed. Perhaps jump on the forum and ask but I would appreciate it if you raise this issue on the documentation's repo so that section gets completed to avoid this confusion again.

https://github.com/salesagility/SuiteDocs/issues
