### ISSUE TITLE
API returns wrong module string address for email addresses

### ISSUE THREAD

**Issue by ltcmdrkeen** [salesagility/SuiteCRM#7080]
#### Issue
- When acquiring the Contacts via V8 API address `/Api/V8/module/Contacts`, an object is returned for each Contact that has it's relationships including the email addresses, e.g. `$contact->relationships->EmailAddress->links->related`. 
- This value points to a wrong API address, i.e. `/Api/V8/module/Contacts/{ID}/relationships/emailaddress` 
- However, the correct API endpoint is `/Api/V8/module/Contacts/{ID}/relationships/email_addresses`

- The `/Api/V8/module/Contacts/{ID}/relationships/email_addresses` endpoint then returns a wrong module name `EmailAddress` instead of `EmailAddresses`, 
- i.e. `/Api/V8/module/EmailAddress/{id}` instead of `/Api/V8/module/EmailAddresses/{id}`

**Comment by Jason-Dang** [comment]
Currently looking at this.

**Comment by Jason-Dang** [comment]
This PR https://github.com/salesagility/SuiteCRM/pull/7143 appears to resolve the issue where the lower-cased module class name is returned instead of the correct relationship link name. 

The outstanding issue is the module name not being mapped to the correct bean alias. Will be addressing and a forthcoming PR.
