### ISSUE TITLE
Custom Required Field not flagging

### ISSUE THREAD

**Issue by darthtang** [salesagility/SuiteCRM#715]
If you create a custom field and set as  required. Place it in a module.

fill out the record and DO NOT fill in the required field then it will not flag and warn the user that a required field is not filled

**Comment by axion-edusca** [comment]
Yes do that or put an automatic value to the require field in a before_save logic hook.

**Comment by samus-aran** [comment]
Using the latest 7.4.3 instance - the only fields that doesn't flag are radio buttons (those that has no 'blank' value in the list), URLs, and IFrame fields (due to them having http:// as a placeholder).

If a dropdown field has a 'blank' value in the list associated to it then it will use that as a default and will flag if nothing else has been selected - this looks like logical behaviour.  However,  it will not flag if there is no 'blank' value in the list, but due to nature of the dropdown the first value will be considered the default.  This also seems like logical behaviour.

The only illogical behaviour is if a radio button that doesn't have a 'blank' value in the list then the required flag will fail as no value has been 'selected' unlike the nature of a dropdown field.

@axion-edusca Can you explain your scenario in abit more detail?

**Comment by aureh12** [comment]
Any news about this ? Required message for Radio custom fields still not show on form validation on SuiteCRM Version 7.11.2

**Comment by pgorod** [comment]
@aureh12 	
Does the [proposed fix](https://github.com/salesagility/SuiteCRM/pull/4319) work for you?

**Comment by aureh12** [comment]
Hi. No. It doesn't. 




Aurélien







On Mon, Apr 1, 2019 at 12:01 AM +0800, "pgorod" <notifications@github.com> wrote:












@aureh12

Does the proposed fix work for you?
