### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by Petrouchka** [salesagility/SuiteCRM#7326]
In the french version there's a translation error in th efrench version : http://www.numopen.fr/crm/index.php?module=Home&action=About

"Tout le code de SuiteCRM, géré et développé par ce projet, seras publié"
->
"Tout le code de SuiteCRM, géré et développé par ce projet, sera publié"

**Comment by Dillon-Brown** [comment]
Hi @Petrouchka, this would actually be handled on [crowdin](https://crowdin.com/project/suitecrmtranslations) as we don't store or translate language packs on GitHub. I think you should be able to request to join the particular language to correct it yourself or use the contact buttons on the right to let them know. Thanks!

**Comment by horus68** [comment]
Fixed on Crowdin. @Petrouchka please join to improve french translation https://crowdin.com/project/suitecrmtranslations/

**Comment by Petrouchka** [comment]
Still wrong in version 7.11.10.

**Comment by horus68** [comment]
The translation its fixed in Crowdin for 6 months. But its not updated into your installation unless you act on this. You need to:
1- In SuiteCRM Logout / login with ENGLISH language
2- Go to Admin, remove the french language pack from your system
3- Download new language pack from Crowdin  https://crowdin.com/project/suitecrmtranslations
4- Install the new zip language pack into your system
5- Logout / login with French language!

**Comment by Petrouchka** [comment]
Thank you for the help. I updated the language pack but have still the error.
Perhaps because I can't remove the old language pack (see screenshot).

![lang](https://user-images.githubusercontent.com/3955499/70415677-7d054700-1a5d-11ea-97de-460f7b6c60eb.png)

**Comment by horus68** [comment]
Now the question is a different issue on "How to completely remove a language".
Notes: You should hide PHP error messages. You also need to delete your browser Cache too.
Please use the forum to ask for help fixing your system.
https://community.suitecrm.com/c/suitecrm-forum-english-language/translation-and-language-packs
