### ISSUE TITLE
email send notification

### ISSUE THREAD

**Issue by muratdogan1** [salesagility/SuiteCRM#7493]
hi there

we use suitecrm 7.11.5

we set all mail setting.
when the reply all activities, I wanna send email notification automatically.

example ;

when the reply support records, the system doesnt send email.
when the close support records,  the system doesnt send email.

**Comment by samus-aran** [comment]
Hi there, 
I know following the bug report guide is time consuming but so it the back and forth of asking for more information...

Ok, lets start from the top.

"When the reply all activities, I wanna send email notification automatically".. What do you mean all activities?
Do you currently know what activities already send out email notifications? Depends on the trigger. The following triggers are: Assignment (when a record is assigned to someone), When an external contact responds to a Support Case (this is using Monitoring Inbound Mail Box, and AOP settings), When a CRM User responds to a Support Case via the interface (Using Outgoing Mail Box and AOP settings). I'm sure there is a closed case trigger (thought this can easily be done by Workflow).

So yes, you should do the ones you have asked for as an example out the box. Any additional 'activities' you can set up a workflow for them.

Regards to the actual issue of 'the system doesn't send email' is that because you have set up AOP, or have actually tested the email settings? This is where we need more information and following the bug report guide would've helped us.

P.S have you had a search if anyone else had this issue here?
