### ISSUE TITLE
Update to CLA using CLA Assistant

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteCRM#7579]
#### Issue
Right now SuiteCRM is using [clahub](https://github.com/clahub/clahub) which hasn't had a new commit in ~2.5 years. We should switch to [CLA Assistant](https://github.com/cla-assistant/cla-assistant) because it's actively maintained and because it supports whitelisting bot accounts, which is necessary if we want to merge PRs from Dependabot.

cc: @Dillon-Brown

**Comment by connorshea** [comment]
CLAHub has now been down for over 2 weeks, so we should switch over if we want to continue to have CLA-signing.

**Comment by samus-aran** [comment]
Just an update that it looks more likely we will go with CLA assistant but on our own hosting (learning from the mistakes haha). Please bare with us whilst we whip this up :+1:

**Comment by samus-aran** [comment]
Just to confirm that is the CLA assistant is now in place and supplying us with a PR check. :partying_face: 

We were in a situation that we were only able to obtain a record of those that successfully contributed to SuiteCRM i.e. merged into master or other branches so there may be a chance that you will have to re-sign the CLA on your PR. Don't worry, the same CLA agreement was used and if you do have issues re-signing please feel free to reach out to the community team and we can cross reference your existing application.

Apologies if you have received multiple emails due to the CLA assistant checking all open PRs we hope it wasn't too much of an inconvenience. :bowing_woman:

**Comment by tsmgeek** [comment]
I've previously had PRs accepted, just got loads of emails but it does not show anything other than Version. Seems it needs fixing or if someone can just approve my account from prior commits.

**Comment by samus-aran** [comment]
@tsmgeek Ahh looks like the bot hit the API limit (due to the rechecking of PRs)

Let's wait until the limit resets and check again (which would explain the 'version' only showing up.  You should ideally see the below). But I'll add your name to the list to import and we'll re-check (after the limit wait).

![Screenshot_2020-08-27 CLA assistant_doc](https://user-images.githubusercontent.com/4041275/91452088-18ea1380-e876-11ea-81a2-32db9188c523.png)
