### ISSUE TITLE
Timezone issue for Meeting reminders

### ISSUE THREAD

**Issue by vjaro** [salesagility/SuiteCRM#766]
Steps to reproduce:
1. Change user timezone settings to GMT+8
2. Create a meeting
3. Add 4 reminders with 15,10,5,1 minutes prior popup reminders.

Expected result 
the desktop popup notifications will appear.
Actual result
Waited for all the reminders to popup but no reminders were displayed.

Now when i update my user timezone settings to UTC and did the previous steps, the reminders started displaying correctly as per defined on the popup reminder time.

**Comment by KhyberPass** [comment]
As of 7.4.3 reminders for Calls and Meetings do not work correctly unless the user’s time zone is set to UTC. If the user’s time zone is set to say Europe (UTC+1) the reminder will trigger 1 hour later.

Some details, as part of the Reminder enhancements for 7.4.3 it looks like code was copied from include/javascript/jsAlerts.php to modules/Reminders/Reminder.php, however the code in jsAlerts queried date/time directly from the database where time is UTC, whereas Reminder was changed to use the Bean which returns time in the user’s time zone.

This problem is also present in 7.5.1. A patch fix will be posted soon.

**Comment by armadillotec** [comment]
In the 7.5.1 doesn't take timezone from php.ini
