### ISSUE TITLE
Case Type Dom Does Not Appear on the Right Within the Drop Down Editor

### ISSUE THREAD

**Issue by greenlanegreb** [salesagility/SuiteCRM#7755]
Is not a currently logged issue as far as I can see (presumably new bug introduced in the upgrade from 7.11.7 to 7.11.8. Note: I have customised my drop downs as per the intended functionality of the drop down editor. 

 
Is not a security issue. 

Issue - As Above. 

Provide a more detailed introduction to the issue itself, and why you consider it to be a bug --> It appeared there before, now it doesn't. Likely to cause even more problems with the portal module than there already was before. 

### Expected Behavior
 
Should appear on the right within drop down menu editor. 

### Actual Behavior 
Doesn't but is available on the left but will not drag across. 
 As Above. 
 
Haha - it produces 28 pages an hour of errors - see here https://pastebin.com/K1CN8GDK

### Possible Fix
 
To check over the code please, assess priority based on complications from the error across other parts of the system please and prioritise accordingly. 

### Steps to Reproduce
 
N/A

N/A

1. Log in as an Administrator
2.Go to Administrative Menu
3.Select Drop Down Editor. 
4.Look for it on the right and notice it is not there. 

### Context
 
It is difficult to tell with the amount of issues with the portal system and the case from Email setup, particularly given the lack of coverage in the forum that the only logical way of dealing with anything is to deal with everything that is wrong by first researching it and then, if appropriate, reporting it. 

<-- If you feel this should be a low/medium/high priority then please state so --> Not sure. 

### Your Environment
<-- Include as many relevant details about the environment you experienced the bug in -->
* SuiteCRM Version used: 7.11.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 76.0.3809.100 (Official Build) Built on Ubuntu , running on LinuxMint 18.3 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0.33 - 10.3.15-MariaDB-1 - Debian 10 Apache 2.4.28 (Debian)
* Operating System and version (e.g Ubuntu 16.04): As Above.

**Comment by samus-aran** [comment]
Hey @greenlanegreb 
I think your formatting of the issue template is abit broken. Do you create this via a particular browser? I'll update it abit to make it abit more easier to read.
Anyway, onto the issue.

Are you able to provide a screenshot of what the issue is.

This is what I see on 7.11.8 Drop Down Editor via Admin Panel > Drop Down Editor
![Screenshot_2019-08-27 SuiteCRM](https://user-images.githubusercontent.com/4041275/63769576-118ed380-c8cb-11e9-9f64-c5e3ed41d93a.png)

**Comment by samus-aran** [comment]
Oh, I think you are expecting it to drag & drop similar to the Studio?.
Nah, you simply click the name of the drop down list and it should take you to the 'Edit Dropdown' page seen in the above comment.

![Screenshot_2019-08-27 SuiteCRM(1)](https://user-images.githubusercontent.com/4041275/63770089-46e7f100-c8cc-11e9-83c0-fe1455cc79e5.png)

Or you can simply click on the name on the left hand panel too. There isn't drag and drop here.

**Comment by greenlanegreb** [comment]
Hello, thanks for this. I've been reading today's chat in the main developer's channel (after responding to your forum post) we're not a million miles away on the wider issues. I don't understand why there is a repeat of items available within the drop down editor both on the left or right unless the one's on the right are supposed to be active and the one's on the left aren't. In any event, since the 7.11.8 update (or since I manually deleted the options in the case type dom and I just didn't notice) the case type dom has disappeared from the right. If they are both active and work the same, what is the objective or listing them twice? Thanks.

**Comment by greenlanegreb** [comment]
I there a temporary fix for this please so i can rule it out from causing any further issues. Naturally i'll report back anything useful to add to this report (same as the others). Thanks.

**Comment by samus-aran** [comment]
If you are able to see the case_type_dom hyperlink on the left hand side then you should still be able to access it by clicking it. Regards to the lack of the item on the right (actually I would refer this to the middle panel) can I ask for a screenshot of what you see so I can identify that it is missing between case_status_dom and charset_dom.

The interface is hasn't seen much extension since SugarCRM but it was a template adopted from the Studio & MOdule Builder which has similarities.

**Comment by greenlanegreb** [comment]
Hi Ashley, 

Thanks for your message - sure it is technically the middle - I just mean, comparatively (from the list on the left) it is to the right of it. 

Here's a rather basic screenshot where I've tried to make it just a touch easier to see - you'l see that the case type dom is in the list on the left but not on the right anymore. I'm more concerned that it will affect functionality - as I say, there must be a difference between the items on the left to the items on the right or there is no point in replicating them so I am concerned about the wider implications. I'm going out for a break from my laptop this evening (hopefully if I can get my backside in gear and i'm going to need to start researching other solutions so I will be less active on the forums at least temporarily and, as I'm sure you will understand, permanently if I end up using an alternative project to try and help the tenants as I will likely need to contribute on an ongoing basis to an alternative project. I can't code so I can't move forward but I have posted a clear brief of what I was trying to do in the forum. I will keep you up to date and I have pulled a copy of the cases with portal page and added in a section on what the portal cannot do out of the box and an invite to developers to help with it. I'm no good at the indented lists using stars so it will need a little tidying. Thanks.

**Comment by samus-aran** [comment]
Hey @greenlanegreb I think they one is an easy fix. I can see a few are 'missing' but actually I really think that due to your screensize that you need to scroll to the right to see the three columns within the middle section - try grabbing that green bar at the bottom and scroll right. What you can also do is hide/minimise that furtherest right panel to give you more room - they by click on that > icon slightly above and across from the 'Help' title. 

Sure, as I said you are free to explore software and whatever suits your needs then thats great. 

Regards to the differences, there isn't any functional differences, just bad usability.

**Comment by greenlanegreb** [comment]
Quite right! I should have noticed that - my bad. Thanks. I've updated my reply to you on the forum but I didn't understand one of your key questions so i've highlighted that there.

**Comment by samus-aran** [comment]
Glad that help. I'll close this issue then.
