### ISSUE TITLE
Need to disable ajax loading for all modules

### ISSUE THREAD

**Issue by efrgithub** [salesagility/SuiteCRM#776]
After upgrading from suitecrm 7.4.1 to 7.4.3 i needed to disable all ajax modules in the system settings. No list would load. All give error: There was an error processing your request, please try again at a later time.

apache error.log show something like
PHP Catchable fatal error:  Argument 1 passed to Reminder::isDecline() must be an instance of SugarBean, boolean given, called in D:\\Bitnami\\sugarcrm-6.5.20-2\\apps\\sugarcrm\\htdocs\\modules\\Reminders\\Reminder.php on line 299 and defined in D:\\Bitnami\\sugarcrm-6.5.20-2\\apps\\sugarcrm\\htdocs\\modules\\Reminders\\Reminder.php on line 374,

**Comment by ArsalanThange** [comment]
The same issue has been happening to me as well. It started after I scheduled a meeting to test the notifications. Once the time elapsed and I deleted the meeting, it started giving ajax errors on all the modules.

**Comment by danfreid** [comment]
Same issue.  Cleared browser cache, error went away.

**Comment by TheFlyinGeek** [comment]
Same problem here, just out of the blue. Clearing browser cache didn't work for me, disabling Ajax module did

**Comment by TheFlyinGeek** [comment]
Actually disabling Ajax only partly fixed the problem. While I could load my modules again, non of the module's subpanels were loading. I found this post: https://suitecrm.com/forum/installation-upgrade-help/234-ajax-error-after-upgrade?start=15#27281 and that fixed the problem.

Now the question is, is this fixed in 7.5? (I'm still on 7.4.3)  and are there any consequences by removing this part of the code?

**Comment by davenz** [comment]
Confirming the same behaviour here, and also concurring with ArsalanThange that this only appeared after testing the meetings notifications – which, ironically, I was checking out for an earlier fix (https://github.com/salesagility/SuiteCRM/issues/476).

**Comment by mattlorimer** [comment]
This issue is fixed within 7.5+
