### ISSUE TITLE
missing field into workflow

### ISSUE THREAD

**Issue by fabiogiovannelli** [salesagility/SuiteCRM#797]
Hi,
I've found a possible bug on version 7.3.1 (installed on our On:Demand instance): when creating a new workflow entry in order to update the Security Group of an Account, the text box which should allow to enter the value is missing.

On Premise instance - WAI
![on_premise](https://cloud.githubusercontent.com/assets/16338737/11874825/d91e244e-a4e1-11e5-9976-bec216ed4134.png)

On Demand instance - missing field
![on_demand_full](https://cloud.githubusercontent.com/assets/16338737/11874827/d928bc1a-a4e1-11e5-95c8-91fde4cc640a.png)
![on_demand_detail](https://cloud.githubusercontent.com/assets/16338737/11874826/d925dce8-a4e1-11e5-9423-57ed0873773c.png)

Regards,

Fabio Giovannelli

**Comment by willrennie** [comment]
You should select the Account module as the Record Type when creating the 'Modify Record' action, not the Security Group module. Otherwise you are trying to relate a security group to another security group within an Account module workflow, which will not work. The field appears if you select the Accounts module for the Record Type.
