### ISSUE TITLE
Any module-Filter resets after dates are added and columns are sorted out!

### ISSUE THREAD

**Issue by itglaafs** [salesagility/SuiteCRM#8008]
Amy module-Filter resets after dates are added and columns are sorted out!

#### Issue

We were sorting out from newly added columns in Accounts list view and noticed that filter resets always showing full numbers of Accounts or those filtered by any other fields type but "Date". The problem is that we have many date fields in search view and that it should be normal that you can sort columns without resetting the whole filter.

#### Expected Behavior

The column sorting should work regardless of what field type you are using in search filter.
#### Actual Behavior

The column sorting and date type filtering does not work together.

#### Steps to Reproduce

1. Go to any module or Accounts, use simple/advanced filter and choose any date field that you want to filter out on your records
2. Try to sort columns on the list view below with your search filter previously added
3. The records will reset showing the default number of Accounts or the number you have filtered out with any other field type but "Date" type

#### Context

Sort columns on the list that I have filtered out previously

#### Your Environment

* SuiteCRM Version used: 7.8.8 LTS
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 69.0.2
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.6, MySQL 5.6.31
* Operating System and version (e.g Ubuntu 16.04): Windows 10

**Comment by Mac-Rae** [comment]
Hi @itglaafs,

We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x as such this issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. 
If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post ](https://suitecrm.com/7-8-x-end-of-life/)

Thanks :+1:
