### ISSUE TITLE
version 7.11.9 upgrade to 7.11.10 - Font less legible and less accessible

### ISSUE THREAD

**Issue by FR-TA** [salesagility/SuiteCRM#8247]
#### Issue
There has been a change to the font on lists which is less legible in version 7.11.10
It is thinner, more squat and as a result less accessible when viewed for a Disability Discrimination point of view

If this is a step in readiness for move font and type size selection into the Administration area, then can it be reversed until that is complete

If it has been done in error can we reverse as soon as possible please

If it is a bug in the upgrade, how can it be fixed now?

**Comment by pgorod** [comment]
Which version are you upgrading from?

There have been no significant style changes in the latest versions, so you must be having some technical problem. If you could post more information, and perhaps a screenshot, that would be helpful. 

There is a know issue related to fonts, this one #8175, maybe you can check if that's what you're getting.

**Comment by craigpanton** [comment]
I've taken a look at the 7.11.x-7.11.10 installer and it looks like the font files are being populated so unlikely to be related to #8175. 

Just to confirm, was the font appearing correctly in 7.11.9 for you? It may be worth clearing your browser cache and rebuilding the JS files to see if that helps.

**Comment by FR-JS** [comment]
Just to expand on what @FR-TA posted.
It turns out that the cause of the issue is related to #8175 as all the Lato font files were 0 bytes. Since it's been happening for some time, through the updates it would seem that people have assumed the fallback Arial font was what it was supposed to be. I have the desktop fonts installed so it looked no different to me.

I can confirm that the installation of 7.11.10 has been the first update in a while that hasn't broken the fonts, so as far as the corrupt font issue goes I would say it's fixed.

As far as the accessibility issue goes, I do agree that 12px used on list views does strain the eyes a little unlike the 14px used on the detail views, especially when using the Suite P Day theme which is grey on grey text.

**Comment by craigpanton** [comment]
@FR-JS Thanks that is a useful suggestion - we are currently in the process of making a high contrast theme. We will take your feedback into account for this. 

In the meantime, you could potentially try out the other available sub-themes for a greater colour contrast. If you would like to use the older font, an option would also be to remove the Lato font files.
