### ISSUE TITLE
SuiteCRM 7.11.10 release Reports not show Conditions

### ISSUE THREAD

**Issue by germango** [salesagility/SuiteCRM#8455]
#### Issue
I was created reports in 7.2.2 SuiteCRM version.  Upgrading to 7.11.10 Reports not show fields in the Conditions tab, only shows a "( ... ) Drop parenthesis" button than makes any thing.  Then is not possible to filter report results.

#### Expected Behavior
Be possible to add fields with conditions in a Conditions tab to filter Report results

#### Actual Behavior
Not to add fields in Conditions tab Reports module.

#### Possible Fix
I have not possible fix

#### Steps to Reproduce
Simply enter to Reports module and try to create or view Conditions in edit mode.
#### Context
SuiteCRM 7.11.10 release

#### Your Environment

* SuiteCRM Version used: 7.11.10
* Browser name and version Chrome Version 79.0.3945.117 (Build oficial) (64 bits)

Hosting Godaddy Package | Ultimate
-- | --
cPanel Version | 78.0 (build 38)
Apache Version | 2.4.41
PHP Version | 5.6.40
MySQL Version | 5.6.44-cll-lve
Architecture | x86_64
Operating System | linux
Dedicated IP Address | 23.229.190.97
Local IP Address | 23.229.190.97
Path to Sendmail | /usr/sbin/sendmail
Path to Perl | /usr/bin/perl
Perl Version | 5.10.1
Kernel Version | 2.6.32-954.3.5.lve1.4.66.el6.x86_64

**Comment by Mac-Rae** [comment]
Hi @germango,

We haven't been able to replicate this issue in the most recent versions of SuiteCRM such as 7.10.x or 7.11.x. I would suggest remaking the reports in the new version where they should work for you. If you believe this to be an issue still, please leave a comment explaining further steps to reproduce otherwise this issue will be closed.

Thanks :+1:
