### ISSUE TITLE
Accept Status does not save on lead

### ISSUE THREAD

**Issue by duncanf95** [salesagility/SuiteCRM#8495]
#### Issue
Accept status on lead does not save its value when it should.

#### Expected Behavior
I should be able to select a accept status on a lead and when I hit save it should save along with the rest of the record data

#### Actual Behavior
when I hit save it does not save the accept status, leaving it blank on the detail view

#### Steps to Reproduce
1.create new lead record
2.select accept status
3.hit save

#### Context
I cannot see the status of leads, I do not know whether they have been accepted or declined
I feel this hsould be a high priority as all info on a record should save

#### Your Environment

* SuiteCRM Version used: 7.11.10
* Browser name and version Chrome 64bit
* Environment name and version (MySQL, PHP 7.2):
* Operating System and version (e.g Ubuntu 18.04):

**Comment by pgorod** [comment]
It sounds like you have a customized system, is that it?

This is what I see in the live demo:

![image](https://user-images.githubusercontent.com/15945027/73613738-69570680-45f0-11ea-9307-24b3bb2dd135.png)

.. no "accept" status there.

This is possibly changed in Admin / Dropdown Editor / `lead_status_dom`

Now, those customizations need to be carefully considered, because that field is used in the CRM code, mot just as data/labels.

**Comment by duncanf95** [comment]
Hey sorry for taking time to reply to this as I thought it was just a standard field. It is a core field but is not included in the standard layout. If you go into studio you can add the field to the layouts but it does not save. I believe this is because it lacks a proper VarDef. As this isn't included in the standard layouts I think this should be a low priority bug.

**Comment by pgorod** [comment]
@duncanf95 I still can't understand what field you're talking about. In a freshly installed 7.11.10, Leads module, Fields, I don't see any field called `accept_status` or similar.

In Dropdown editor, I see `dom_meeting_accept_status` but this has nothing to do with Leads...

**Comment by duncanf95** [comment]
@pgorod it does not appear under the fields, I believe this is part of the bug. If you go into layout editor for leads then it is in the layout editor as an optional field

**Comment by pgorod** [comment]
Ok, I am starting to understand now, thanks.

This is the field definition: https://github.com/salesagility/SuiteCRM/blob/master/modules/Leads/vardefs.php#L324

It's a `non-db` field, so no wonder it doesn't save. It's meant to be something calculated when displaying in a view, not actual data, only _based_ on something in the database. Although I couldn't find out how it is actually used...

It should probably have been marked with `'studio' => false` as the other related fields above it...

By the way, what exactly are you trying to achieve? This does seem related to accepting Meetings, why don't you do that in the meeting record? It doesn't make sense to just put this in a Leads edit view, since a Lead can be related to many Meetings.

**Comment by duncanf95** [comment]
Ah that makes more sense, thanks for the calrification. This was a field a client requested to be a part of the view so I'm not entirely sure why they wanted it. I will make sure to pass this on to them though to see how they want it to work. It probably should not be part of studio if it is not intended to be edited on the record. Thanks for getting back to me
