### ISSUE TITLE
Since upgrade from 7.4.3 to 7.5 issues

### ISSUE THREAD

**Issue by nathancani** [salesagility/SuiteCRM#853]
Hello; We just installed the update from 7.4.3 to 7.5

The unified search has stopped working
Aswell as the Dashlets, Upgrade Wizard

All of the pages go to a blank white page.

**Comment by CaptainChainsaw** [comment]
Is there any relevant information in the log file that you can supply?

**Comment by nathancani** [comment]
Hello Captain Chainsaw

 

Unfortunately it doesn’t say anything whats so ever;

The dashlets just go blank and the upgrade page doesn’t want to load; Doesnt even try to load

 

Thanks

Nathan

**Comment by willrennie** [comment]
Have you run the recommended permissions for your environment? Have you turned on PHP error reporting?

**Comment by willrennie** [comment]
This issue should now be resolved in SuiteCRM 7.5.1, can you confirm?

**Comment by shoaib-fazal16** [comment]
Issue still persists.

**Comment by willrennie** [comment]
Can you please provide more details. What did you upgrade to/from, what are your environment details, what errors are outputted in the log files etc?

**Comment by willrennie** [comment]
As we have not received feedback for over a month on your issues, noting these issues should be resolved in the latest release such as your blank upgrade wizard/homepage, I would recommend that you post on the community forums providing more details about your issue with environment/version details so that we can progress your issue further: https://suitecrm.com/forum/index
