### ISSUE TITLE
Favorites adds record twice to the sidebar and to the db

### ISSUE THREAD

**Issue by joshscorpion** [salesagility/SuiteCRM#9078]
Hi,

I am using SuiteCRM 7.11.18 and php 7.2, on Apache and Ubuntu.

The issue I have is that when I open an Account/Contact/etc and select it as a Favorite (by clicking the star next to the name) and I refresh the page, 2 Favorites (of the same link) are added to the sidebar.

When I go directly to the database, I see that indeed added 2 instances of the same Favorite, instead of only once as it should.

I've been looking through all the cases in this github, didn't find anyone else that reported the same issue.

Any ideas?

I am not a developer, any help is really appreciated.

Many thanks
Josh

**Comment by pgorod** [comment]
This issue is related to JS events firing twice and it affects other things. Sometimes it only appears after loading a record through the Ajax mechanism (for example, entering a detail view form the Recently Viewed list on the sidebar).

I can see the Favorites creation requests doubled in the Network tab of the browser; and I can also see duplicate requests for **inline editing** when I double-click on a field. 

My own code is also having trouble with this: JS code injected in AfterUI hook executes twice. So when I add an action button on top, sometimes I get two buttons...

There are probably other manifestations of this same bug which we're not seeing yet...

**Comment by pgorod** [comment]
In my case, I think this bug was my fault, not SuiteCRM. Double JS injection.

@joshscorpion do you still get this issue? Do you have any JS customizations? Any specific add-ons installed?

**Comment by joshscorpion** [comment]
@pgorod I doubt this bug is your fault, its something within SuiteCRM that is triggering the double  JS injection.

Even before I added the add-on from Dynamic Dropdown(Urdhva Tech) we already had this issue.

We were with SuiteCRM 7.11.15, not too stable, then moved to 7.11.17 and now on 7.11.18, which is working very reliably.

Our SuiteCRM 7.11.18 addresses many of the issues covered by 7.11.19.

Our PHP is v7.3 as SuiteCRM 7.11.18 is compatible max to PHP 7.3.
