### ISSUE TITLE
Source size on github is about half of the sourceforge linked on suitecrm.com

### ISSUE THREAD

**Issue by merlinthemagic** [salesagility/SuiteCRM#9107]
Hi,

Not sure what to make of this, just noticed that when i go to [https://suitecrm.com/download/ ](https://suitecrm.com/download/ ) download the latest version i am linked to [https://sourceforge.net/projects/suitecrm/files/SuiteCRM-7.11.19.zip/download](https://sourceforge.net/projects/suitecrm/files/SuiteCRM-7.11.19.zip/download)

The downloaded file (SuiteCRM-7.11.19.zip) is 75,903,399 bytes

If i go to github [https://github.com/salesagility/SuiteCRM/releases/tag/v7.11.19](https://github.com/salesagility/SuiteCRM/releases/tag/v7.11.19) and download the same release [https://codeload.github.com/salesagility/SuiteCRM/zip/refs/tags/v7.11.19](https://codeload.github.com/salesagility/SuiteCRM/zip/refs/tags/v7.11.19)

The downloaded file (SuiteCRM-7.11.19.zip) is 35,058,353 bytes

I dont know if sourceforge has a shady rep anymore but thought i would raise the issue here.

**Comment by Dillon-Brown** [comment]
Hi @merlinthemagic, this is expected. The SourceForge download that we link to on the download page is a "production ready" package in that it's ready for immediate deployment. 

The GitHub download will give you the same release but without including the ```vendor``` and ```cache``` directories. You will need to generate these yourself by running ```composer install --no-dev``` and going through the install process. Since these are autogenerated files they aren't something we would want to track with ```git``` and include here on GitHub.
