### ISSUE TITLE
Global search returns no results

### ISSUE THREAD

**Issue by Yousuf-Said** [salesagility/SuiteCRM#9143]
#### Issue

The global search could not retrieve any data for ‘Target’, ‘Target List’, ‘Case’ and ‘Project’ modules. 

#### Expected Behavior

Search Results displayed
Search result page is displayed with the name of the Target being displayed.

#### Actual Behavior

global search could not retrieve any data

#### Steps to Reproduce

1. Type "Soma Yun" in search-query-string Textbox
2. Click Global Search Button

#### Your Environment

SuiteCRM Version used: 7.11.19
Browser name and version: Version 90.0.4430.212 (Official Build) (64-bit)
Environment name and version (e.g. MySQL, PHP 7):
Operating System and version (e.g Ubuntu 16.04): MS Windows 10 pro

**Comment by johnM2401** [comment]
Hey there, 
I don't think I'm able to fully replicate, I'm afraid.

I'm able to see results from those four modules on both Basic and Advanced Search, once they've been added to the Searchable modules, (Admin->Search Modules):

(Basic Search v)
![image](https://user-images.githubusercontent.com/13675281/119503158-90e05e00-bd62-11eb-8b09-7152d957f7d4.png)

(Advanced Search v)
![image](https://user-images.githubusercontent.com/13675281/119503207-9d64b680-bd62-11eb-9292-decd5016968b.png)

Which search method are you using?
I believe they do search through different methods, so it would be good to know if this issue is specific to one, or more, of the Search Methods.
(For example, I get fewer results from Advanced Search, if my search term is less of a match. (Lower Search Score))


Could you perhaps provide some screenshots, or further steps to replicate?
Thanks!

**Comment by Mac-Rae** [comment]
Closed as unable to replicate
