### ISSUE TITLE
AOR_Reports with "Date" type conditions faileds

### ISSUE THREAD

**Issue by macala** [salesagility/SuiteCRM#917]
When AOR_Report contain the "Date" type conditions like on the screenshoots:
![report_fields](https://cloud.githubusercontent.com/assets/15381196/12843291/a352ee92-cbf8-11e5-98fa-5fe0b73d1f48.png)
![report_conditions](https://cloud.githubusercontent.com/assets/15381196/12843294/a85cf0f4-cbf8-11e5-8b73-bcefa445de23.png)
then an error appears in suitecrm.log:
"Query Failed: SELECT `accounts`.id AS 'accounts_id', `accounts`.name AS 'Name0', `accounts`.date_modified AS 'Date_Modified1' FROM `accounts`  WHERE ( `accounts`.date_modified <= DATE_ADD(NOW, INTERVAL + 1 month) ) AND  accounts.deleted = 0 : MySQL error 1054: Unknown column 'NOW' in 'where clause'"

The generated by SuiteCRM query lack of expression "()" after the "NOW". The correct expression should be "NOW()" and then the correct query should be: 
`SELECT `accounts`.id AS 'accounts_id', `accounts`.name AS 'Name0', `accounts`.date_modified AS 'Date_Modified1' FROM `accounts` WHERE ( `accounts`.date_modified <= DATE_ADD(NOW(), INTERVAL + 1 month) ) AND accounts.deleted = 0`

**Comment by virtualme123** [comment]
I'm having issues with dates on the reports. I don't seem to be able to get equals to 'period' working properly. In the SQL it is putting the date entered as "2016-03-07 00:00:00". So I assume because that time doesn't exist in any of my records it won't show anything for that day.

Surprised I can't see others with this issue highlighted though, is it relates to my instance alone?

SuiteCRM - 7.5.2
PHP 5.3.10

**Comment by ijdavie** [comment]
@macala - there has been large advancements with Reports, can you confirm this is still an issue in the latest version of SuiteCRM ? if it is not a issue any longer can you close this ? 
Thanks,

**Comment by virtualme123** [comment]
just checked and it appears to work for me now - thanks!

**Comment by ijdavie** [comment]
@virtualme123, Thanks for letting us know this is resolved.  
Thanks
