### ISSUE TITLE
Mpdf backport change not in the latest version of SuiteCRM

### ISSUE THREAD

**Issue by Isac99** [salesagility/SuiteCRM#9228]
#### Issue

Mpdf is a very old version and causes errors in PHP 7.x . A fix was created here https://github.com/Dillon-Brown/SuiteCRM/tree/fix/backport_mpdf but it is not in the latest version of SuiteCRM. I am getting lots of errors with the Print as PDF function caused by this in the apache error log. PDF's are taking over 2 minutes to render. I am attempting to take the code from the backport and put it into version 7.11.20
#### Expected Behavior

I hope this change can be brought into the main codebase of SuiteCRM
#### Steps to Reproduce

1.
2.
3.
4.

#### Context

This is a high priority for my client as they need to produce contracts for clients in a timely manner. This is disrupting their business.
#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by tsmgeek** [comment]
The errors itself should not cause it to take 2 mins.
To rule out the errors being the issue, disable error logging for PHP and run a report again.

PDF generation in PHP is not great as it stands especially when there is lots of data and many pages, worst is when these libraries are used to do html2pdf which is why I was looking to add in support for wkhtml2pdf in the future and @Dillon-Brown has done a load of refactoring that should make this area pluggable in the future.

**Comment by Isac99** [comment]
Quick update... the issue turned out to be images in the template that were referenced using an IP address URL. We changed the IP address of the server and the 2 minute wait was caused by a timeout waiting for the images to load. I changed the URL of the images in the database to the FQDN and all was well.
