### ISSUE TITLE
PopupView buttons position

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#925]
Hi, i want ask, if it will possible, that those buttons will in one line  (one row)

The buttons take to much place in this Popup windows in all modules.

![company](https://cloud.githubusercontent.com/assets/5773777/12879416/be89a2a0-ce32-11e5-8883-8dfb05c0b3b5.png)

![target](https://cloud.githubusercontent.com/assets/5773777/12879503/5f3bc830-ce34-11e5-9077-1e96766cc0e8.png)

**Comment by ghermans** [comment]
## Work in progress 

- Added ```<div class="btn-group"> ```
- Changed ```<input type="button"> ``` to ```<button> ```

![selection_126](https://cloud.githubusercontent.com/assets/1594411/13236887/c483639e-d9c7-11e5-9da2-e67ca55eb2e9.png)

**Comment by ghermans** [comment]
@Mausino i just created a pull request for this suggestion, lets hope this will get merged soon in the hotfix/master. @willrennie @mattlorimer @JimMackin can you guys please verify this one? thanks in advance for the cooperation

**Comment by pgorod** [comment]
@ghermans thanks for the fix, I was also bothered by this one...

There is an additional issue that is quite simple to fix. I think **it could be added to your fix** because it is also about this same popup box, and it is also an issue of layout wasting vertical space.

Basically, if you go in https://github.com/salesagility/SuiteCRM/blob/26fbd737a47163bff07e1ff828fc488e7e5075bb/modules/Contacts/metadata/popupdefs.php
and change the order of the `searchdefs` list to become this: 

```
// items in this list alternate between left- and right-hand side when displayed:
	'searchdefs'   => array(
	 	'first_name', 
		'last_name', 
		array('name' => 'account_name', 'type' => 'varchar',),
		'title',
        array('name' => 'assigned_user_id', 'type' => 'enum', 'label' => 'LBL_ASSIGNED_TO', 'function' => array('name' => 'get_user_array', 'params' => array(false))),
        'lead_source',
		'email',
        array('name' => 'campaign_name', 'displayParams' => array('hideButtons'=>'true', 'size'=>30, 'class'=>'sqsEnabled sqsNoAutofill')),
	  )
```

Everything will be much better arranged (compare this with the screenshots above):

![popup1](https://cloud.githubusercontent.com/assets/15945027/15077671/7009215e-13a7-11e6-8701-25f70b147dbe.jpg)

The two boxes with lists are now side-by-side, saving vertical space; and the fields related to the record (Account, assigned, email) go on the left, while the two fields related to marketing go on the right (campaign, lead source).

I propose that my comment in the code above can also be included into the file, for future reference.

**Comment by pgorod** [comment]
I was focusing on Contacts bit I just noticed the other modules also need attention. The Accounts popup is particularly horrendous. But it seems the searchdefs are specified differently, I don't know why...

Anyway, if the Contacts module gets improved, that would be a start.

**Comment by ghermans** [comment]
@pgorod thanks for the feedback, i will check this tonight.

**Comment by pgorod** [comment]
@ghermans did you get a chance to look into this? Thanks.

**Comment by ghermans** [comment]
@pgorod  sorry for the late response, i didn't got the time to have a look at this.

**Comment by Mausino** [comment]
@ghermans thanks, we are using your code from February :)

**Comment by samus-aran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PopupView buttons position](https://trello.com/c/XHDmmHBV/118-popupview-buttons-position)

**Comment by samus-aran** [comment]
We have now set up a new home for suggestions at Trello.  All github issues that were labeled 'suggestion' have been moved and will be closed.  Certain ones will be progressed within the new Suggestion Box and may be re-opened.

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box
