### ISSUE TITLE
System Administrator User access gets disabled with 2fa plugin installed and enabled

### ISSUE THREAD

**Issue by croniserb** [salesagility/SuiteCRM#9307]
#### Issue
If the user is a System Administrator User in suitecrm and 2FA is enabled, the user is demoted to a regular user on next login. The database table 'users' is changing the 'is_admin' value of 1 to 0. This occurs right after the QRcode value is entered. This is a fresh install and was not upgraded from a previous version.  This issue was originally sent to the Two-Factor Authentication plugin developers because of where the change appeared to be happening.  They do not see the is_admin value being set/changed in the code base.  The link to that reported issue is https://store.suitecrm.com/support/google-authentication/3881#post_13971. 

#### Expected Behavior
'is_admin' should  stay set to 1

#### Actual Behavior
'is_admin' is being set to  0

#### Possible Fix
I don't have the fix.  The current workaround is:
update users SET is_admin=1 WHERE user_name='admin';

#### Steps to Reproduce

1.  Install CentOS 7.9.2009 and all updates
2.  Install Mariadb 10.6.4 client and server
3.  Install php remi 7.4.24 and all required additional packages
4.  Install httpd for the apache webserver distributed with CentOS 7 
5.  Install and configure SuiteCRM 7.11.22 using the default settings 
6.  Install and configure Two-Factor Authentication (https://store.suitecrm.com/support/google-authentication)
7.  Setup a user account as System Administrator User and enable Two-Factor Authentication
8.  Logout of the current session. 
9. Login with the new System Administrator User using 2FA.
10.  Try to access the Admin pages for SuiteCRM.  The user is a Regular User and not  System Administrator User

#### Context
Medium priority.  Since there is a work around for the time being.  However, it is very annoying to change the user to admin every time a task needs to be completed.

#### Your Environment
The environment is setup in the above steps.
Safari, Firefox, and Chrome on the current version have the same issue.

**Comment by johnM2401** [comment]
Hi there, 

I have given this a try on a local 7.11.22, but I cannot seem to replicate this with the out-of-the-box 2FA functionality, I'm afraid.

My users appear to retain their Admin status

<br>

Do you know if this issue occurs with the standard, vanilla, 2FA functionality?
(User receives an Email with a Code upon Login)

Or does this only appear when this Store Plugin is installed?


<br>

Another thing to note is that the [Compatiblity Matrix](https://docs.suitecrm.com/admin/compatibility-matrix/) currently does not list MariaDB 10.6 as a compatible version

I'm not well-versed in the differences between MariaDB versions, but it very well could be a cause of the issue

Would you be able to confirm with a compatible MariaDB version?

**Comment by croniserb** [comment]
I only have the Store Plugin configured for use right now.  I was under the impression that I needed that from another company I am working with.  It is my first time installing/using suitecrm.  

With the server is in production right now due to a time crunch.  I'm trying to avoid rolling back MariaDB at the moment since it only seems to be the is_admin value that is having an issue and I have a workaround.    Would you be able to dig in to the store version of 2FA plugin path since they don't see the is_admin value in there code?

Unfortunately I missed the compatibility matrix before I moved it to production.

**Comment by johnM2401** [comment]
Hey there, 

Thanks for getting back in touch!

Unfortunately, we don't maintain (or provide support for) the plugins on the Store to that extent, I'm afraid


However, I *would* recommend passing over all the information here, (ie; Steps to Replicate, MariaDB ver. being outside of Compatibility), to the Plugin provider, to allow them to investigate further.
(If you have not, already)

I'd also recommend, when you have time, ensuring that your Environment meets the Compatibility Matrix to avoid any potential oddness/issues in the future.
(Although, luckily, you do have a workaround for this current issue)


<br>

I'd be more than happy to continue investigating if you (or the provider) are able to confirm that this issue is unrelated to the Plugin, or any other Customisations, and is indeed a bug with SuiteCRM itself.

<br>

Also, If you are curious about the vanilla 2FA functionality, (or need Documentation on anything else), you can find further information here:
https://docs.suitecrm.com/user/modules/passwordmanagement/#_two_factor_authentication

<br>

Please let us know if you have any updates on this, any questions, or if you come across any further information that would help with replicating this issue.

Thanks!

**Comment by pgorod** [comment]
Seems to be a known issue, solved by updating plugin to V5:
https://store.suitecrm.com/support/google-authentication/3881
