### ISSUE TITLE
AOP - External portal

### ISSUE THREAD

**Issue by ghermans** [salesagility/SuiteCRM#985]
Currently when you click on "Create portal user"  it calls the Joomla url 
```php
$portalURL.'/index.php?option=com_advancedopenportal&task=create&sug='.$_REQUEST['record']
```
My suggestion is: allow SuiteCRM to create a portal user for other portals instead only the Joomla plugin.

**Comment by chris001** [comment]
:+1:
AOP should add support for creating user accounts in Wordpress also.  Or, users can install the wordpress plugin for a suitecrm user case support portal on wordpress.org, instead of the suitecrm AOP module and AOP joomla component.

To get full connection to any portal, AOP would need to support 104 popular portal apps:  
http://www.capterra.com/portal-software/

A streamlined suitecrm REST JSON API could connect to most/all of those portals' REST JSON APIs, and sync the support case ticket data, in both directions.

A software subscription service which would connect and sync suitecrm with any one of the top 104 user to organization portal apps, would easily be a multi million dollar/euro/pound business.

**Comment by vjaro** [comment]
I agree with @ghermans .
It would be best if we can create portal users in suitecrm without having to rely on joomla and wordpress. This way, we can create custom portal applications independent of the platforms in place.

**Comment by ghermans** [comment]
@willrennie @gregsoper could we perhaps integrate this in the LTS release?

**Comment by gregsoper** [comment]
Where does this particular train stop? Wordpress, Drupal, Concrete5 .... the list is endless. We needed to make a choice and we've made it. We seriously welcome contributions that extend the portal to other CMS's but the core project Portal choice is Joomla. We won't please everyone but the focus has to be narrow in order to be excellent.

**Comment by ghermans** [comment]
@gregsoper thanks for the feedback.
